import { ArrowLeft, Check, Clock3, ExternalLink, FileText, FlaskConical, Route } from "lucide-react";
import Link from "next/link";
import { notFound, redirect } from "next/navigation";

import { ApplicationStatusBadge } from "@/components/dashboard/testing-applications/ApplicationStatusBadge";
import { getExecutiveTestingReport } from "@/features/testing-applications/executive-testing-report.service";
import { requireTestingReportViewer } from "@/features/testing-applications/testing-application.auth";

interface Props { readonly params: Promise<{ readonly id: string }> }
interface Detail {
  readonly id: string; readonly applicationNumber: string; readonly status: string; readonly purpose: string | null; readonly otherPurpose: string | null; readonly testingTypes: readonly string[]; readonly notes: string | null; readonly submittedAt: string | null; readonly reviewedAt: string | null; readonly approvedAt: string | null; readonly updatedAt: string;
  readonly businessProfile: { readonly business: { readonly name: string; readonly businessCode: string }; readonly addressLine: string | null; readonly whatsapp: string | null; readonly picName: string | null };
  readonly laboratory: { readonly name: string; readonly address: string | null } | null;
  readonly product: { readonly productName: string | null; readonly productType: string | null; readonly hsCode: string | null; readonly productForm: string | null; readonly description: string | null } | null;
  readonly samples: readonly { readonly id: string; readonly sampleName: string | null; readonly quantity: number | null; readonly weight: string | null; readonly weightUnit: string | null; readonly packaging: string | null; readonly condition: string | null; readonly samplingDate: string | null; readonly samplingLocation: string | null; readonly temperature: string | null; readonly description: string | null }[];
  readonly parameters: readonly { readonly id: string; readonly parameter: { readonly name: string; readonly method: string | null }; readonly sample: { readonly sampleName: string | null } }[];
  readonly documents: readonly { readonly id: string; readonly documentType: string; readonly documentName: string | null; readonly fileName: string; readonly mimeType: string; readonly fileSize: string; readonly uploadedAt: string }[];
  readonly sampleShipment: { readonly shippingDate: string; readonly shippingMethod: string; readonly carrierName: string | null; readonly trackingNumber: string | null; readonly packageCount: number; readonly conditionNotes: string | null; readonly senderName: string } | null;
  readonly sampleReview: { readonly decision: string; readonly notes: string | null; readonly reviewedAt: string } | null;
  readonly workOrders: readonly { readonly id: string; readonly workOrderNumber: string; readonly type: string; readonly status: string; readonly testingMethod: string | null; readonly assignedAt: string | null; readonly targetCompletionDate: string | null; readonly sentToSupervisorAt: string | null; readonly reviewedAt: string | null; readonly analystNotes: string | null; readonly supervisorNotes: string | null; readonly applicationParameter: { readonly parameter: { readonly name: string; readonly method: string | null }; readonly sample: { readonly sampleName: string | null } }; readonly analyst: { readonly profile: { readonly fullName: string } | null } | null; readonly assignedBy: { readonly profile: { readonly fullName: string } | null } | null; readonly documents: readonly { readonly id: string; readonly type: string; readonly fileName: string; readonly mimeType: string; readonly fileSize: string; readonly uploadedAt: string }[] }[];
  readonly laboratoryReport: { readonly id: string; readonly reportNumber: string; readonly status: string; readonly reportDate: string; readonly conclusion: string; readonly notes: string | null; readonly submittedAt: string | null; readonly approvedAt: string | null; readonly finalFileName: string | null; readonly publishedAt: string | null } | null;
}

export default async function ReportDetailPage({ params }: Props) {
  try { await requireTestingReportViewer(); } catch { redirect("/dashboard"); }
  const { id } = await params;
  if (!/^\d+$/.test(id)) notFound();
  let item: Detail;
  try {
    item = await getExecutiveTestingReport(id) as Detail;
  } catch (error) {
    if (error instanceof Error && error.message === "NOT_FOUND") notFound();
    throw error;
  }
  const steps = [
    ["Permohonan diajukan", item.submittedAt],
    ["Pemeriksaan administrasi", item.reviewedAt],
    ["Persetujuan Kepala UPTD", item.approvedAt],
    ["Pengiriman sampel", item.sampleShipment?.shippingDate ?? null],
    ["Kaji ulang sampel", item.sampleReview?.reviewedAt ?? null],
    ["Pengerjaan pengujian", item.workOrders.find((workOrder) => workOrder.assignedAt)?.assignedAt ?? null],
    ["Verifikasi seluruh hasil", item.workOrders.length && item.workOrders.every((workOrder) => workOrder.status === "HASIL_TERVERIFIKASI") ? item.workOrders.find((workOrder) => workOrder.reviewedAt)?.reviewedAt ?? item.updatedAt : null],
    ["Penerbitan LHU", item.laboratoryReport?.publishedAt ?? null],
  ] as const;
  return <div className="space-y-6">
    <header><Link href="/dashboard/reports" className="inline-flex items-center gap-2 text-sm font-bold text-[#087E8B]"><ArrowLeft size={16} /> Kembali ke laporan pengajuan</Link><div className="mt-4 flex flex-wrap items-start justify-between gap-4"><div><p className="text-sm font-bold text-[#087E8B]">{item.applicationNumber}</p><h1 className="mt-1 text-3xl font-bold text-[#073B4C]">Detail Laporan Pengajuan</h1><p className="mt-2 text-sm text-slate-500">{item.businessProfile.business.name} · {item.product?.productName || "Produk belum diberi nama"}</p></div><ApplicationStatusBadge status={item.status} /></div></header>
    <nav className="flex flex-wrap gap-2"><Anchor href="#pengajuan" label="Pengajuan" /><Anchor href="#sampel" label="Sampel & Parameter" /><Anchor href="#dokumen" label="Dokumen" /><Anchor href="#hasil" label="Hasil Pengujian" /><Anchor href="#tracking" label="Tracking Proses" /></nav>
    <div className="grid gap-6 xl:grid-cols-[minmax(0,1fr)_360px]"><main className="space-y-6">
      <Section id="pengajuan" title="Informasi Lengkap Pengajuan" icon={<FileText size={18} />}><dl className="grid gap-4 sm:grid-cols-2"><Info label="Pelaku usaha" value={`${item.businessProfile.business.name} (${item.businessProfile.business.businessCode})`} /><Info label="Kontak" value={[item.businessProfile.picName, item.businessProfile.whatsapp].filter(Boolean).join(" · ")} /><Info label="Alamat usaha" value={item.businessProfile.addressLine} /><Info label="Laboratorium" value={item.laboratory?.name} /><Info label="Tujuan" value={item.otherPurpose || formatEnum(item.purpose)} /><Info label="Jenis pengujian" value={item.testingTypes.map(formatEnum).join(", ")} /><Info label="Tanggal diajukan" value={formatDate(item.submittedAt)} /><Info label="Catatan" value={item.notes} /></dl></Section>
      <Section id="sampel" title="Sampel dan Parameter Pengujian" icon={<FlaskConical size={18} />}><div className="grid gap-4 md:grid-cols-2">{item.samples.map((sample) => <article key={sample.id} className="rounded-xl border border-slate-200 p-4"><h3 className="font-bold text-[#073B4C]">{sample.sampleName || "Sampel tanpa nama"}</h3><p className="mt-2 text-xs leading-5 text-slate-500">{sample.quantity ?? "-"} unit · {sample.weight ?? "-"} {sample.weightUnit ?? ""}<br />Kemasan: {sample.packaging || "-"} · Kondisi: {formatEnum(sample.condition)}</p></article>)}</div><div className="mt-4 overflow-x-auto"><table className="w-full min-w-[520px] text-left text-sm"><thead className="bg-slate-50 text-xs text-slate-500"><tr><th className="p-3">Sampel</th><th className="p-3">Parameter</th><th className="p-3">Metode</th></tr></thead><tbody>{item.parameters.map((mapping) => <tr key={mapping.id} className="border-t"><td className="p-3">{mapping.sample.sampleName || "-"}</td><td className="p-3 font-semibold">{mapping.parameter.name}</td><td className="p-3">{mapping.parameter.method || "-"}</td></tr>)}</tbody></table></div></Section>
      <Section id="dokumen" title={`Dokumen Pengajuan (${item.documents.length})`} icon={<FileText size={18} />}><div className="grid gap-3 sm:grid-cols-2">{item.documents.map((document) => <a key={document.id} href={`/api/testing-applications/${item.id}/documents/${document.id}`} target="_blank" rel="noopener noreferrer" className="flex items-center justify-between gap-3 rounded-xl border border-slate-200 p-4 transition hover:border-[#087E8B] hover:bg-cyan-50"><span className="min-w-0"><strong className="block truncate text-sm text-[#073B4C]">{document.documentName || formatEnum(document.documentType)}</strong><small className="block truncate text-slate-500">{document.fileName} · {formatSize(document.fileSize)}</small></span><ExternalLink size={17} className="shrink-0 text-[#087E8B]" /></a>)}</div>{!item.documents.length && <p className="text-sm text-slate-500">Tidak ada dokumen pengajuan.</p>}</Section>
      <Section id="hasil" title="Hasil Pengujian per Parameter" icon={<FlaskConical size={18} />}><div className="space-y-4">{item.workOrders.map((workOrder) => <article key={workOrder.id} className="rounded-xl border border-slate-200 p-4"><div className="flex flex-wrap items-start justify-between gap-3"><div><p className="text-xs font-bold text-[#087E8B]">{workOrder.workOrderNumber}</p><h3 className="mt-1 font-bold text-[#073B4C]">{workOrder.applicationParameter.parameter.name}</h3><p className="mt-1 text-xs text-slate-500">{workOrder.applicationParameter.sample.sampleName || "-"} · {workOrder.testingMethod || workOrder.applicationParameter.parameter.method || "-"}</p></div><span className="rounded-full bg-slate-100 px-3 py-1 text-[10px] font-bold">{formatEnum(workOrder.status)}</span></div><dl className="mt-3 grid gap-3 text-xs sm:grid-cols-2"><Info label="Analis" value={workOrder.analyst?.profile?.fullName} /><Info label="Penyelia" value={workOrder.assignedBy?.profile?.fullName} /></dl>{workOrder.documents.length > 0 && <div className="mt-3 flex flex-wrap gap-2">{workOrder.documents.map((document) => <a key={document.id} href={`/api/work-orders/${workOrder.id}/documents?documentId=${document.id}`} target="_blank" rel="noopener noreferrer" className="inline-flex items-center gap-1.5 rounded-lg border px-3 py-2 text-xs font-bold text-[#087E8B]"><ExternalLink size={14} /> {document.fileName}</a>)}</div>}</article>)}</div>{!item.workOrders.length && <p className="text-sm text-slate-500">Work Order belum diterbitkan.</p>}</Section>
    </main><aside id="tracking" className="h-fit scroll-mt-24 rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><h2 className="flex items-center gap-2 font-bold text-[#073B4C]"><Route size={18} /> Tracking Proses Pengujian</h2><ol className="mt-5">{steps.map(([label, date], index) => <li key={label} className="relative grid grid-cols-[32px_1fr] gap-3 pb-5 last:pb-0">{index < steps.length - 1 && <span className={`absolute left-[15px] top-7 h-[calc(100%-8px)] w-0.5 ${date ? "bg-[#61C0BF]" : "bg-slate-200"}`} />}<span className={`relative z-10 flex h-8 w-8 items-center justify-center rounded-full ${date ? "bg-[#087E8B] text-white" : "bg-slate-100 text-slate-400"}`}>{date ? <Check size={15} /> : <Clock3 size={14} />}</span><div><p className={`text-sm font-bold ${date ? "text-[#073B4C]" : "text-slate-400"}`}>{label}</p><p className="mt-1 text-xs text-slate-500">{formatDate(date)}</p></div></li>)}</ol>{item.laboratoryReport && <div className="mt-5 rounded-xl bg-cyan-50 p-4"><p className="text-xs font-bold text-[#087E8B]">Laporan Hasil Uji</p><p className="mt-1 font-bold text-[#073B4C]">{item.laboratoryReport.reportNumber}</p><p className="mt-1 text-xs text-slate-500">{formatEnum(item.laboratoryReport.status)}</p>{item.laboratoryReport.status === "DITERBITKAN" && <a href={`/api/laboratory-reports/${item.laboratoryReport.id}/final-file`} className="mt-3 inline-flex text-xs font-bold text-[#087E8B]">Lihat LHU final</a>}</div>}</aside></div>
  </div>;
}

function Section({ id, title, icon, children }: { readonly id: string; readonly title: string; readonly icon: React.ReactNode; readonly children: React.ReactNode }) { return <section id={id} className="scroll-mt-24 rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><h2 className="mb-4 flex items-center gap-2 font-bold text-[#073B4C]">{icon}{title}</h2>{children}</section>; }
function Info({ label, value }: { readonly label: string; readonly value?: string | null }) { return <div><dt className="text-xs text-slate-400">{label}</dt><dd className="mt-1 text-sm font-semibold text-slate-700">{value || "-"}</dd></div>; }
function Anchor({ href, label }: { readonly href: string; readonly label: string }) { return <a href={href} className="rounded-full border border-slate-200 bg-white px-3 py-2 text-xs font-bold text-[#073B4C] hover:border-[#087E8B]">{label}</a>; }
function formatEnum(value?: string | null): string { return value ? value.replaceAll("_", " ").toLocaleLowerCase("id-ID").replace(/^\p{L}/u, (letter) => letter.toLocaleUpperCase("id-ID")) : "-"; }
function formatDate(value?: string | null): string { return value ? new Intl.DateTimeFormat("id-ID", { dateStyle: "medium", timeStyle: "short", timeZone: "Asia/Jakarta" }).format(new Date(value)) : "Belum tersedia"; }
function formatSize(value: string): string { const bytes = Number(value); return bytes < 1_048_576 ? `${Math.max(1, Math.round(bytes / 1024))} KB` : `${(bytes / 1_048_576).toFixed(1)} MB`; }
