"use client";

import { ArrowLeft, CalendarDays, FileSpreadsheet, MapPin, Search, UserRound, X } from "lucide-react";
import Link from "next/link";
import { useMemo, useState } from "react";

import { CoachingActivityType, type CoachingActivityRow } from "@/features/executive-dashboard/coaching-summary.types";

import { formatExecutiveDate, humanizeStatus, statusClass } from "./ExecutiveSummaryUi";

export function CoachingDetailReport({ generatedAt, rows }: { readonly generatedAt: string; readonly rows: readonly CoachingActivityRow[] }) {
  const [activeType, setActiveType] = useState(CoachingActivityType.QUALITY_CLINIC);
  const [query, setQuery] = useState("");
  const [selected, setSelected] = useState<CoachingActivityRow | null>(null);
  const keyword = query.trim().toLocaleLowerCase("id-ID");
  const filteredRows = useMemo(() => rows.filter((item) => item.type === activeType && (!keyword || [item.title, item.businessName, item.requesterName, item.consultantName ?? "", item.status].some((value) => value.toLocaleLowerCase("id-ID").includes(keyword)))), [activeType, keyword, rows]);

  return <div className="space-y-6">
    <header className="flex flex-col gap-5 lg:flex-row lg:items-end lg:justify-between"><div><Link href="/dashboard/coaching-summary" className="inline-flex items-center gap-2 text-xs font-bold text-ocean"><ArrowLeft className="h-4 w-4" />Kembali ke ringkasan</Link><p className="mt-5 text-xs font-bold uppercase tracking-[.14em] text-ocean">Laporan Pimpinan</p><h1 className="mt-2 text-3xl font-bold text-navy">Laporan Lengkap Pembinaan</h1><p className="mt-2 text-sm leading-6 text-muted">Telusuri kegiatan Klinik Mutu dan Konsultasi Daring serta buka rincian setiap kegiatan.</p></div><span className="inline-flex w-fit items-center gap-2 rounded-xl border border-slate-200 bg-white px-4 py-3 text-xs font-semibold text-muted"><FileSpreadsheet className="h-4 w-4 text-ocean" />Data per {formatExecutiveDate(generatedAt)}</span></header>
    <section className="overflow-hidden rounded-3xl border border-slate-200 bg-white shadow-sm"><div className="flex flex-col gap-4 border-b border-slate-100 p-5 lg:flex-row lg:items-center lg:justify-between"><div className="flex rounded-xl bg-slate-100 p-1" role="tablist" aria-label="Jenis pembinaan">{[CoachingActivityType.QUALITY_CLINIC, CoachingActivityType.ONLINE_CONSULTATION].map((type) => <button key={type} type="button" role="tab" aria-selected={activeType === type} onClick={() => setActiveType(type)} className={`min-h-10 rounded-lg px-4 text-sm font-bold transition ${activeType === type ? "bg-white text-navy shadow-sm" : "text-muted hover:text-navy"}`}>{type === CoachingActivityType.QUALITY_CLINIC ? "Klinik Mutu" : "Konsultasi Daring"}</button>)}</div><label className="relative block lg:w-96"><Search className="absolute left-3.5 top-1/2 h-4 w-4 -translate-y-1/2 text-slate-400" /><span className="sr-only">Cari kegiatan</span><input value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Cari kegiatan atau pelaku usaha..." className="min-h-11 w-full rounded-xl border border-slate-200 bg-slate-50 pl-10 pr-4 text-sm outline-none focus:border-ocean focus:bg-white" /></label></div>
      <div className="overflow-x-auto"><table className="w-full min-w-[900px] text-left text-sm"><thead className="bg-slate-50 text-[10px] uppercase tracking-wider text-muted"><tr>{["Kegiatan", "Pelaku Usaha", "Pemohon", "Pendamping", "Tanggal", "Status", "Aksi"].map((label) => <th key={label} className="px-5 py-4">{label}</th>)}</tr></thead><tbody className="divide-y divide-slate-100">{filteredRows.map((item) => <tr key={item.id} className="hover:bg-slate-50/70"><Cell value={item.title} strong /><Cell value={item.businessName} /><Cell value={item.requesterName} /><Cell value={item.consultantName ?? "Belum ditugaskan"} /><Cell value={formatExecutiveDate(item.createdAt)} /><td className="px-5 py-4"><span className={`inline-flex rounded-full px-3 py-1.5 text-[10px] font-bold ${statusClass(item.status)}`}>{humanizeStatus(item.status)}</span></td><td className="px-5 py-4"><button type="button" onClick={() => setSelected(item)} className="rounded-lg border border-ocean/20 px-3 py-2 text-xs font-bold text-ocean hover:bg-seafoam">Lihat detail</button></td></tr>)}</tbody></table></div><div className="border-t border-slate-100 px-6 py-4 text-xs text-muted">Menampilkan {filteredRows.length.toLocaleString("id-ID")} kegiatan</div>
    </section>
    {selected && <DetailDialog item={selected} onClose={() => setSelected(null)} />}
  </div>;
}

function DetailDialog({ item, onClose }: { readonly item: CoachingActivityRow; readonly onClose: () => void }) {
  return <div className="fixed inset-0 z-50 flex items-end justify-center bg-navy/55 p-0 backdrop-blur-sm sm:items-center sm:p-6" role="presentation" onMouseDown={(event) => { if (event.currentTarget === event.target) onClose(); }}><section role="dialog" aria-modal="true" aria-labelledby="coaching-detail-title" className="max-h-[90vh] w-full max-w-2xl overflow-y-auto rounded-t-3xl bg-white shadow-2xl sm:rounded-3xl"><header className="sticky top-0 flex items-start justify-between border-b border-slate-100 bg-white p-6"><div><p className="text-xs font-bold uppercase tracking-wider text-ocean">{item.type === CoachingActivityType.QUALITY_CLINIC ? "Klinik Mutu" : "Konsultasi Daring"}</p><h2 id="coaching-detail-title" className="mt-2 text-xl font-bold text-navy">{item.title}</h2></div><button type="button" onClick={onClose} aria-label="Tutup detail" className="rounded-xl p-2 text-muted hover:bg-slate-100"><X className="h-5 w-5" /></button></header><div className="space-y-6 p-6"><div className="grid gap-3 sm:grid-cols-2"><Info icon={UserRound} label="Pelaku usaha" value={item.businessName} /><Info icon={UserRound} label="Pemohon" value={item.requesterName} /><Info icon={UserRound} label="Pendamping" value={item.consultantName ?? "Belum ditugaskan"} /><Info icon={CalendarDays} label="Tanggal dibuat" value={formatExecutiveDate(item.createdAt)} />{item.scheduledAt && <Info icon={CalendarDays} label="Jadwal" value={formatExecutiveDate(item.scheduledAt)} />}{item.location && <Info icon={MapPin} label="Lokasi" value={item.location} />}</div><div><p className="text-xs font-bold uppercase tracking-wider text-muted">Status</p><span className={`mt-2 inline-flex rounded-full px-3 py-1.5 text-xs font-bold ${statusClass(item.status)}`}>{humanizeStatus(item.status)}</span></div>{item.category && <TextBlock label="Kategori" value={humanizeStatus(item.category)} />}<TextBlock label={item.type === CoachingActivityType.QUALITY_CLINIC ? "Uraian kebutuhan" : "Pertanyaan konsultasi"} value={item.description} />{item.consultantNote && <TextBlock label="Catatan pendamping" value={item.consultantNote} />}{item.type === CoachingActivityType.ONLINE_CONSULTATION && <TextBlock label="Aktivitas percakapan" value={`${item.responseCount.toLocaleString("id-ID")} tanggapan tercatat`} />}</div></section></div>;
}

function Cell({ value, strong = false }: { readonly value: string; readonly strong?: boolean }) { return <td className={`px-5 py-4 ${strong ? "font-bold text-navy" : "text-ink"}`}>{value}</td>; }
function Info({ icon: Icon, label, value }: { readonly icon: typeof UserRound; readonly label: string; readonly value: string }) { return <div className="rounded-2xl bg-slate-50 p-4"><p className="flex items-center gap-2 text-xs font-semibold text-muted"><Icon className="h-4 w-4 text-ocean" />{label}</p><p className="mt-2 text-sm font-bold text-navy">{value}</p></div>; }
function TextBlock({ label, value }: { readonly label: string; readonly value: string }) { return <div><p className="text-xs font-bold uppercase tracking-wider text-muted">{label}</p><p className="mt-2 whitespace-pre-wrap text-sm leading-6 text-ink">{value}</p></div>; }
