import { notFound, redirect } from "next/navigation";
import { SampleShipmentForm } from "@/components/dashboard/testing-applications/SampleShipmentForm";
import { getApplication } from "@/features/testing-applications/testing-application.service";
import { getCurrentUser, resolveCurrentBusiness } from "@/lib/business/get-current-business";
interface Detail { readonly applicationNumber: string | null; readonly status: string; readonly sampleShipment: { readonly shippingDate: string; readonly shippingMethod: string; readonly carrierName: string | null; readonly trackingNumber: string | null; readonly packageCount: number; readonly evidence: readonly { readonly id: string; readonly fileName: string }[] } | null }
export default async function SampleShipmentPage({ params }: { readonly params: Promise<{ readonly id: string }> }) {
  const user = await getCurrentUser(); if (!user) redirect("/login"); const membership = await resolveCurrentBusiness(user.id); if (!membership) redirect("/dashboard");
  const { id } = await params; let item: Detail; try { item = await getApplication({ userId: user.id, businessId: membership.businessId }, id) as Detail; } catch { notFound(); }
  if (item.status !== "MENUNGGU_SAMPEL" && !item.sampleShipment) redirect(`/dashboard/permohonan/${id}`);
  return <div className="space-y-6"><header><p className="text-sm font-bold text-[#087E8B]">{item.applicationNumber}</p><h1 className="mt-1 text-3xl font-bold text-[#073B4C]">Pengiriman Sampel Fisik</h1><p className="mt-2 text-sm text-slate-500">Bukti ini bersifat operasional untuk pencocokan sampel saat diterima laboratorium.</p></header>{item.sampleShipment ? <section className="rounded-2xl border border-emerald-200 bg-emerald-50 p-6"><h2 className="font-bold text-emerald-800">Berita Pengiriman Sampel Tercatat</h2><dl className="mt-4 grid gap-3 text-sm sm:grid-cols-2"><Info label="Tanggal" value={new Intl.DateTimeFormat("id-ID", { dateStyle: "long" }).format(new Date(item.sampleShipment.shippingDate))}/><Info label="Metode" value={item.sampleShipment.shippingMethod.replaceAll("_", " ")}/><Info label="Ekspedisi/pengantar" value={item.sampleShipment.carrierName}/><Info label="Nomor resi" value={item.sampleShipment.trackingNumber}/><Info label="Jumlah kemasan" value={`${item.sampleShipment.packageCount} kemasan`}/><Info label="Bukti" value={`${item.sampleShipment.evidence.length} file`}/></dl></section> : <SampleShipmentForm applicationId={id}/>}</div>;
}
function Info({ label, value }: { readonly label: string; readonly value?: string | null }) { return <div><dt className="text-slate-500">{label}</dt><dd className="font-semibold text-slate-700">{value || "-"}</dd></div>; }
