"use client";
import Link from "next/link";
import { Eye, FilePenLine, Plus, Search, Trash2 } from "lucide-react";
import { useCallback, useEffect, useState } from "react";
import { ApplicationStatusBadge } from "./ApplicationStatusBadge";
interface Item { readonly id: string; readonly applicationNumber: string | null; readonly createdAt: string; readonly purpose: string | null; readonly otherPurpose: string | null; readonly status: string; readonly product: { readonly productName: string | null } | null; readonly _count: { readonly samples: number } }
interface Data { readonly items: readonly Item[]; readonly pagination: { readonly page: number; readonly total: number; readonly totalPages: number }; readonly stats: Readonly<Record<string, number>> }
const cards = [["total", "Total Permohonan"], ["DRAFT", "Draft"], ["DIAJUKAN", "Diajukan"], ["PERLU_PERBAIKAN", "Perlu Perbaikan"], ["DALAM_PENGUJIAN", "Diproses"], ["SELESAI", "Selesai"]] as const;
export function ApplicationsList() {
  const [data, setData] = useState<Data | null>(null); const [search, setSearch] = useState(""); const [status, setStatus] = useState(""); const [from, setFrom] = useState(""); const [page, setPage] = useState(1); const [loading, setLoading] = useState(true); const [message, setMessage] = useState("");
  const load = useCallback(async () => { setLoading(true); const query = new URLSearchParams({ search, page: String(page), ...(status ? { status } : {}), ...(from ? { from } : {}) }); const response = await fetch(`/api/testing-applications?${query}`); const result = await response.json() as { success: boolean; message: string; data?: Data }; if (result.success && result.data) setData(result.data); else setMessage(result.message); setLoading(false); }, [search, status, from, page]);
  useEffect(() => { const timer = setTimeout(() => void load(), 250); return () => clearTimeout(timer); }, [load]);
  async function remove(id: string) { if (!window.confirm("Hapus draft permohonan ini? Tindakan ini tidak dapat dibatalkan.")) return; const response = await fetch(`/api/testing-applications/${id}`, { method: "DELETE" }); const result = await response.json() as { success: boolean; message: string }; setMessage(result.message); if (result.success) await load(); }
  return <div className="space-y-6">
    <div className="flex flex-col gap-4 sm:flex-row sm:items-end sm:justify-between"><div><p className="text-xs font-bold uppercase tracking-widest text-[#087E8B]">Layanan Laboratorium</p><h1 className="mt-2 text-3xl font-bold text-[#073B4C]">Permohonan Pengujian</h1><p className="mt-2 text-sm text-slate-500">Kelola pengajuan pengujian sampel produk perikanan Anda.</p></div><Link href="/dashboard/permohonan/tambah" className="inline-flex items-center justify-center gap-2 rounded-xl bg-[#073B4C] px-5 py-3 text-sm font-bold text-white"><Plus size={18}/> Permohonan Baru</Link></div>
    {message && <div role="status" className="rounded-xl border border-[#0FA3B1]/20 bg-cyan-50 p-3 text-sm text-[#073B4C]">{message}</div>}
    <div className="grid grid-cols-2 gap-3 lg:grid-cols-6">{cards.map(([key, label]) => <div key={key} className="rounded-2xl border border-slate-200 bg-white p-4 shadow-sm"><p className="text-xs text-slate-500">{label}</p><p className="mt-2 text-2xl font-bold text-[#073B4C]">{data?.stats[key] ?? 0}</p></div>)}</div>
    <div className="rounded-2xl border border-slate-200 bg-white shadow-sm"><div className="grid gap-3 border-b border-slate-100 p-4 md:grid-cols-[1fr_220px_180px]"><label className="relative"><Search className="absolute left-3 top-3 h-4 w-4 text-slate-400"/><input aria-label="Cari permohonan" value={search} onChange={(event) => { setSearch(event.target.value); setPage(1); }} placeholder="Cari nomor atau nama produk" className="w-full rounded-xl border border-slate-200 py-2.5 pl-10 pr-3 text-sm"/></label><select aria-label="Filter status" value={status} onChange={(event) => { setStatus(event.target.value); setPage(1); }} className="rounded-xl border border-slate-200 px-3 text-sm"><option value="">Semua status</option>{["DRAFT","DIAJUKAN","PERLU_PERBAIKAN","DISETUJUI","MENUNGGU_SAMPEL","SAMPEL_DITERIMA","DALAM_PENGUJIAN","SELESAI","DITOLAK"].map((item) => <option key={item}>{item}</option>)}</select><input aria-label="Dari tanggal" type="date" value={from} onChange={(event) => { setFrom(event.target.value); setPage(1); }} className="rounded-xl border border-slate-200 px-3 text-sm"/></div>
      {loading ? <div className="space-y-3 p-6">{[1,2,3].map((item) => <div key={item} className="h-14 animate-pulse rounded-xl bg-slate-100"/>)}</div> : !data?.items.length ? <div className="p-14 text-center"><h2 className="font-bold text-[#073B4C]">Belum ada permohonan</h2><p className="mt-2 text-sm text-slate-500">Mulai dengan membuat permohonan pengujian pertama Anda.</p></div> : <div className="overflow-x-auto"><table className="w-full min-w-[900px] text-left text-sm"><thead className="bg-slate-50 text-xs uppercase text-slate-500"><tr>{["Nomor Permohonan","Tanggal","Tujuan Pengujian","Nama Produk","Jumlah Sampel","Status","Aksi"].map((label) => <th key={label} className="px-4 py-3">{label}</th>)}</tr></thead><tbody>{data.items.map((item) => <tr key={item.id} className="border-t border-slate-100"><td className="px-4 py-4 font-semibold text-[#073B4C]">{item.applicationNumber ?? `DRAFT-${item.id}`}</td><td className="px-4">{new Intl.DateTimeFormat("id-ID").format(new Date(item.createdAt))}</td><td className="px-4">{item.otherPurpose || item.purpose || "-"}</td><td className="px-4">{item.product?.productName || "Belum diisi"}</td><td className="px-4">{item._count.samples}</td><td className="px-4"><ApplicationStatusBadge status={item.status}/></td><td className="px-4"><div className="flex items-center gap-2"><Link title="Lihat" href={`/dashboard/permohonan/${item.id}`} className="rounded-lg p-2 text-[#087E8B] hover:bg-cyan-50"><Eye size={17}/></Link>{item.status === "DRAFT" && <><Link title="Lanjutkan pengisian" href={`/dashboard/permohonan/${item.id}/edit`} className="rounded-lg p-2 text-amber-600 hover:bg-amber-50"><FilePenLine size={17}/></Link><button title="Hapus" onClick={() => void remove(item.id)} className="rounded-lg p-2 text-red-600 hover:bg-red-50"><Trash2 size={17}/></button></>}</div></td></tr>)}</tbody></table></div>}
      {data && <div className="flex items-center justify-between border-t border-slate-100 p-4 text-sm"><span>{data.pagination.total} permohonan</span><div className="flex gap-2"><button disabled={page <= 1} onClick={() => setPage((value) => value - 1)} className="rounded-lg border px-3 py-2 disabled:opacity-40">Sebelumnya</button><span className="px-2 py-2">{page} / {data.pagination.totalPages}</span><button disabled={page >= data.pagination.totalPages} onClick={() => setPage((value) => value + 1)} className="rounded-lg border px-3 py-2 disabled:opacity-40">Berikutnya</button></div></div>}
    </div>
  </div>;
}
