"use client";

import { useEffect, useState } from "react";
import Image from "next/image";
import { AlertTriangle, ArrowLeft, Check, CheckCircle2, ChevronDown, ClipboardCheck, Download, FileUp, LoaderCircle, Plus, Save, Send, ShieldCheck, Trash2, X, XCircle } from "lucide-react";
import { useForm, useWatch } from "react-hook-form";
import { CertificationQuestionnaireWizard } from "./CertificationQuestionnaireWizard";
import { CertificationQuestionnaireDetail } from "./CertificationQuestionnaireDetail";

interface ApplicantSnapshot { readonly applicantName: string; readonly upiName: string; readonly identityNumber: string; readonly address: string; readonly phone: string; readonly email: string; readonly position: string; }
interface Contact { name: string; position: string; phone: string; email: string; }
interface SniReference { readonly id: string; readonly judul_standar: string; readonly nomor_sni: string; }
interface ProductInformation { productName: string; catalogNumber: string; uniqueIdentification: string; readonly conformityStandard?: string; rujukanSniIds: string[]; pempekTypes: ("BOILED" | "FRIED" | "GRILLED")[]; existingScope: string; proposedScope: string; additionalInformation: string; }
interface FormValues { type: "INITIAL" | "RECERTIFICATION" | "SCOPE_EXTENSION"; contactPerson: Contact; recipientSameAsApplicant: boolean; certificateRecipient?: Contact; productInformation: ProductInformation; manufacturingInformation: { factoryName: string; factoryAddress: string; responsiblePerson: string; responsiblePosition: string; contactPerson: string; contactAddress: string; }; requirementsAccepted: boolean; licenseAgreementAccepted: boolean; }
interface Evaluator { readonly name: string; readonly role: string; }
interface AuditReport { readonly productionProcess: string; readonly qualitySystem: string; readonly facilities: string; readonly supportingDocuments: string; readonly marketProductCondition: string; readonly conclusion: string; readonly hasNonconformity: boolean; readonly nonconformityDetails: string; }
interface Application { readonly id: string; readonly applicationNumber: string | null; readonly type: FormValues["type"]; readonly status: string; readonly applicantSnapshot: ApplicantSnapshot; readonly contactPerson: Contact | null; readonly certificateRecipient: Contact | null; readonly productInformation: FormValues["productInformation"] | null; readonly conformityStandards: readonly SniReference[]; readonly manufacturingInformation: FormValues["manufacturingInformation"] | null; readonly requirementsAccepted: boolean; readonly licenseAgreementAccepted: boolean; readonly reviewNotes: string | null; readonly feeDetails: { readonly reference: string; readonly amount: number; readonly dueDate: string; readonly description: string; } | null; readonly proposedEvaluators: readonly Evaluator[] | null; readonly assignedEvaluators: readonly Evaluator[] | null; readonly auditSchedule: { readonly startAt: string; readonly endAt: string; readonly location: string; readonly agenda: string; } | null; readonly auditReport: AuditReport | null; readonly correctiveActionNotes: string | null; readonly certificationQuestionnaire: { readonly submittedAt: string | null; readonly updatedAt: string } | null; readonly updatedAt: string; readonly business: { readonly name: string; }; readonly documents: readonly { readonly id: string; readonly documentType: string; readonly documentName: string; readonly originalFileName: string; readonly mimeType: string; }[]; }
interface Props { readonly isReviewer: boolean; readonly applicantSnapshot?: ApplicantSnapshot; readonly initialView?: "application" | "history"; }

const inputClass = "mt-1.5 w-full rounded-xl border border-slate-200 bg-white px-3.5 py-2.5 text-sm outline-none focus:border-[#0FA3B1] focus:ring-2 focus:ring-[#0FA3B1]/10";
const labels: Readonly<Record<string, string>> = { INITIAL: "Sertifikasi Awal", RECERTIFICATION: "Resertifikasi", SCOPE_EXTENSION: "Perluasan Ruang Lingkup", DRAFT: "Draft", SUBMITTED: "Permohonan Diajukan", RESUBMITTED: "Permohonan Diajukan Kembali", REVISION_REQUIRED: "Perlu Perbaikan", VERIFIED: "Lengkap dan Sesuai", INVOICED: "Menunggu Pembayaran", PAYMENT_SUBMITTED: "Pembayaran Diajukan", PAYMENT_VERIFIED: "Pembayaran Terverifikasi", AUDIT_SCHEDULED: "Menunggu Konfirmasi Jadwal", SCHEDULE_CONFIRMED: "Jadwal Dikonfirmasi", AUDIT_COMPLETED: "Audit Selesai", CORRECTIVE_ACTION_REQUIRED: "Perlu Tindakan Perbaikan", CORRECTIVE_ACTION_SUBMITTED: "Perbaikan Diajukan", CORRECTIVE_ACTION_VERIFIED: "Perbaikan Terverifikasi" };
const documentTypes = [{ value: "APPLICANT_IDENTITY", label: "Fotokopi identitas pemohon", required: true }, { value: "APPLICANT_TAX_ID", label: "Fotokopi NPWP Pemohon", required: true }, { value: "BUSINESS_LEGALITY", label: "Fotokopi akte pendirian/legalitas lokasi usaha", required: true }, { value: "QUALITY_GUIDE", label: "Panduan Mutu (HACCP/GMP dan SSOP)", required: true }, { value: "BUSINESS_CERTIFICATES", label: "Sertifikat NIB, MD/PIRT, Merek, Halal, SKP, sistem manajemen", required: true }, { value: "SNI_MARK_ILLUSTRATION", label: "Ilustrasi Tanda SNI pada kemasan", required: true }, { value: "APPLICATION_LETTER", label: "Surat Permohonan" }, { value: "BUSINESS_LICENSE", label: "Legalitas Usaha" }, { value: "PRODUCT_SPECIFICATION", label: "Spesifikasi Produk" }, { value: "QUALITY_DOCUMENT", label: "Dokumen Sistem Mutu" }, { value: "PRODUCTION_PROCESS", label: "Proses Produksi" }, { value: "OTHER", label: "Dokumen Lainnya" }, { value: "PAYMENT_PROOF", label: "Bukti Transfer" }, { value: "AUDIT_REPORT", label: "Laporan Audit" }, { value: "CORRECTIVE_ACTION_PROOF", label: "Bukti Tindakan Perbaikan" }] as const;

export function CertificationWorkspace({ isReviewer, applicantSnapshot, initialView = "history" }: Props) {
  const [applications, setApplications] = useState<Application[]>([]); const [selected, setSelected] = useState<Application | null>(null); const [mode, setMode] = useState<"list" | "form" | "questionnaire" | "review" | "workflow">(!isReviewer && initialView === "application" ? "form" : "list"); const [message, setMessage] = useState(""); const [busy, setBusy] = useState(false); const [reviewNotes, setReviewNotes] = useState(""); const [documentType, setDocumentType] = useState("APPLICANT_IDENTITY"); const [sniReferences, setSniReferences] = useState<SniReference[]>([]);
  const { register, reset, getValues, setValue, control, formState: { errors }, trigger } = useForm<FormValues>({ defaultValues: emptyForm });
  const sameRecipient = useWatch({ control, name: "recipientSameAsApplicant" });
  const applicationType = useWatch({ control, name: "type" }); const selectedSniIds = useWatch({ control, name: "productInformation.rujukanSniIds" }) ?? []; const additionalInformation = useWatch({ control, name: "productInformation.additionalInformation" }) ?? "";
  const pempekSelected = sniReferences.some((standard) => standard.nomor_sni === "SNI 7661:2019" && selectedSniIds.includes(standard.id));
  async function load() { const response = await fetch("/api/certification-applications"); const result = await response.json() as { data?: Application[]; }; setApplications(result.data ?? []); }
  useEffect(() => { void fetch("/api/certification-applications").then((response) => response.json()).then((result: { data?: Application[]; }) => setApplications(result.data ?? [])); void fetch("/api/rujukan-sni").then((response) => response.json()).then((result: { data?: SniReference[] }) => setSniReferences(result.data ?? [])); }, []);
  useEffect(() => { if (!pempekSelected) setValue("productInformation.pempekTypes", []); }, [pempekSelected, setValue]);
  function start(application?: Application) { setSelected(application ?? null); reset(application ? { type: application.type, contactPerson: application.contactPerson ?? emptyForm.contactPerson, recipientSameAsApplicant: !application.certificateRecipient, certificateRecipient: application.certificateRecipient ?? emptyForm.certificateRecipient, productInformation: { ...emptyForm.productInformation, ...application.productInformation, rujukanSniIds: application.conformityStandards.slice(0, 1).map((standard) => standard.id) }, manufacturingInformation: application.manufacturingInformation ?? emptyForm.manufacturingInformation, requirementsAccepted: application.requirementsAccepted, licenseAgreementAccepted: application.licenseAgreementAccepted } : emptyForm); setMessage(""); setMode("form"); }
  async function save(validate = false): Promise<string | null> { if (validate && !(await trigger())) { setMessage("Lengkapi seluruh informasi wajib sebelum melanjutkan."); return null; } setBusy(true); try { const values = getValues(); const payload = { ...values, certificateRecipient: values.recipientSameAsApplicant ? undefined : values.certificateRecipient }; const response = await fetch(selected ? `/api/certification-applications/${selected.id}` : "/api/certification-applications", { method: selected ? "PUT" : "POST", headers: { "content-type": "application/json" }, body: JSON.stringify(payload) }); const result = await response.json() as { success: boolean; message: string; data?: { id: string; }; }; setMessage(result.success ? "Detail informasi produk berhasil disimpan." : result.message); if (result.success && result.data) { const detailResponse = await fetch(`/api/certification-applications/${result.data.id}`); const detail = await detailResponse.json() as { data: Application; }; setSelected(detail.data); await load(); return result.data.id; } return null; } finally { setBusy(false); } }
  async function upload(file: File) { let id = selected?.id; if (!id) id = (await save()) ?? undefined; if (!id) return; setBusy(true); const form = new FormData(); form.set("file", file); form.set("documentType", documentType); form.set("documentName", file.name); const response = await fetch(`/api/certification-applications/${id}/documents`, { method: "POST", body: form }); const result = await response.json() as { success: boolean; message: string; }; setMessage(result.message); if (result.success) await refreshSelected(id); setBusy(false); }
  async function refreshSelected(id: string) { const response = await fetch(`/api/certification-applications/${id}`); const detail = await response.json() as { data: Application; }; setSelected(detail.data); }
  async function removeDocument(documentId: string) { if (!selected) return; setBusy(true); const response = await fetch(`/api/certification-applications/${selected.id}/documents/${documentId}`, { method: "DELETE" }); const result = await response.json() as { success: boolean; message: string; }; setMessage(result.message); if (result.success) await refreshSelected(selected.id); setBusy(false); }
  async function continueToQuestionnaire() { const id = await save(true); if (!id) return; const response = await fetch(`/api/certification-applications/${id}`); const result = await response.json() as { data?: Application }; if (result.data) setSelected(result.data); setMessage(""); setMode("questionnaire"); }
  async function review(decision: "VERIFIED" | "REVISION_REQUIRED") { if (!selected) return; if (decision === "REVISION_REQUIRED" && !reviewNotes.trim()) { setMessage("Catatan perbaikan wajib diisi sebelum permohonan dikembalikan."); return; } setBusy(true); setMessage(""); try { const response = await fetch(`/api/certification-applications/${selected.id}/review`, { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ decision, notes: reviewNotes.trim() }) }); const result = await response.json() as { success: boolean; message: string; }; setMessage(result.message); if (result.success) { await load(); setMode("list"); } } finally { setBusy(false); } }
  if (mode === "questionnaire" && selected) return <CertificationQuestionnaireWizard applicationId={selected.id} onBack={() => setMode("form")} onSubmitted={async (notice) => { setMessage(notice); await load(); setMode("list"); }}/>
  if (mode === "form") return <div className="space-y-6"><PageBack onClick={() => setMode("list")} title={selected ? "Perbaiki Permohonan Sertifikasi" : "Permohonan Sertifikasi Baru"} />{message && <Notice>{message}</Notice>}<form className="space-y-5" onSubmit={(event) => event.preventDefault()}>
    <Section title="Informasi Pemohon" description="Data berikut diambil otomatis dari profil usaha dan tidak perlu diinput ulang."><dl className="grid gap-4 md:grid-cols-2">{Object.entries({ "Nama Pemohon": applicantSnapshot?.applicantName, "Nama UPI sesuai legalitas": applicantSnapshot?.upiName, "Nomor Identitas": applicantSnapshot?.identityNumber, "Alamat UPI": applicantSnapshot?.address, "Telepon/Faks": applicantSnapshot?.phone, "Posisi Pemohon": applicantSnapshot?.position }).map(([label, value]) => <div key={label} className="rounded-xl bg-slate-50 p-4"><dt className="text-xs font-semibold uppercase text-slate-500">{label}</dt><dd className="mt-1 text-sm font-semibold text-slate-800">{value || "Belum tersedia di profil"}</dd></div>)}</dl></Section>
    <Section title="Personel Penghubung"><ContactFields prefix="contactPerson" register={register} errors={errors} /></Section>
    <Section title="Penerima Sertifikat Kesesuaian"><label className="flex gap-3 text-sm"><input type="checkbox" {...register("recipientSameAsApplicant")} />Penerima sertifikat sama dengan pemohon</label>{!sameRecipient && <div className="mt-5"><ContactFields prefix="certificateRecipient" register={register} errors={errors} /></div>}</Section>
    <Section title="Informasi Produk"><div className="grid gap-5 md:grid-cols-2"><Field label="Nama Produk *"><input {...register("productInformation.productName", { required: "Nama produk wajib diisi" })} placeholder="Contoh: Pempek Kapal Selam Merek ABC" className={inputClass} /></Field><Field label="Nomor Katalog"><input {...register("productInformation.catalogNumber")} placeholder="Contoh: PMK-001" className={inputClass} /></Field><Field label="Tipe atau Identifikasi Unik Lainnya"><input {...register("productInformation.uniqueIdentification")} placeholder="Contoh: Kemasan 500 gram, varian rebus" className={inputClass} /></Field><div className="md:col-span-2"><SniMultiSelect options={sniReferences} selectedIds={selectedSniIds} onChange={(ids) => setValue("productInformation.rujukanSniIds", ids, { shouldValidate: true, shouldDirty: true })} /></div>{pempekSelected && <fieldset className="md:col-span-2"><legend className="text-sm font-semibold text-slate-700">Jenis Produk Pempek *</legend><div className="mt-2 flex flex-wrap gap-4">{([['BOILED','Rebus'],['FRIED','Goreng'],['GRILLED','Panggang']] as const).map(([value, label]) => <label key={value} className="flex items-center gap-2 rounded-xl border px-4 py-3 text-sm"><input type="checkbox" value={value} {...register("productInformation.pempekTypes", { validate: (items) => !pempekSelected || items.length > 0 || "Pilih minimal satu jenis Pempek" })}/>{label}</label>)}</div></fieldset>}<fieldset className="md:col-span-2"><legend className="text-sm font-semibold text-slate-700">Jenis Pengajuan Sertifikasi *</legend><div className="mt-2 grid gap-3 md:grid-cols-3">{(["INITIAL", "RECERTIFICATION", "SCOPE_EXTENSION"] as const).map((value) => <label key={value} className="flex cursor-pointer gap-3 rounded-xl border p-4 text-sm font-semibold"><input type="radio" value={value} {...register("type", { required: true })}/>{labels[value]}</label>)}</div></fieldset>{applicationType === "SCOPE_EXTENSION" && <div className="grid gap-4 md:col-span-2 md:grid-cols-2"><Field label="Standar/Ruang Lingkup yang Sudah Dimiliki *"><textarea rows={3} {...register("productInformation.existingScope", { required: true })} className={inputClass}/></Field><Field label="Ruang Lingkup Baru yang Diajukan *"><textarea rows={3} {...register("productInformation.proposedScope", { required: true })} className={inputClass}/></Field></div>}<div className="md:col-span-2"><Field label="Keterangan Tambahan"><textarea rows={4} maxLength={1000} {...register("productInformation.additionalInformation", { maxLength: 1000 })} placeholder="Tuliskan informasi tambahan mengenai produk yang diajukan." className={inputClass}/><span className="mt-1 block text-right text-xs text-slate-500">{additionalInformation.length}/1.000 karakter</span></Field></div></div></Section>
    <Section title="Informasi Pembuatan Produk"><div className="grid gap-4 md:grid-cols-2"><Field label="Lokasi/Nama Pabrik"><input {...register("manufacturingInformation.factoryName", { required: true })} className={inputClass} /></Field><Field label="Alamat Pabrik"><input {...register("manufacturingInformation.factoryAddress", { required: true })} className={inputClass} /></Field><Field label="Nama Penanggung Jawab"><input {...register("manufacturingInformation.responsiblePerson", { required: true })} className={inputClass} /></Field><Field label="Jabatan"><input {...register("manufacturingInformation.responsiblePosition", { required: true })} className={inputClass} /></Field><Field label="Personel Penghubung"><input {...register("manufacturingInformation.contactPerson", { required: true })} className={inputClass} /></Field><Field label="Alamat yang Dapat Dihubungi"><input {...register("manufacturingInformation.contactAddress", { required: true })} className={inputClass} /></Field></div></Section>
    <Section title="Dokumen Persyaratan" description="Terlampir kami sertakan kelengkapan persyaratan berikut. Seluruh dokumen bertanda wajib harus dilengkapi."><ul className="mb-5 space-y-2">{documentTypes.filter((item) => "required" in item && item.required).map((item) => { const attached = selected?.documents.some((document) => document.documentType === item.value) ?? false; return <li key={item.value} className="flex items-center gap-2 text-sm"><span className={`flex h-5 w-5 items-center justify-center rounded border ${attached ? "border-[#2E9F6B] bg-[#2E9F6B] text-white" : "border-slate-300"}`}>{attached && <Check size={14}/>}</span>{item.label}</li>; })}</ul><div className="flex flex-wrap items-end gap-3"><Field label="Jenis Dokumen"><select value={documentType} onChange={(event) => setDocumentType(event.target.value)} className={inputClass}>{documentTypes.map((item) => <option key={item.value} value={item.value}>{item.label}</option>)}</select></Field><label className="inline-flex cursor-pointer items-center gap-2 rounded-xl border border-dashed border-[#0FA3B1] px-5 py-3 text-sm font-bold text-[#087E8B]"><FileUp size={18} /> Unggah PDF/JPG/PNG<input type="file" className="sr-only" accept=".pdf,.jpg,.jpeg,.png" onChange={(event) => { const file = event.target.files?.[0]; if (file) void upload(file); event.target.value = ""; }} /></label></div><ul className="mt-4 space-y-2">{selected?.documents.map((document) => <li key={document.id} className="flex items-center gap-3 rounded-lg bg-slate-50 px-4 py-3 text-sm"><span className="min-w-0 flex-1"><strong className="block truncate">{document.documentName}</strong><span className="text-xs text-slate-500">{documentTypes.find((item) => item.value === document.documentType)?.label}</span></span><a href={`/api/certification-applications/${selected.id}/documents/${document.id}`} className="rounded-lg p-2 text-[#087E8B]" aria-label={`Unduh ${document.documentName}`}><Download size={17} /></a><button type="button" disabled={busy} onClick={() => void removeDocument(document.id)} className="rounded-lg p-2 text-red-600" aria-label={`Hapus ${document.documentName}`}><Trash2 size={17} /></button></li>)}</ul></Section>
    <Section title="Pernyataan"><div className="space-y-3"><label className="flex gap-3 rounded-xl border p-4 text-sm"><input type="checkbox" {...register("requirementsAccepted", { required: true })} />Saya sanggup memenuhi seluruh persyaratan sertifikasi yang berlaku.</label><label className="flex gap-3 rounded-xl border p-4 text-sm"><input type="checkbox" {...register("licenseAgreementAccepted", { required: true })} />Saya menyetujui perjanjian lisensi sertifikasi.</label></div></Section>
    <div className="flex flex-wrap justify-end gap-3"><button type="button" disabled={busy} onClick={() => setMode("list")} className="inline-flex items-center gap-2 rounded-xl border border-slate-300 px-5 py-3 text-sm font-bold text-slate-700"><ArrowLeft size={17}/> Kembali</button><button type="button" disabled={busy} onClick={() => void save()} className="inline-flex items-center gap-2 rounded-xl border border-[#087E8B] px-5 py-3 text-sm font-bold text-[#087E8B]"><Save size={17} /> Simpan Draft</button><button type="button" disabled={busy} onClick={() => void continueToQuestionnaire()} className="inline-flex items-center gap-2 rounded-xl bg-[#2E9F6B] px-5 py-3 text-sm font-bold text-white">{busy ? <LoaderCircle className="animate-spin" size={17} /> : <Send size={17} />} Simpan dan Lanjutkan Mengisi Kuesioner</button></div>
  </form></div>;
  if (mode === "workflow" && selected) return <div className="space-y-6"><PageBack onClick={() => setMode("list")} title="Proses Sertifikasi" /><ApplicationSummary application={selected} /><WorkflowPanel application={selected} isReviewer={isReviewer} onUpdated={async (notice) => { setMessage(notice); await load(); setMode("list"); }} />{message && <Notice>{message}</Notice>}</div>;
  if (mode === "review" && selected) return <div className="space-y-6 pb-10"><ReviewHeader application={selected} onBack={() => setMode("list")} /><ApplicationSummary application={selected} />{selected.certificationQuestionnaire?.submittedAt ? <div className="grid items-start gap-6 xl:grid-cols-[minmax(0,1fr)_360px]"><main className="min-w-0"><CertificationQuestionnaireDetail applicationId={selected.id}/></main><aside className="space-y-4 xl:sticky xl:top-6"><ReviewDecisionPanel notes={reviewNotes} onNotesChange={setReviewNotes} busy={busy} message={message} onDecision={review} /></aside></div> : <div className="rounded-2xl border border-amber-200 bg-amber-50 p-6"><div className="flex gap-3"><AlertTriangle className="mt-0.5 shrink-0 text-amber-600" size={22}/><div><h2 className="font-bold text-amber-900">Kuesioner belum tersedia</h2><p className="mt-1 text-sm leading-6 text-amber-800">Kuesioner DK 7.3 belum dikirim oleh pemohon. Keputusan kaji ulang baru dapat diberikan setelah kuesioner selesai diajukan.</p></div></div></div>}</div>;
  return <div className="space-y-6"><div className="flex flex-wrap items-start justify-between gap-4"><div><h1 className="text-3xl font-bold text-[#073B4C]">Permohonan Sertifikasi</h1><p className="mt-2 text-sm text-slate-500">{isReviewer ? "Periksa kelengkapan dan kesesuaian permohonan yang masuk." : "Ajukan dan pantau proses sertifikasi produk Anda."}</p></div>{!isReviewer && <button onClick={() => start()} className="inline-flex items-center gap-2 rounded-xl bg-[#073B4C] px-5 py-3 text-sm font-bold text-white"><Plus size={18} /> Permohonan Baru</button>}</div>{message && <Notice>{message}</Notice>}<div className="overflow-hidden rounded-2xl border bg-white shadow-sm"><div className="overflow-x-auto"><table className="w-full text-left text-sm"><thead className="bg-slate-50 text-xs uppercase text-slate-500"><tr><th className="px-5 py-4">Nomor</th><th className="px-5 py-4">Pemohon</th><th className="px-5 py-4">Jenis</th><th className="px-5 py-4">Status</th><th className="px-5 py-4">Tindakan</th></tr></thead><tbody className="divide-y">{applications.map((application) => <tr key={application.id}><td className="px-5 py-4 font-semibold">{application.applicationNumber ?? "Draft"}</td><td className="px-5 py-4">{application.business.name}</td><td className="px-5 py-4">{labels[application.type]}</td><td className="px-5 py-4"><span className="rounded-full bg-cyan-50 px-3 py-1 text-xs font-bold text-[#087E8B]">{labels[application.status]}</span>{application.reviewNotes && <p className="mt-2 max-w-xs text-xs text-red-600">{application.reviewNotes}</p>}</td><td className="px-5 py-4">{isReviewer && ["SUBMITTED", "RESUBMITTED"].includes(application.status) ? <button onClick={() => { setSelected(application); setReviewNotes(""); setMode("review"); }} className="font-bold text-[#087E8B]">Kaji ulang</button> : ["DRAFT", "REVISION_REQUIRED"].includes(application.status) ? <button onClick={() => start(application)} className="font-bold text-[#087E8B]">Lanjutkan</button> : <button onClick={() => { setSelected(application); setMessage(""); setMode("workflow"); }} className="font-bold text-[#087E8B]">{["AUDIT_COMPLETED","CORRECTIVE_ACTION_VERIFIED"].includes(application.status) ? "Lihat detail" : "Proses"}</button>}</td></tr>)}</tbody></table>{applications.length === 0 && <div className="p-12 text-center text-sm text-slate-500"><ClipboardCheck className="mx-auto mb-3 text-slate-300" />Belum ada permohonan sertifikasi.</div>}</div></div></div>;
}

const emptyForm: FormValues = { type: "INITIAL", contactPerson: { name: "", position: "", phone: "", email: "" }, recipientSameAsApplicant: true, certificateRecipient: { name: "", position: "", phone: "", email: "" }, productInformation: { productName: "", catalogNumber: "", uniqueIdentification: "", rujukanSniIds: [], pempekTypes: [], existingScope: "", proposedScope: "", additionalInformation: "" }, manufacturingInformation: { factoryName: "", factoryAddress: "", responsiblePerson: "", responsiblePosition: "", contactPerson: "", contactAddress: "" }, requirementsAccepted: false, licenseAgreementAccepted: false };
function SniMultiSelect({ options, selectedIds, onChange }: { readonly options: readonly SniReference[]; readonly selectedIds: readonly string[]; readonly onChange: (ids: string[]) => void }) {
  const [query, setQuery] = useState(""); const [open, setOpen] = useState(false); const selected = options.find((option) => option.id === selectedIds[0]); const available = options.filter((option) => `${option.judul_standar} ${option.nomor_sni}`.toLocaleLowerCase("id-ID").includes(query.toLocaleLowerCase("id-ID")));
  return <div><label className="text-sm font-semibold text-slate-700" htmlFor="sni-search">Standar Kesesuaian *</label><div className="relative"><div className="mt-1.5 flex items-center rounded-xl border border-slate-200 bg-white focus-within:border-[#0FA3B1] focus-within:ring-2 focus-within:ring-[#0FA3B1]/10"><input id="sni-search" value={query} onFocus={() => setOpen(true)} onChange={(event) => { setQuery(event.target.value); setOpen(true); }} placeholder="Cari judul standar atau nomor SNI..." className="w-full bg-transparent px-3.5 py-2.5 text-sm outline-none"/><button type="button" onClick={() => setOpen((value) => !value)} className="p-3 text-slate-500" aria-label="Buka pilihan standar"><ChevronDown size={18}/></button></div>{open && <div className="absolute z-20 mt-1 max-h-64 w-full overflow-y-auto rounded-xl border bg-white p-1 shadow-xl">{available.map((option) => <button type="button" key={option.id} onClick={() => { onChange([option.id]); setQuery(""); setOpen(false); }} aria-pressed={option.id === selected?.id} className="block w-full rounded-lg px-3 py-2 text-left text-sm hover:bg-cyan-50 aria-pressed:bg-cyan-50"><span className="font-semibold">{option.judul_standar}</span> — {option.nomor_sni}</button>)}{available.length === 0 && <p className="px-3 py-4 text-center text-sm text-slate-500">Standar tidak ditemukan.</p>}</div>}</div>{selected && <div className="mt-3"><span className="inline-flex items-center gap-2 rounded-full bg-cyan-50 px-3 py-1.5 text-sm font-semibold text-[#073B4C]">{selected.judul_standar} — {selected.nomor_sni}<button type="button" onClick={() => onChange([])} aria-label={`Hapus ${selected.judul_standar}`}><X size={15}/></button></span></div>}</div>;
}
function Section({ title, description, children }: { readonly title: string; readonly description?: string; readonly children: React.ReactNode; }) { return <section className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm sm:p-7"><h2 className="text-lg font-bold text-[#073B4C]">{title}</h2>{description && <p className="mt-1 text-sm text-slate-500">{description}</p>}<div className="mt-5">{children}</div></section>; }
function Field({ label, children }: { readonly label: string; readonly children: React.ReactNode; }) { return <label className="text-sm font-semibold text-slate-700">{label}{children}</label>; }
function ContactFields({ prefix, register }: { readonly prefix: "contactPerson" | "certificateRecipient"; readonly register: ReturnType<typeof useForm<FormValues>>["register"]; readonly errors: ReturnType<typeof useForm<FormValues>>["formState"]["errors"]; }) { return <div className="grid gap-4 md:grid-cols-2"><Field label="Nama"><input {...register(`${prefix}.name`, { required: true })} className={inputClass} /></Field><Field label="Jabatan"><input {...register(`${prefix}.position`, { required: true })} className={inputClass} /></Field><Field label="Nomor Telepon"><input {...register(`${prefix}.phone`, { required: true })} className={inputClass} /></Field><Field label="Email"><input type="email" {...register(`${prefix}.email`, { required: true })} className={inputClass} /></Field></div>; }
function PageBack({ onClick, title }: { readonly onClick: () => void; readonly title: string; }) { return <div className="flex items-center gap-4"><button onClick={onClick} aria-label="Kembali" className="rounded-xl border bg-white p-2.5"><ArrowLeft size={19} /></button><h1 className="text-2xl font-bold text-[#073B4C]">{title}</h1></div>; }
function Notice({ children }: { readonly children: React.ReactNode; }) { return <div role="status" className="rounded-xl border border-cyan-200 bg-cyan-50 p-4 text-sm text-[#073B4C]">{children}</div>; }
function ReviewHeader({ application, onBack }: { readonly application: Application; readonly onBack: () => void }) { return <header className="overflow-hidden rounded-3xl bg-[#073B4C] text-white shadow-[0_20px_55px_rgba(7,59,76,.18)]"><div className="relative p-5 sm:p-7"><div className="absolute -right-12 -top-16 h-52 w-52 rounded-full bg-[#0FA3B1]/20 blur-2xl"/><div className="relative flex flex-col gap-5 sm:flex-row sm:items-start sm:justify-between"><div className="flex gap-4"><button onClick={onBack} aria-label="Kembali ke daftar permohonan" className="flex h-11 w-11 shrink-0 items-center justify-center rounded-xl border border-white/15 bg-white/10 transition hover:bg-white/20 focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-white"><ArrowLeft size={19}/></button><div><p className="text-xs font-bold uppercase tracking-[.18em] text-[#61C0BF]">Kaji Ulang Permohonan</p><h1 className="mt-2 text-2xl font-bold sm:text-3xl">{application.applicationNumber ?? "Permohonan Sertifikasi"}</h1><p className="mt-2 text-sm text-white/65">Periksa data permohonan, dokumen, dan kuesioner DK 7.3 sebelum menetapkan keputusan.</p></div></div><span className="inline-flex w-fit items-center gap-2 rounded-full border border-emerald-300/25 bg-emerald-400/15 px-3.5 py-2 text-xs font-bold text-emerald-100"><ShieldCheck size={16}/> Siap dikaji ulang</span></div></div></header>; }
function ReviewDecisionPanel({ notes, onNotesChange, busy, message, onDecision }: { readonly notes: string; readonly onNotesChange: (value: string) => void; readonly busy: boolean; readonly message: string; readonly onDecision: (decision: "VERIFIED" | "REVISION_REQUIRED") => Promise<void> }) { return <section aria-labelledby="review-decision-title" className="overflow-hidden rounded-2xl border border-slate-200 bg-white shadow-[0_12px_35px_rgba(7,59,76,.09)]"><div className="border-b border-slate-100 bg-slate-50 px-5 py-4"><div className="flex items-center gap-3"><span className="flex h-10 w-10 items-center justify-center rounded-xl bg-[#073B4C] text-white"><ClipboardCheck size={19}/></span><div><h2 id="review-decision-title" className="font-bold text-[#073B4C]">Keputusan Kaji Ulang</h2><p className="mt-0.5 text-xs text-slate-500">Pastikan seluruh bagian telah diperiksa.</p></div></div></div><div className="p-5"><label htmlFor="review-notes" className="text-sm font-semibold text-slate-700">Catatan petugas <span className="font-normal text-slate-400">(wajib jika dikembalikan)</span></label><textarea id="review-notes" rows={6} maxLength={3000} value={notes} onChange={(event) => onNotesChange(event.target.value)} className={`${inputClass} resize-y`} placeholder="Tuliskan temuan, bagian yang perlu diperbaiki, atau catatan hasil pemeriksaan."/><div className="mt-1 flex justify-between text-xs text-slate-400"><span>Catatan diterima oleh pemohon.</span><span>{notes.length}/3.000</span></div>{message && <div role="status" className="mt-4 rounded-xl border border-amber-200 bg-amber-50 p-3 text-sm leading-5 text-amber-800">{message}</div>}<div className="mt-5 space-y-3"><button type="button" disabled={busy} onClick={() => void onDecision("VERIFIED")} className="inline-flex w-full items-center justify-center gap-2 rounded-xl bg-[#2E9F6B] px-4 py-3 text-sm font-bold text-white shadow-sm transition hover:bg-[#27875b] focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-[#2E9F6B] focus-visible:ring-offset-2 disabled:cursor-not-allowed disabled:opacity-50">{busy ? <LoaderCircle className="animate-spin" size={18}/> : <CheckCircle2 size={18}/>} Nyatakan Lengkap dan Sesuai</button><button type="button" disabled={busy} onClick={() => void onDecision("REVISION_REQUIRED")} className="inline-flex w-full items-center justify-center gap-2 rounded-xl border border-red-200 bg-red-50 px-4 py-3 text-sm font-bold text-[#C92C38] transition hover:bg-red-100 focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-[#E63946] focus-visible:ring-offset-2 disabled:cursor-not-allowed disabled:opacity-50"><XCircle size={18}/> Kembalikan untuk Perbaikan</button></div><p className="mt-4 text-center text-xs leading-5 text-slate-500">Keputusan dicatat pada riwayat permohonan dan tidak dapat dibatalkan dari halaman ini.</p></div></section>; }
function ApplicationSummary({ application }: { readonly application: Application; }) { const mainDocuments = application.documents.filter((document) => documentTypes.some((item) => "required" in item && item.required && item.value === document.documentType)); return <div className="space-y-5"><Section title="Ringkasan Permohonan"><dl className="grid gap-4 md:grid-cols-2"><Summary label="Nomor Permohonan" value={application.applicationNumber} /><Summary label="Jenis Permohonan" value={labels[application.type]} /><Summary label="Pemohon / UPI" value={`${application.applicantSnapshot.applicantName} / ${application.business.name}`} /><Summary label="Personel Penghubung" value={application.contactPerson ? `${application.contactPerson.name} · ${application.contactPerson.phone}` : null} /><Summary label="Produk" value={`${application.productInformation?.productName ?? "-"} · ${application.productInformation?.uniqueIdentification ?? "-"}`} /><Summary label="Standar Kesesuaian" value={application.productInformation?.conformityStandard} /><Summary label="Pabrik" value={`${application.manufacturingInformation?.factoryName ?? "-"} · ${application.manufacturingInformation?.factoryAddress ?? "-"}`} /><Summary label="Penanggung Jawab Pabrik" value={`${application.manufacturingInformation?.responsiblePerson ?? "-"} · ${application.manufacturingInformation?.responsiblePosition ?? "-"}`} /></dl></Section><Section title={`Enam Dokumen Utama (${mainDocuments.length}/6)`}><div className="grid gap-3 sm:grid-cols-2">{mainDocuments.map((document) => <article key={document.id} className="overflow-hidden rounded-xl border bg-slate-50">{document.mimeType.startsWith("image/") && <div className="relative aspect-[16/9] bg-slate-100"><Image src={`/api/certification-applications/${application.id}/documents/${document.id}?preview=1`} alt={`Pratinjau ${document.documentName}`} fill unoptimized className="object-contain"/></div>}<div className="flex items-center gap-3 p-4"><span className="min-w-0 flex-1 text-sm font-semibold"><span className="block truncate">{document.documentName}</span><small className="mt-1 block font-normal text-slate-500">{documentTypes.find((item) => item.value === document.documentType)?.label}</small></span><a href={`/api/certification-applications/${application.id}/documents/${document.id}`} className="inline-flex shrink-0 items-center gap-2 rounded-lg border border-[#087E8B]/20 bg-white px-3 py-2 text-xs font-bold text-[#087E8B]"><Download size={16} /> Unduh</a></div></article>)}</div></Section></div>; }
function Summary({ label, value }: { readonly label: string; readonly value: string | null | undefined; }) { return <div><dt className="text-xs text-slate-500">{label}</dt><dd className="mt-1 font-semibold">{value || "-"}</dd></div>; }

interface WorkflowValues { reference: string; amount: number; dueDate: string; description: string; evaluatorName: string; evaluatorRole: string; startAt: string; endAt: string; location: string; agenda: string; productionProcess: string; qualitySystem: string; facilities: string; supportingDocuments: string; marketProductCondition: string; conclusion: string; hasNonconformity: boolean; nonconformityDetails: string; notes: string; accepted: boolean }
const workflowTitles: Readonly<Record<string, string>> = { ISSUE_INVOICE: "Rincian Biaya dan Usulan Evaluator", SUBMIT_PAYMENT: "Pembayaran Sertifikasi", VERIFY_PAYMENT: "Verifikasi Pembayaran dan Penetapan Evaluator", SCHEDULE_AUDIT: "Jadwal Pelaksanaan Audit", CONFIRM_SCHEDULE: "Konfirmasi Jadwal Audit", RECORD_AUDIT: "Laporan Hasil Audit", SUBMIT_CORRECTIVE_ACTION: "Tindakan Perbaikan", VERIFY_CORRECTIVE_ACTION: "Verifikasi Tindakan Perbaikan" };

function WorkflowPanel({ application, isReviewer, onUpdated }: { readonly application: Application; readonly isReviewer: boolean; readonly onUpdated: (notice: string) => Promise<void> }) {
  const { register, handleSubmit, formState: { isSubmitting } } = useForm<WorkflowValues>({ defaultValues: { accepted: true, hasNonconformity: false } });
  const [proof, setProof] = useState<File | null>(null); const [notice, setNotice] = useState("");
  const reviewerActions: Readonly<Record<string, string>> = { VERIFIED: "ISSUE_INVOICE", PAYMENT_SUBMITTED: "VERIFY_PAYMENT", PAYMENT_VERIFIED: "SCHEDULE_AUDIT", SCHEDULE_CONFIRMED: "RECORD_AUDIT", CORRECTIVE_ACTION_SUBMITTED: "VERIFY_CORRECTIVE_ACTION" };
  const applicantActions: Readonly<Record<string, string>> = { INVOICED: "SUBMIT_PAYMENT", AUDIT_SCHEDULED: "CONFIRM_SCHEDULE", CORRECTIVE_ACTION_REQUIRED: "SUBMIT_CORRECTIVE_ACTION" };
  const action = (isReviewer ? reviewerActions : applicantActions)[application.status];
  async function submit(values: WorkflowValues) {
    if (["SUBMIT_PAYMENT", "SUBMIT_CORRECTIVE_ACTION"].includes(action) && !proof) { setNotice("Pilih berkas bukti terlebih dahulu."); return; }
    if (proof) { const form = new FormData(); form.set("file", proof); form.set("documentType", action === "SUBMIT_PAYMENT" ? "PAYMENT_PROOF" : "CORRECTIVE_ACTION_PROOF"); form.set("documentName", proof.name); const response = await fetch(`/api/certification-applications/${application.id}/documents`, { method: "POST", body: form }); const result = await response.json() as { success: boolean; message: string }; if (!result.success) { setNotice(result.message); return; } }
    const payload: Readonly<Record<string, unknown>> = action === "ISSUE_INVOICE" ? { action, feeDetails: { reference: values.reference, amount: Number(values.amount), dueDate: new Date(values.dueDate).toISOString(), description: values.description }, proposedEvaluators: [{ name: values.evaluatorName, role: values.evaluatorRole }] } : action === "VERIFY_PAYMENT" ? { action, assignedEvaluators: [{ name: values.evaluatorName, role: values.evaluatorRole }], notes: values.notes } : action === "SCHEDULE_AUDIT" ? { action, auditSchedule: { startAt: new Date(values.startAt).toISOString(), endAt: new Date(values.endAt).toISOString(), location: values.location, agenda: values.agenda } } : action === "RECORD_AUDIT" ? { action, auditReport: { productionProcess: values.productionProcess, qualitySystem: values.qualitySystem, facilities: values.facilities, supportingDocuments: values.supportingDocuments, marketProductCondition: values.marketProductCondition, conclusion: values.conclusion, hasNonconformity: values.hasNonconformity, nonconformityDetails: values.nonconformityDetails } } : action === "SUBMIT_CORRECTIVE_ACTION" ? { action, notes: values.notes } : action === "VERIFY_CORRECTIVE_ACTION" ? { action, accepted: values.accepted, notes: values.notes } : { action };
    const response = await fetch(`/api/certification-applications/${application.id}/workflow`, { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify(payload) }); const result = await response.json() as { success: boolean; message: string }; if (result.success) await onUpdated(result.message); else setNotice(result.message);
  }
  if (!action) return <Section title="Informasi Proses"><p className="text-sm text-slate-600">Tidak ada tindakan yang perlu dilakukan pada tahap ini.</p></Section>;
  return <Section title={workflowTitles[action]}><ProcessInformation application={application}/><form onSubmit={handleSubmit(submit)} className="mt-5 space-y-4">
    {action === "ISSUE_INVOICE" && <div className="grid gap-4 md:grid-cols-2"><Input register={register} name="reference" label="Nomor Tagihan"/><Input register={register} name="amount" label="Jumlah Biaya (Rp)" type="number"/><Input register={register} name="dueDate" label="Batas Pembayaran" type="datetime-local"/><Input register={register} name="description" label="Uraian Biaya"/></div>}
    {["ISSUE_INVOICE", "VERIFY_PAYMENT"].includes(action) && <div className="grid gap-4 md:grid-cols-2"><Input register={register} name="evaluatorName" label="Nama Evaluator"/><Input register={register} name="evaluatorRole" label="Peran Evaluator"/></div>}
    {action === "SCHEDULE_AUDIT" && <div className="grid gap-4 md:grid-cols-2"><Input register={register} name="startAt" label="Mulai Audit" type="datetime-local"/><Input register={register} name="endAt" label="Selesai Audit" type="datetime-local"/><Input register={register} name="location" label="Lokasi"/><Input register={register} name="agenda" label="Agenda"/></div>}
    {action === "RECORD_AUDIT" && <div className="grid gap-4 md:grid-cols-2">{([['productionProcess','Proses Produksi'],['qualitySystem','Penerapan Sistem Mutu'],['facilities','Fasilitas Usaha'],['supportingDocuments','Dokumen Pendukung'],['marketProductCondition','Kondisi Produk di Pasar'],['conclusion','Kesimpulan Audit'],['nonconformityDetails','Rincian Ketidaksesuaian']] as const).map(([name, label]) => <Field key={name} label={label}><textarea rows={3} className={inputClass} {...register(name, { required: !["marketProductCondition", "nonconformityDetails"].includes(name) })}/></Field>)}<label className="flex gap-3 text-sm font-semibold"><input type="checkbox" {...register("hasNonconformity")}/>Ditemukan ketidaksesuaian</label></div>}
    {["SUBMIT_PAYMENT", "SUBMIT_CORRECTIVE_ACTION"].includes(action) && <Field label={action === "SUBMIT_PAYMENT" ? "Bukti Transfer" : "Bukti Tindakan Perbaikan"}><input type="file" accept=".pdf,.jpg,.jpeg,.png" className={inputClass} onChange={(event) => setProof(event.target.files?.[0] ?? null)}/></Field>}
    {["VERIFY_PAYMENT", "SUBMIT_CORRECTIVE_ACTION", "VERIFY_CORRECTIVE_ACTION"].includes(action) && <Field label="Catatan"><textarea rows={4} className={inputClass} {...register("notes", { required: action !== "VERIFY_PAYMENT" })}/></Field>}{action === "VERIFY_CORRECTIVE_ACTION" && <label className="flex gap-3 text-sm font-semibold"><input type="checkbox" {...register("accepted")}/>Tindakan perbaikan telah memenuhi ketentuan</label>}{notice && <Notice>{notice}</Notice>}<button disabled={isSubmitting} className="rounded-xl bg-[#087E8B] px-5 py-3 text-sm font-bold text-white">{isSubmitting ? "Menyimpan..." : "Simpan dan Lanjutkan"}</button>
  </form></Section>;
}
function Input({ register, name, label, type = "text" }: { readonly register: ReturnType<typeof useForm<WorkflowValues>>["register"]; readonly name: keyof WorkflowValues; readonly label: string; readonly type?: string }) { return <Field label={label}><input type={type} className={inputClass} {...register(name, { required: true, valueAsNumber: name === "amount" })}/></Field>; }
function ProcessInformation({ application }: { readonly application: Application }) { return <dl className="grid gap-3 rounded-xl bg-slate-50 p-4 text-sm md:grid-cols-2">{application.feeDetails && <><Summary label="Nomor Tagihan" value={application.feeDetails.reference}/><Summary label="Biaya Sertifikasi" value={new Intl.NumberFormat("id-ID", { style: "currency", currency: "IDR" }).format(application.feeDetails.amount)}/><Summary label="Batas Pembayaran" value={new Date(application.feeDetails.dueDate).toLocaleString("id-ID")}/></>}{application.auditSchedule && <><Summary label="Waktu Audit" value={`${new Date(application.auditSchedule.startAt).toLocaleString("id-ID")} - ${new Date(application.auditSchedule.endAt).toLocaleString("id-ID")}`}/><Summary label="Lokasi Audit" value={application.auditSchedule.location}/><Summary label="Agenda Audit" value={application.auditSchedule.agenda}/></>}{application.assignedEvaluators?.map((item) => <Summary key={`${item.name}-${item.role}`} label="Tim Evaluator" value={`${item.name} · ${item.role}`}/>)}</dl>; }
