"use client";

import { useEffect, useState } from "react";
import { ArrowLeft, ArrowRight, LoaderCircle, Save, Send } from "lucide-react";
import { useForm } from "react-hook-form";

interface QualityAnswer { answer: "YES" | "NO" | null; notes: string; evidence: string }
interface Row { [key: string]: string }
interface QuestionnaireValues {
  applicantInformation: Row; productInformation: Row; productionInformation: Row; businessLegality: Row;
  humanResources: Row; certificationsAndProducts: Row; marketingChannels: Row;
  qualitySystemAnswers: QualityAnswer[]; sniEvaluation: Row; otherNotes: string;
  declarationAccepted: boolean; signatoryName: string; signatoryPosition: string; approvalDate: string; electronicSignatureAccepted: boolean;
}
interface Props { readonly applicationId: string; readonly onBack: () => void; readonly onSubmitted: (message: string) => Promise<void> }

const inputClass = "mt-1.5 w-full rounded-xl border border-slate-200 bg-white px-3.5 py-2.5 text-sm outline-none focus:border-[#0FA3B1] focus:ring-2 focus:ring-[#0FA3B1]/10";
const steps = ["Informasi Pemohon", "Informasi Produk", "Proses Produksi", "Legalitas UPI", "Sumber Daya Manusia", "Sertifikasi dan Produk", "Jalur Pemasaran", "Kuesioner Sistem Mutu", "Evaluasi Penerapan SNI", "Pernyataan dan Pengesahan"] as const;
export const qualitySystemQuestions = [
  "Apakah UPI memiliki panduan mutu atau dokumen sejenis?", "Apakah panduan mutu tersebut ditinjau secara berkala?", "Apakah terdapat aturan untuk mengontrol proses produksi?", "Apakah tersedia dokumen kontrol dan lembar pemeriksaan proses produksi?", "Apakah terdapat metode penyimpanan, revisi, persetujuan, identifikasi, dan distribusi dokumen?", "Apakah dokumen dipelihara?", "Apakah UPI memiliki kebijakan mutu?", "Apakah tersedia struktur organisasi dan uraian tugas yang jelas?", "Apakah terdapat petugas yang bertanggung jawab atas Quality Assurance?", "Apakah pernah dilakukan sosialisasi pencapaian kualitas melalui quality meeting?", "Apakah ada pertemuan untuk membahas peningkatan sistem mutu?", "Apakah tersedia pelatihan aspek mutu yang diterapkan secara sistematis?", "Apakah rekaman atau arsip pelatihan disimpan?", "Apakah operator diklasifikasikan berdasarkan keterampilan?", "Apakah tersedia buku riwayat pemeliharaan peralatan?", "Apakah terdapat aturan peninjauan atau persetujuan model baru?", "Apakah terdapat prosedur pemenuhan permintaan spesifikasi dan penanggung jawabnya?", "Apakah tersedia tenaga ahli pengembangan produk yang berpengalaman dan bersertifikat?", "Apakah peralatan, metode kerja, kondisi proses, dan alat ukur ditentukan secara jelas?", "Apakah produk pertama dan produk terakhir diperiksa dan dicatat?", "Apakah produk dikendalikan agar mudah ditelusuri?", "Apakah penanganan, penyimpanan, pengemasan, dan pengiriman dilakukan sesuai persyaratan?", "Apakah semua alat ukur dikontrol melalui buku kendali?", "Apakah UPI melaksanakan audit mutu internal?", "Apakah tindakan perbaikan dilakukan atas temuan audit internal?", "Apakah produk cacat dipisahkan dari produk yang baik?", "Apakah terdapat metode tindakan perbaikan dan tindakan pencegahan?",
] as const;
const questions = qualitySystemQuestions;

const defaultValues: QuestionnaireValues = {
  applicantInformation: {}, productInformation: {}, productionInformation: {}, businessLegality: {}, humanResources: {}, certificationsAndProducts: {}, marketingChannels: {},
  qualitySystemAnswers: qualitySystemQuestions.map(() => ({ answer: null, notes: "", evidence: "" })), sniEvaluation: {}, otherNotes: "", declarationAccepted: false, signatoryName: "", signatoryPosition: "", approvalDate: "", electronicSignatureAccepted: false,
};

export function CertificationQuestionnaireWizard({ applicationId, onBack, onSubmitted }: Props) {
  const [step, setStep] = useState(0); const [notice, setNotice] = useState(""); const [busy, setBusy] = useState(false);
  const { register, reset, getValues } = useForm<QuestionnaireValues>({ defaultValues });
  useEffect(() => { void fetch(`/api/certification-applications/${applicationId}/questionnaire`).then((response) => response.json()).then((result: { data?: Partial<QuestionnaireValues> }) => { if (result.data) reset({ ...defaultValues, ...result.data, qualitySystemAnswers: result.data.qualitySystemAnswers ?? defaultValues.qualitySystemAnswers }); }); }, [applicationId, reset]);
  async function save(submit = false) { setBusy(true); setNotice(""); try { const response = await fetch(`/api/certification-applications/${applicationId}/questionnaire`, { method: "PUT", headers: { "content-type": "application/json" }, body: JSON.stringify({ submit, data: getValues() }) }); const result = await response.json() as { success: boolean; message: string }; setNotice(result.message); if (result.success && submit) await onSubmitted(result.message); } finally { setBusy(false); } }
  return <div className="space-y-6">
    <div className="flex items-center gap-4"><button type="button" onClick={onBack} aria-label="Kembali" className="rounded-xl border bg-white p-2.5"><ArrowLeft size={19}/></button><div><h1 className="text-2xl font-bold text-[#073B4C]">DK 7.3 — Kuesioner Lampiran Aplikasi</h1><p className="mt-1 text-sm text-slate-500">Lengkapi data secara benar. Informasi dapat diaudit dan diverifikasi oleh LSPro-HP.</p></div></div>
    <ol className="grid grid-cols-2 gap-2 lg:grid-cols-5">{steps.map((label, index) => <li key={label}><button type="button" onClick={() => setStep(index)} className={`h-full w-full rounded-xl border p-3 text-left text-xs font-semibold ${step === index ? "border-[#087E8B] bg-cyan-50 text-[#073B4C]" : "bg-white text-slate-500"}`}><span className="mr-2 inline-flex h-6 w-6 items-center justify-center rounded-full bg-[#073B4C] text-white">{index + 1}</span>{label}</button></li>)}</ol>
    <section className="rounded-2xl border bg-white p-5 shadow-sm sm:p-7"><h2 className="text-lg font-bold text-[#073B4C]">Langkah {step + 1} — {steps[step]}</h2><div className="mt-5">{renderStep(step, register)}</div></section>
    {notice && <div role="status" className="rounded-xl border border-cyan-200 bg-cyan-50 p-4 text-sm text-[#073B4C]">{notice}</div>}
    <div className="flex flex-wrap justify-between gap-3"><button type="button" disabled={step === 0} onClick={() => setStep((value) => value - 1)} className="inline-flex items-center gap-2 rounded-xl border px-5 py-3 text-sm font-bold"><ArrowLeft size={17}/> Sebelumnya</button><div className="flex flex-wrap gap-3"><button type="button" disabled={busy} onClick={() => void save()} className="inline-flex items-center gap-2 rounded-xl border border-[#087E8B] px-5 py-3 text-sm font-bold text-[#087E8B]"><Save size={17}/> Simpan Draft</button>{step < steps.length - 1 ? <button type="button" onClick={() => setStep((value) => value + 1)} className="inline-flex items-center gap-2 rounded-xl bg-[#073B4C] px-5 py-3 text-sm font-bold text-white">Selanjutnya <ArrowRight size={17}/></button> : <button type="button" disabled={busy} onClick={() => void save(true)} className="inline-flex items-center gap-2 rounded-xl bg-[#2E9F6B] px-5 py-3 text-sm font-bold text-white">{busy ? <LoaderCircle className="animate-spin" size={17}/> : <Send size={17}/>} Kirim Permohonan dan Kuesioner</button>}</div></div>
  </div>;
}

type Register = ReturnType<typeof useForm<QuestionnaireValues>>["register"];
function renderStep(step: number, register: Register) {
  if (step === 0) return <Grid>{fields("applicantInformation", register, [["upiName","Nama UPI"],["officeAddress","Alamat kantor"],["phone","Nomor telepon"],["email","E-mail"],["nib","Nomor NIB"],["brandCertificateNumber","Nomor sertifikat merek"],["yearEstablished","Tahun pendirian"],["operationalYear","Tahun mulai beroperasi"],["contactPerson","Personel penghubung dan nomor HP"]])}</Grid>;
  if (step === 1) return <Grid>{fields("productInformation", register, [["brand","Merek produk"],["productType","Jenis produk"],["netWeight","Berat bersih dan satuan"],["shelfLife","Masa simpan"],["productionDateFormat","Format tanggal produksi"],["expiryDateFormat","Format tanggal kedaluwarsa"],["sni","SNI yang digunakan"],["labelInformation","Label dan informasi pada label"],["packagingType","Jenis, bahan, dan bentuk kemasan"],["productionCapacity","Kapasitas produksi per hari"],["averageProduction","Produksi rata-rata per hari"],["iceRequirement","Kebutuhan dan asal es"],["productPhotos","Foto kemasan depan, belakang, dan samping (nama/lokasi berkas)"]], true)}</Grid>;
  if (step === 2) return <Grid>{fields("productionInformation", register, [["sameProductionLocation","Lokasi produksi sama dengan alamat pemohon (Ya/Tidak)"],["facility","Nama, alamat, dan telepon fasilitas"],["organizationStructure","Struktur organisasi dan personel"],["responsiblePerson","Penanggung jawab produksi/mutu"],["processFlow","Alur proses produksi / flowchart"],["rawMaterials","Asal, pemasok, dan persyaratan bahan baku"],["additives","Daftar bumbu/bahan tambahan, merek, pemasok, fungsi, izin edar, halal"],["qualityDocuments","Dokumen pengendalian mutu: nomor, revisi, berlaku, keterangan, berkas"],["equipment","Peralatan: spesifikasi, jumlah, kalibrasi/tera, masa berlaku, kepemilikan"]], true)}</Grid>;
  if (step === 3) return <Grid>{fields("businessLegality", register, [["investmentStatus","PMA/PMDN: nomor, penerbit, tanggal, tempat, berlaku, keterangan"],["establishmentDeed","Akta pendirian UPI"],["amendmentDeed","Akta perubahan UPI / tidak ada"],["industrialLicense","Izin usaha tetap industri"],["npwp","NPWP: nomor, penerbit, tanggal, tempat, berlaku, keterangan"],["attachments","Daftar lampiran dokumen legalitas"]], true)}</Grid>;
  if (step === 4) return <Grid>{fields("humanResources", register, [["workforce","Tenaga kerja S3/S2/S1/SMA-SMK/SMP/SD: tetap, tidak tetap, kualifikasi"],["foreignExperts","Tenaga ahli asing: nama, pendidikan, negara, keterangan / tidak ada"],["trainings","Pelatihan: nama, peserta, penyelenggara, tahun, sertifikat"]], true)}</Grid>;
  if (step === 5) return <Grid>{fields("certificationsAndProducts", register, [["managementCertificates","ISO 9001/HACCP/ISO 22000/lainnya: nomor, tanggal, berlaku, badan sertifikasi, alamat, berkas"],["completeProcessFlow","Alur lengkap produksi/pengolahan dan diagram"],["certifiedProducts","Produk yang akan/telah disertifikasi: jenis dan merek"]], true)}</Grid>;
  if (step === 6) return <Grid>{fields("marketingChannels", register, [["distributors","Distributor/tujuan: alamat, dalam/luar negeri, kontak, jabatan, kota, persentase, keterangan"],["totalPercentage","Total persentase pemasaran"]], true)}</Grid>;
  if (step === 7) return <div className="space-y-4">{questions.map((question, index) => <fieldset key={question} className="rounded-xl border p-4"><legend className="px-1 text-sm font-semibold">{index + 1}. {question}</legend><div className="mt-3 flex gap-5"><label className="text-sm"><input type="radio" value="YES" {...register(`qualitySystemAnswers.${index}.answer`, { required: true })} className="mr-2"/>Ya</label><label className="text-sm"><input type="radio" value="NO" {...register(`qualitySystemAnswers.${index}.answer`, { required: true })} className="mr-2"/>Tidak</label></div><div className="mt-3 grid gap-3 md:grid-cols-2"><label className="text-xs font-semibold">Keterangan<textarea rows={2} {...register(`qualitySystemAnswers.${index}.notes`)} className={inputClass}/></label><label className="text-xs font-semibold">Bukti pendukung<input {...register(`qualitySystemAnswers.${index}.evidence`)} placeholder="Nama atau lokasi berkas" className={inputClass}/></label></div></fieldset>)}</div>;
  if (step === 8) return <Grid>{fields("sniEvaluation", register, [["sniKnowledge","Pengetahuan SNI (Sudah/Belum) dan kesediaan pernyataan"],["productionCompliance","Penerapan proses sesuai SNI (Sudah/Belum) dan alasan"],["productTesting","Pengujian mutu sesuai SNI (Ada/Tidak Ada), hasil uji, dan alasan"]], true)}</Grid>;
  return <div className="space-y-5"><label className="block text-sm font-semibold">Catatan lain<textarea rows={5} maxLength={2000} {...register("otherNotes")} className={inputClass}/></label><label className="flex gap-3 rounded-xl border p-4 text-sm"><input type="checkbox" {...register("declarationAccepted", { required: true })}/>Saya menyatakan seluruh informasi lengkap dan benar serta bersedia diaudit dan diverifikasi oleh LSPro-HP.</label><Grid>{fields("", register, [["signatoryName","Nama penandatangan"],["signatoryPosition","Jabatan"],["approvalDate","Tanggal pengesahan"]])}</Grid><label className="flex gap-3 rounded-xl border p-4 text-sm"><input type="checkbox" {...register("electronicSignatureAccepted", { required: true })}/>Saya menyetujui penggunaan tanda tangan elektronik untuk pengesahan ini.</label><p className="text-xs text-slate-500">Tanda tangan dan cap perusahaan dapat dilampirkan melalui dokumen pendukung permohonan.</p></div>;
}
function Grid({ children }: { readonly children: React.ReactNode }) { return <div className="grid gap-5 md:grid-cols-2">{children}</div>; }
function fields(prefix: string, register: Register, definitions: readonly (readonly [string, string])[], multiline = false) { return definitions.map(([name, label]) => { const path = (prefix ? `${prefix}.${name}` : name) as Parameters<Register>[0]; return <label key={path} className={`text-sm font-semibold ${multiline ? "md:col-span-2" : ""}`}>{label}{multiline ? <textarea rows={3} {...register(path)} className={inputClass}/> : <input type={name === "approvalDate" ? "date" : "text"} {...register(path)} className={inputClass}/>}</label>; }); }
