"use client";
import { Plus, Trash2 } from "lucide-react";

export interface Workforce { pendidikan: string; jumlahTetap: number; jumlahTidakTetap: number; kualifikasi: string }
export interface Expert { id: string; kualifikasi: string; kualifikasiLainnya: string; nama: string; negaraAsal: string; keterangan: string; dokumen: string }
export interface Training { id: string; namaPelatihan: string; namaPeserta: string; penyelenggara: string; tahun: number | ""; dokumen: string }
export interface HumanResourcesData { tenagaKerja: Workforce[]; memilikiTenagaAhliAsing: boolean | null; tenagaAhliAsing: Expert[]; pernahMengikutiPelatihan: boolean | null; alasanTidakPelatihan: string; pelatihan: Training[] }
const levels = ["S3", "S2", "S1", "SMU/SMK", "SMP", "SD"];
export const defaultHumanResources: HumanResourcesData = { tenagaKerja: levels.map((pendidikan) => ({ pendidikan, jumlahTetap: 0, jumlahTidakTetap: 0, kualifikasi: "" })), memilikiTenagaAhliAsing: null, tenagaAhliAsing: [], pernahMengikutiPelatihan: null, alasanTidakPelatihan: "", pelatihan: [] };
const css = "mt-1 w-full rounded-xl border border-slate-200 px-3 py-2 text-sm outline-none focus:border-[#0FA3B1]";
interface Props { value: HumanResourcesData; errors: Record<string,string>; onChange: (value: HumanResourcesData) => void }
export function HumanResourcesForm({ value, errors, onChange }: Props) {
 const workforce = (i:number, patch:Partial<Workforce>) => onChange({...value, tenagaKerja:value.tenagaKerja.map((r,n)=>n===i?{...r,...patch}:r)});
 const expert = (i:number, patch:Partial<Expert>) => onChange({...value, tenagaAhliAsing:value.tenagaAhliAsing.map((r,n)=>n===i?{...r,...patch}:r)});
 const training = (i:number, patch:Partial<Training>) => onChange({...value, pelatihan:value.pelatihan.map((r,n)=>n===i?{...r,...patch}:r)});
 const permanent=value.tenagaKerja.reduce((s,r)=>s+r.jumlahTetap,0), temporary=value.tenagaKerja.reduce((s,r)=>s+r.jumlahTidakTetap,0);
 return <div className="space-y-8"><header><h3 className="text-xl font-bold text-[#073B4C]">V. Sumber Daya Manusia</h3><p className="mt-2 text-sm text-slate-600">Lengkapi informasi tenaga kerja, tenaga ahli asing, dan pelatihan yang pernah diikuti oleh personel UPI sesuai kondisi terbaru.</p></header>
 <Part title="1. Tenaga Kerja" text="Catat jumlah tenaga kerja berdasarkan tingkat pendidikan, status kepegawaian, dan kualifikasinya."><div className="hidden overflow-x-auto rounded-xl border md:block"><table className="w-full min-w-[760px] text-sm"><thead className="bg-[#073B4C] text-left text-white"><tr>{["No","Pendidikan","Tenaga Tetap","Tenaga Tidak Tetap","Kualifikasi"].map(x=><th key={x} className="p-3">{x}</th>)}</tr></thead><tbody>{value.tenagaKerja.map((r,i)=><tr key={r.pendidikan} className="border-t align-top"><td className="p-3">{i+1}</td><td className="p-3 font-semibold">{r.pendidikan}</td><td className="p-2"><Num value={r.jumlahTetap} set={x=>workforce(i,{jumlahTetap:x})}/></td><td className="p-2"><Num value={r.jumlahTidakTetap} set={x=>workforce(i,{jumlahTidakTetap:x})}/></td><td className="p-2"><textarea value={r.kualifikasi} onChange={e=>workforce(i,{kualifikasi:e.target.value})} placeholder="Contoh: Quality Control, operator produksi" className={css}/><Err text={errors[`tenagaKerja.${i}.kualifikasi`]}/></td></tr>)}</tbody></table></div><div className="space-y-3 md:hidden">{value.tenagaKerja.map((r,i)=><div key={r.pendidikan} className="rounded-xl border p-4"><b>{i+1}. {r.pendidikan}</b><div className="grid grid-cols-2 gap-3"><Label text="Tenaga Tetap"><Num value={r.jumlahTetap} set={x=>workforce(i,{jumlahTetap:x})}/></Label><Label text="Tidak Tetap"><Num value={r.jumlahTidakTetap} set={x=>workforce(i,{jumlahTidakTetap:x})}/></Label></div><Label text="Kualifikasi"><textarea value={r.kualifikasi} onChange={e=>workforce(i,{kualifikasi:e.target.value})} className={css}/></Label><Err text={errors[`tenagaKerja.${i}.kualifikasi`]}/></div>)}</div><div className="grid gap-3 rounded-xl bg-slate-50 p-4 text-sm sm:grid-cols-3">{[["Total Tenaga Tetap",permanent],["Total Tenaga Tidak Tetap",temporary],["Total Seluruh Tenaga Kerja",permanent+temporary]].map(([a,b])=><div key={a}><span className="text-slate-500">{a}</span><p className="text-lg font-bold text-[#073B4C]">{b} orang</p></div>)}</div></Part>
 <Part title="2. Tenaga Ahli Asing" text="Informasikan tenaga ahli asing yang bekerja atau mendampingi UPI."><Choice label="Apakah UPI memiliki tenaga ahli asing?" value={value.memilikiTenagaAhliAsing} set={x=>onChange({...value,memilikiTenagaAhliAsing:x,tenagaAhliAsing:x?value.tenagaAhliAsing:[]})}/><Err text={errors.memilikiTenagaAhliAsing}/>{value.memilikiTenagaAhliAsing&&<><Err text={errors.tenagaAhliAsing}/>{value.tenagaAhliAsing.map((r,i)=><Card key={r.id} title={`${i+1}. ${r.nama||"Tenaga ahli baru"}`} remove={()=>onChange({...value,tenagaAhliAsing:value.tenagaAhliAsing.filter((_,n)=>n!==i)})}><Label text="Kualifikasi *"><select value={r.kualifikasi} onChange={e=>expert(i,{kualifikasi:e.target.value})} className={css}><option value="">Pilih kualifikasi</option>{[...levels,"Sertifikasi profesi","Lainnya"].map(x=><option key={x}>{x}</option>)}</select><Err text={errors[`tenagaAhliAsing.${i}.kualifikasi`]}/></Label>{r.kualifikasi==="Lainnya"&&<Label text="Tuliskan kualifikasi *"><input value={r.kualifikasiLainnya} onChange={e=>expert(i,{kualifikasiLainnya:e.target.value})} className={css}/></Label>}<Text label="Nama *" value={r.nama} set={x=>expert(i,{nama:x})} error={errors[`tenagaAhliAsing.${i}.nama`]}/><Text label="Negara Asal *" value={r.negaraAsal} set={x=>expert(i,{negaraAsal:x})} error={errors[`tenagaAhliAsing.${i}.negaraAsal`]}/><Text label="Keterangan *" value={r.keterangan} set={x=>expert(i,{keterangan:x})} error={errors[`tenagaAhliAsing.${i}.keterangan`]}/><File value={r.dokumen} set={x=>expert(i,{dokumen:x})}/></Card>)}<Add text="Tambah Tenaga Ahli Asing" click={()=>onChange({...value,tenagaAhliAsing:[...value.tenagaAhliAsing,{id:crypto.randomUUID(),kualifikasi:"",kualifikasiLainnya:"",nama:"",negaraAsal:"",keterangan:"",dokumen:""}]})}/></>}</Part>
 <Part title="3. Pelatihan yang Diikuti" text="Catat pelatihan yang pernah diikuti personel UPI."><Choice label="Apakah personel UPI pernah mengikuti pelatihan?" value={value.pernahMengikutiPelatihan} set={x=>onChange({...value,pernahMengikutiPelatihan:x,pelatihan:x?value.pelatihan:[]})}/><Err text={errors.pernahMengikutiPelatihan}/>{value.pernahMengikutiPelatihan===false&&<Text label="Alasan atau keterangan (opsional)" value={value.alasanTidakPelatihan} set={x=>onChange({...value,alasanTidakPelatihan:x})}/>} {value.pernahMengikutiPelatihan&&<><Err text={errors.pelatihan}/>{value.pelatihan.map((r,i)=><Card key={r.id} title={`${i+1}. ${r.namaPelatihan||"Pelatihan baru"}`} remove={()=>onChange({...value,pelatihan:value.pelatihan.filter((_,n)=>n!==i)})}><Text label="Nama Pelatihan *" value={r.namaPelatihan} set={x=>training(i,{namaPelatihan:x})} error={errors[`pelatihan.${i}.namaPelatihan`]}/><Text label="Nama Peserta *" value={r.namaPeserta} set={x=>training(i,{namaPeserta:x})} error={errors[`pelatihan.${i}.namaPeserta`]}/><Text label="Penyelenggara *" value={r.penyelenggara} set={x=>training(i,{penyelenggara:x})} error={errors[`pelatihan.${i}.penyelenggara`]}/><Label text="Tahun *"><input type="number" max={new Date().getFullYear()} value={r.tahun} onChange={e=>training(i,{tahun:e.target.value?Number(e.target.value):""})} className={css}/><Err text={errors[`pelatihan.${i}.tahun`]}/></Label><File value={r.dokumen} set={x=>training(i,{dokumen:x})}/></Card>)}<Add text="Tambah Pelatihan" click={()=>onChange({...value,pelatihan:[...value.pelatihan,{id:crypto.randomUUID(),namaPelatihan:"",namaPeserta:"",penyelenggara:"",tahun:"",dokumen:""}]})}/></>}</Part></div>;
}
function Part(p:{title:string;text:string;children:React.ReactNode}) { return <section className="space-y-4 border-t pt-6"><div><h4 className="font-bold text-[#073B4C]">{p.title}</h4><p className="text-sm text-slate-500">{p.text}</p></div>{p.children}</section>; }
function Label(p:{text:string;children:React.ReactNode}) { return <label className="block text-sm font-semibold">{p.text}{p.children}</label>; }
function Num(p:{value:number;set:(x:number)=>void}) { return <input type="number" min="0" step="1" value={p.value} onChange={e=>p.set(Math.max(0,Math.trunc(Number(e.target.value)||0)))} className={css}/>; }
function Err({text}:{text?:string}) { return text?<p role="alert" className="mt-1 text-xs text-[#E63946]">{text}</p>:null; }
function Choice(p:{label:string;value:boolean|null;set:(x:boolean)=>void}) { const options: readonly (readonly [boolean,string])[]=[[true,"Ya"],[false,"Tidak"]]; return <fieldset><legend className="text-sm font-semibold">{p.label}</legend><div className="mt-2 flex gap-6">{options.map(([x,t])=><label key={t}><input type="radio" checked={p.value===x} onChange={()=>p.set(x)} className="mr-2"/>{t}</label>)}</div></fieldset>; }
function Text(p:{label:string;value:string;set:(x:string)=>void;error?:string}) { return <Label text={p.label}><input value={p.value} onChange={e=>p.set(e.target.value)} className={css}/><Err text={p.error}/></Label>; }
function Card(p:{title:string;remove:()=>void;children:React.ReactNode}) { return <div className="rounded-xl border p-4"><div className="flex justify-between"><b>{p.title}</b><button type="button" onClick={p.remove} className="flex gap-1 text-sm text-[#E63946]"><Trash2 size={16}/>Hapus</button></div><div className="mt-3 grid gap-4 md:grid-cols-2">{p.children}</div></div>; }
function Add(p:{text:string;click:()=>void}) { return <button type="button" onClick={p.click} className="flex gap-2 rounded-xl border border-[#087E8B] px-4 py-2 text-sm font-bold text-[#087E8B]"><Plus size={16}/>{p.text}</button>; }
function File(p:{value:string;set:(x:string)=>void}) { return <Label text="Dokumen (opsional)"><input type="file" accept=".pdf,.jpg,.jpeg,.png" onChange={e=>{const f=e.target.files?.[0];if(f&&f.size<=5242880)p.set(f.name)}} className={css}/>{p.value&&<span className="text-xs text-slate-500">{p.value}</span>}</Label>; }
