"use client";

import { useState } from "react";
import { Building2, Pencil, Plus, Trash2, X } from "lucide-react";

export enum MarketingRegion { DOMESTIC = "DOMESTIC", INTERNATIONAL = "INTERNATIONAL" }
export interface MarketingChannel { readonly id: string; distributorName: string; address: string; region: MarketingRegion | ""; destinationCountry: string; destinationCity: string; phoneFax: string; contactName: string; contactPosition: string; marketingCity: string; percentage: number; notes: string }
export interface MarketingChannelsErrors { readonly channels?: string; readonly total?: string }
interface Props { readonly value: readonly MarketingChannel[]; readonly errors: MarketingChannelsErrors; readonly onChange: (value: MarketingChannel[]) => void }
interface FieldErrors {
  distributorName?: string; address?: string; region?: string; destinationCountry?: string;
  destinationCity?: string; contactName?: string; marketingCity?: string; percentage?: string;
}

const inputClass = "mt-1.5 w-full rounded-xl border border-slate-200 bg-white px-3.5 py-2.5 text-sm outline-none focus:border-[#0FA3B1] focus:ring-2 focus:ring-[#0FA3B1]/10";

export function MarketingChannelsForm({ value, errors, onChange }: Props) {
  const [editingIndex, setEditingIndex] = useState<number | null>(null);
  const [draft, setDraft] = useState<MarketingChannel>(emptyChannel);
  const [fieldErrors, setFieldErrors] = useState<FieldErrors>({});
  const total = value.reduce((sum, row) => sum + row.percentage, 0);
  function create() { setDraft(emptyChannel()); setFieldErrors({}); setEditingIndex(value.length); }
  function edit(index: number) { setDraft({ ...value[index] }); setFieldErrors({}); setEditingIndex(index); }
  function close() { setEditingIndex(null); setFieldErrors({}); }
  function saveRow() { const nextErrors = validateRow(draft); const otherTotal = value.reduce((sum, row, index) => sum + (index === editingIndex ? 0 : row.percentage), 0); if (otherTotal + draft.percentage > 100) nextErrors.percentage = "Total persentase pemasaran tidak boleh melebihi 100%."; setFieldErrors(nextErrors); if (Object.keys(nextErrors).length || editingIndex === null) return; const next = [...value]; if (editingIndex === value.length) next.push(draft); else next[editingIndex] = draft; onChange(next); close(); }
  function remove(index: number) { if (window.confirm(`Hapus jalur pemasaran ${value[index].distributorName}?`)) onChange(value.filter((_, itemIndex) => itemIndex !== index)); }
  return <div className="space-y-5">
    <div className="flex flex-col gap-3 sm:flex-row sm:items-start sm:justify-between"><div><h3 className="font-bold text-[#073B4C]">Daftar Jalur Pemasaran</h3><p className="mt-1 text-sm text-slate-500">Catat distributor atau tujuan pemasaran produk di dalam maupun luar negeri.</p></div><button type="button" onClick={create} className="inline-flex items-center justify-center gap-2 rounded-xl bg-[#087E8B] px-4 py-2.5 text-sm font-bold text-white"><Plus size={17}/> Tambah Jalur Pemasaran</button></div>
    {!value.length ? <div className="rounded-2xl border border-dashed bg-slate-50 px-6 py-10 text-center"><Building2 className="mx-auto text-slate-400"/><p className="mt-3 text-sm font-semibold">Belum ada jalur pemasaran</p></div> : <><div className="hidden overflow-x-auto rounded-2xl border lg:block"><table className="w-full min-w-[1500px] text-left text-xs"><thead className="bg-[#073B4C] text-white"><tr>{["No","Nama UPI/Distributor","Alamat","Dalam/Luar Negeri","No. Telepon/Fax","Contact Person Nama","Jabatan","Kota","Persentase","Keterangan","Aksi"].map((item) => <th key={item} className="px-3 py-3.5">{item}</th>)}</tr></thead><tbody className="divide-y">{value.map((row,index) => <tr key={row.id} className="align-top hover:bg-slate-50"><Cell>{index+1}</Cell><Cell strong>{row.distributorName}</Cell><Cell>{row.address}</Cell><Cell><Region row={row}/></Cell><Cell>{row.phoneFax || "-"}</Cell><Cell>{row.contactName}</Cell><Cell>{row.contactPosition || "-"}</Cell><Cell>{row.marketingCity}</Cell><Cell strong>{row.percentage}%</Cell><Cell>{row.notes || "-"}</Cell><Cell><Actions name={row.distributorName} onEdit={() => edit(index)} onDelete={() => remove(index)}/></Cell></tr>)}</tbody></table></div><div className="space-y-3 lg:hidden">{value.map((row,index) => <article key={row.id} className="rounded-2xl border bg-white p-4 shadow-sm"><div className="flex gap-3"><span className="flex h-8 w-8 items-center justify-center rounded-lg bg-[#073B4C] text-sm font-bold text-white">{index+1}</span><div className="min-w-0 flex-1"><h4 className="font-bold text-[#073B4C]">{row.distributorName}</h4><Region row={row}/></div><Actions name={row.distributorName} onEdit={() => edit(index)} onDelete={() => remove(index)}/></div><dl className="mt-4 grid grid-cols-2 gap-3 text-sm"><Info label="Alamat" value={row.address}/><Info label="Telepon/Fax" value={row.phoneFax || "-"}/><Info label="Contact Person" value={row.contactName}/><Info label="Jabatan" value={row.contactPosition || "-"}/><Info label="Kota" value={row.marketingCity}/><Info label="Persentase" value={`${row.percentage}%`}/>{row.notes && <Info label="Keterangan" value={row.notes}/>}</dl></article>)}</div></>}
    {(errors.channels || errors.total) && <p role="alert" className="rounded-xl border border-red-200 bg-red-50 p-3 text-sm font-medium text-[#E63946]">{errors.channels || errors.total}</p>}
    <div className="grid gap-3 sm:grid-cols-2"><Summary label="Jumlah Jalur Pemasaran" value={String(value.length)}/><Summary label="Total Persentase Pemasaran" value={`${total}%`} warning={total !== 100}/></div>
    {editingIndex !== null && <div className="fixed inset-0 z-50 flex items-end justify-center bg-[#073B4C]/45 backdrop-blur-sm sm:items-center sm:p-5" role="dialog" aria-modal="true" aria-labelledby="marketing-title"><div className="max-h-[94vh] w-full overflow-y-auto rounded-t-3xl bg-white shadow-2xl sm:max-w-3xl sm:rounded-3xl"><header className="sticky top-0 z-10 flex items-center justify-between border-b bg-white p-5"><div><h3 id="marketing-title" className="text-lg font-bold text-[#073B4C]">{editingIndex === value.length ? "Tambah" : "Ubah"} Jalur Pemasaran</h3><p className="text-xs text-slate-500">Field bertanda * wajib diisi.</p></div><button type="button" onClick={close} aria-label="Tutup"><X/></button></header><div className="grid gap-4 p-5 sm:grid-cols-2">
      <Text label="Nama UPI/Distributor *" value={draft.distributorName} error={fieldErrors.distributorName} placeholder="Contoh: PT Laut Sejahtera" onChange={(distributorName) => setDraft({...draft,distributorName})}/><Text label="Nomor Telepon/Fax" value={draft.phoneFax} placeholder="Telepon, handphone, atau fax" onChange={(phoneFax) => setDraft({...draft,phoneFax})}/><div className="sm:col-span-2"><Area label="Alamat *" value={draft.address} error={fieldErrors.address} placeholder="Alamat lengkap distributor atau tujuan pemasaran" onChange={(address) => setDraft({...draft,address})}/></div>
      <fieldset className="sm:col-span-2"><legend className="text-sm font-semibold">Wilayah Pemasaran *</legend><div className="mt-2 grid grid-cols-2 gap-3">{([[MarketingRegion.DOMESTIC,"Dalam Negeri"],[MarketingRegion.INTERNATIONAL,"Luar Negeri"]] as const).map(([region,label]) => <label key={region} className={`rounded-xl border p-3 text-sm font-semibold ${draft.region===region ? "border-[#087E8B] bg-cyan-50" : ""}`}><input type="radio" className="mr-2" checked={draft.region===region} onChange={() => setDraft({...draft,region,destinationCountry:region===MarketingRegion.DOMESTIC?"":draft.destinationCountry,destinationCity:region===MarketingRegion.DOMESTIC?"":draft.destinationCity})}/>{label}</label>)}</div><Error text={fieldErrors.region}/></fieldset>
      {draft.region===MarketingRegion.INTERNATIONAL && <><Text label="Negara Tujuan *" value={draft.destinationCountry} error={fieldErrors.destinationCountry} onChange={(destinationCountry) => setDraft({...draft,destinationCountry})}/><Text label="Kota Tujuan *" value={draft.destinationCity} error={fieldErrors.destinationCity} onChange={(destinationCity) => setDraft({...draft,destinationCity})}/></>}
      <Text label="Contact Person – Nama *" value={draft.contactName} error={fieldErrors.contactName} onChange={(contactName) => setDraft({...draft,contactName})}/><Text label="Contact Person – Jabatan" value={draft.contactPosition} onChange={(contactPosition) => setDraft({...draft,contactPosition})}/><Text label="Pemasaran – Kota *" value={draft.marketingCity} error={fieldErrors.marketingCity} onChange={(marketingCity) => setDraft({...draft,marketingCity})}/><label className="text-sm font-semibold">Pemasaran – Persentase *<div className="relative"><input type="number" min="0" max="100" step="0.01" value={draft.percentage} onChange={(event) => setDraft({...draft,percentage:Number(event.target.value)})} className={`${inputClass} pr-9`}/><span className="absolute right-3 top-1/2 text-slate-500">%</span></div><Error text={fieldErrors.percentage}/></label><div className="sm:col-span-2"><Area label="Keterangan" value={draft.notes} placeholder="Distributor utama, retail, buyer ekspor, kontrak tahunan, dan lainnya" onChange={(notes) => setDraft({...draft,notes})}/></div>
    </div><footer className="sticky bottom-0 flex justify-end gap-3 border-t bg-white p-4"><button type="button" onClick={close} className="rounded-xl border px-5 py-2.5 text-sm font-bold">Batal</button><button type="button" onClick={saveRow} className="rounded-xl bg-[#073B4C] px-5 py-2.5 text-sm font-bold text-white">Simpan Jalur</button></footer></div></div>}
  </div>;
}

export function validateMarketingChannels(value: readonly MarketingChannel[]): MarketingChannelsErrors { if (!value.length) return {channels:"Minimal satu jalur pemasaran harus ditambahkan."}; const total=value.reduce((sum,row)=>sum+row.percentage,0); if(total>100)return{total:"Total persentase pemasaran tidak boleh melebihi 100%."}; if(total<100)return{total:"Total persentase pemasaran belum mencapai 100%."}; return {}; }
function validateRow(row: MarketingChannel): FieldErrors { const errors:FieldErrors={}; if(!row.distributorName.trim())errors.distributorName="Nama UPI/Distributor wajib diisi."; if(!row.address.trim())errors.address="Alamat wajib diisi."; if(!row.region)errors.region="Wilayah pemasaran wajib dipilih."; if(row.region===MarketingRegion.INTERNATIONAL&&!row.destinationCountry.trim())errors.destinationCountry="Negara tujuan wajib diisi."; if(row.region===MarketingRegion.INTERNATIONAL&&!row.destinationCity.trim())errors.destinationCity="Kota tujuan wajib diisi."; if(!row.contactName.trim())errors.contactName="Nama contact person wajib diisi."; if(!row.marketingCity.trim())errors.marketingCity="Kota pemasaran wajib diisi."; if(!Number.isFinite(row.percentage)||row.percentage<0||row.percentage>100)errors.percentage="Persentase harus berupa angka dari 0 sampai 100."; return errors; }
function emptyChannel(): MarketingChannel { return {id:globalThis.crypto.randomUUID(),distributorName:"",address:"",region:"",destinationCountry:"",destinationCity:"",phoneFax:"",contactName:"",contactPosition:"",marketingCity:"",percentage:0,notes:""}; }
function Cell({children,strong=false}:{readonly children:React.ReactNode;readonly strong?:boolean}){return <td className={`max-w-52 px-3 py-4 ${strong?"font-bold text-[#073B4C]":""}`}>{children}</td>}
function Region({row}:{readonly row:MarketingChannel}){return <span className="inline-flex rounded-full bg-cyan-50 px-2 py-1 text-[11px] font-bold text-[#087E8B]">{row.region===MarketingRegion.INTERNATIONAL?`Luar Negeri · ${row.destinationCountry}`:"Dalam Negeri"}</span>}
function Actions({name,onEdit,onDelete}:{readonly name:string;readonly onEdit:()=>void;readonly onDelete:()=>void}){return <div className="flex"><button type="button" onClick={onEdit} aria-label={`Ubah ${name}`} className="p-2 text-[#087E8B]"><Pencil size={16}/></button><button type="button" onClick={onDelete} aria-label={`Hapus ${name}`} className="p-2 text-[#E63946]"><Trash2 size={16}/></button></div>}
function Text({label,value,error,placeholder,onChange}:{readonly label:string;readonly value:string;readonly error?:string;readonly placeholder?:string;readonly onChange:(value:string)=>void}){return <label className="text-sm font-semibold">{label}<input value={value} placeholder={placeholder} onChange={(event)=>onChange(event.target.value)} className={inputClass}/><Error text={error}/></label>}
function Area({label,value,error,placeholder,onChange}:{readonly label:string;readonly value:string;readonly error?:string;readonly placeholder?:string;readonly onChange:(value:string)=>void}){return <label className="text-sm font-semibold">{label}<textarea rows={3} value={value} placeholder={placeholder} onChange={(event)=>onChange(event.target.value)} className={inputClass}/><Error text={error}/></label>}
function Error({text}:{readonly text?:string}){return text?<span role="alert" className="mt-1 block text-xs font-medium text-[#E63946]">{text}</span>:null}
function Info({label,value}:{readonly label:string;readonly value:string}){return <div><dt className="text-[11px] font-semibold uppercase text-slate-400">{label}</dt><dd className="mt-0.5 whitespace-pre-line">{value}</dd></div>}
function Summary({label,value,warning=false}:{readonly label:string;readonly value:string;readonly warning?:boolean}){return <div className={`flex items-center justify-between rounded-xl border p-4 ${warning?"border-amber-200 bg-amber-50":"border-emerald-200 bg-emerald-50"}`}><span className="text-sm font-semibold text-slate-600">{label}</span><strong className={warning?"text-xl text-amber-700":"text-xl text-[#2E9F6B]"}>{value}</strong></div>}
