"use client";

import { FileText, LoaderCircle, Pencil, Plus, Trash2, Upload } from "lucide-react";
import { useState } from "react";

export interface FileMetadata { id: string; name: string; originalFileName: string; mimeType: string; size: number; uploadedAt: string }
export interface RawMaterial { id: string; name: string; origin: string; otherOrigin: string; supplierName: string; supplierAddress: string; requirements: string; document: FileMetadata | null }
export interface Additive { id: string; name: string; brand: string; supplierName: string; origin: string; otherOrigin: string; function: string; hasPermit: "YES" | "NO" | "NOT_REQUIRED" | ""; permitNumber: string; halalStatus: "CERTIFIED" | "NOT_CERTIFIED" | "NOT_RELEVANT" | ""; halalCertificateNumber: string; halalValidUntil: string; halalCertificate: FileMetadata | null; document: FileMetadata | null }
export interface QualityDocument { id: string; name: string; number: string; revision: string; effectiveDate: string; description: string; file: FileMetadata | null }
export interface ProductionEquipment { id: string; name: string; specification: string; quantity: number; requiresCalibration: boolean | null; calibrationCertificateNumber: string; calibrationDate: string; calibrationValidUntil: string; calibrationIssuer: string; noCalibrationReason: string; ownershipStatus: "OWNED" | "RENTED" | ""; ownerName: string; rentalAgreementNumber: string; rentalStartDate: string; rentalEndDate: string; document: FileMetadata | null }
export interface ProductionMaterialsData { rawMaterials: RawMaterial[]; additives: Additive[]; qualityDocuments: QualityDocument[]; equipment: ProductionEquipment[] }
export const defaultProductionMaterials: ProductionMaterialsData = { rawMaterials: [], additives: [], qualityDocuments: [], equipment: [] };
export interface ProductionMaterialsErrors { [path: string]: string }

const inputClass = "mt-1.5 w-full rounded-xl border border-slate-200 bg-white px-3.5 py-2.5 text-sm outline-none focus:border-[#0FA3B1] focus:ring-2 focus:ring-[#0FA3B1]/10";
const rawOrigins = ["Nelayan", "Pembudidaya", "Tempat Pelelangan Ikan", "Pemasok tetap", "Distributor", "Cold storage", "Pasar lokal", "Produksi sendiri", "Lainnya"];
const additiveOrigins = ["Produsen", "Distributor resmi", "Pasar lokal", "Importir", "Produksi sendiri", "Lainnya"];

interface Props { readonly applicationId: string; readonly value: ProductionMaterialsData; readonly errors: ProductionMaterialsErrors; readonly onChange: (value: ProductionMaterialsData) => void; readonly onNotice: (message: string) => void }

export function ProductionMaterialsForm({ applicationId, value, errors, onChange, onNotice }: Props) {
  const updateRaw = (index: number, patch: Partial<RawMaterial>) => onChange({ ...value, rawMaterials: replace(value.rawMaterials, index, patch) });
  const updateAdditive = (index: number, patch: Partial<Additive>) => onChange({ ...value, additives: replace(value.additives, index, patch) });
  const updateDocument = (index: number, patch: Partial<QualityDocument>) => onChange({ ...value, qualityDocuments: replace(value.qualityDocuments, index, patch) });
  const updateEquipment = (index: number, patch: Partial<ProductionEquipment>) => onChange({ ...value, equipment: replace(value.equipment, index, patch) });
  return <div className="space-y-6">
    <DynamicSection title="B. Bahan Baku" description="Isi informasi mengenai jenis bahan baku utama yang digunakan dalam proses produksi, asal bahan baku, pemasok, dan persyaratan penerimaannya." addLabel="Tambah Bahan Baku" empty="Belum ada bahan baku. Tambahkan minimal satu bahan baku utama." error={errors.rawMaterials} onAdd={() => onChange({ ...value, rawMaterials: [...value.rawMaterials, newRawMaterial()] })}>
      {value.rawMaterials.map((row, index) => <Entry key={row.id} number={index + 1} title={row.name || "Bahan baku baru"} summary={[originLabel(row.origin, row.otherOrigin), row.supplierName, row.requirements]} onDelete={() => onChange({ ...value, rawMaterials: remove(value.rawMaterials, index) })}>
        <Text label="Nama Bahan Baku *" value={row.name} placeholder="Contoh: Ikan tenggiri segar" error={errors[`rawMaterials.${index}.name`]} onChange={(name) => updateRaw(index, { name })}/>
        <Select label="Asal Bahan Baku *" value={row.origin} options={rawOrigins} error={errors[`rawMaterials.${index}.origin`]} onChange={(origin) => updateRaw(index, { origin, otherOrigin: origin === "Lainnya" ? row.otherOrigin : "" })}/>
        {row.origin === "Lainnya" && <Text label="Tuliskan asal bahan baku *" value={row.otherOrigin} error={errors[`rawMaterials.${index}.otherOrigin`]} onChange={(otherOrigin) => updateRaw(index, { otherOrigin })}/>} 
        <Text label={`Nama Pemasok${row.origin !== "Produksi sendiri" ? " *" : ""}`} value={row.supplierName} placeholder="Contoh: CV Laut Segar Lampung" error={errors[`rawMaterials.${index}.supplierName`]} onChange={(supplierName) => updateRaw(index, { supplierName })}/>
        <Area label="Alamat Pemasok" value={row.supplierAddress} placeholder="Masukkan alamat lengkap pemasok" onChange={(supplierAddress) => updateRaw(index, { supplierAddress })}/>
        <Area label="Persyaratan Bahan Baku *" value={row.requirements} placeholder="Contoh: Segar, tidak berbau busuk, suhu maksimal 4°C, warna normal, dan bebas bahan berbahaya." error={errors[`rawMaterials.${index}.requirements`]} onChange={(requirements) => updateRaw(index, { requirements })}/>
        <FileField applicationId={applicationId} documentName={`Dokumen bahan baku ${row.name || index + 1}`} label="Dokumen Pendukung" value={row.document} maxMb={5} onChange={(document) => updateRaw(index, { document })} onNotice={onNotice}/>
      </Entry>)}
    </DynamicSection>

    <DynamicSection title="C. Bumbu/Bahan Tambahan yang Digunakan" description="Isi seluruh bumbu, bahan tambahan pangan, dan bahan pendukung yang digunakan dalam proses produksi." addLabel="Tambah Bumbu/Bahan Tambahan" empty="Belum ada bumbu atau bahan tambahan." error={errors.additives} onAdd={() => onChange({ ...value, additives: [...value.additives, newAdditive()] })}>
      {value.additives.map((row, index) => <Entry key={row.id} number={index + 1} title={row.name || "Bahan tambahan baru"} summary={[row.brand, row.supplierName, row.function, halalLabel(row.halalStatus)]} onDelete={() => onChange({ ...value, additives: remove(value.additives, index) })}>
        <Text label="Nama Bumbu/Bahan Tambahan *" value={row.name} placeholder="Contoh: Garam, gula, tepung tapioka" error={errors[`additives.${index}.name`]} onChange={(name) => updateAdditive(index, { name })}/>
        <Text label="Merek" value={row.brand} placeholder="Contoh: Cap ABC" onChange={(brand) => updateAdditive(index, { brand })}/>
        <Text label="Nama Pemasok *" value={row.supplierName} placeholder="Contoh: CV Sumber Rasa" error={errors[`additives.${index}.supplierName`]} onChange={(supplierName) => updateAdditive(index, { supplierName })}/>
        <Select label="Asal *" value={row.origin} options={additiveOrigins} error={errors[`additives.${index}.origin`]} onChange={(origin) => updateAdditive(index, { origin, otherOrigin: origin === "Lainnya" ? row.otherOrigin : "" })}/>
        {row.origin === "Lainnya" && <Text label="Tuliskan asal *" value={row.otherOrigin} error={errors[`additives.${index}.otherOrigin`]} onChange={(otherOrigin) => updateAdditive(index, { otherOrigin })}/>} 
        <Text label="Fungsi *" value={row.function} placeholder="Contoh: Pemberi rasa" error={errors[`additives.${index}.function`]} onChange={(fn) => updateAdditive(index, { function: fn })}/>
        <Select label="Apakah bahan memiliki izin edar? *" value={row.hasPermit} options={["YES|Ya", "NO|Tidak", "NOT_REQUIRED|Tidak diperlukan"]} error={errors[`additives.${index}.hasPermit`]} onChange={(hasPermit) => updateAdditive(index, { hasPermit: hasPermit as Additive["hasPermit"], permitNumber: hasPermit === "YES" ? row.permitNumber : "" })}/>
        {row.hasPermit === "YES" && <Text label="Nomor Izin Edar *" value={row.permitNumber} placeholder="Contoh: BPOM RI MD 123456789" error={errors[`additives.${index}.permitNumber`]} onChange={(permitNumber) => updateAdditive(index, { permitNumber })}/>} 
        <Select label="Status Halal *" value={row.halalStatus} options={["CERTIFIED|Bersertifikat halal", "NOT_CERTIFIED|Belum bersertifikat halal", "NOT_RELEVANT|Tidak relevan"]} error={errors[`additives.${index}.halalStatus`]} onChange={(halalStatus) => updateAdditive(index, { halalStatus: halalStatus as Additive["halalStatus"] })}/>
        {row.halalStatus === "CERTIFIED" && <><Text label="Nomor Sertifikat Halal *" value={row.halalCertificateNumber} error={errors[`additives.${index}.halalCertificateNumber`]} onChange={(halalCertificateNumber) => updateAdditive(index, { halalCertificateNumber })}/><DateField label="Masa Berlaku *" value={row.halalValidUntil} error={errors[`additives.${index}.halalValidUntil`]} onChange={(halalValidUntil) => updateAdditive(index, { halalValidUntil })}/><FileField applicationId={applicationId} documentName={`Sertifikat halal ${row.name || index + 1}`} label="Sertifikat Halal *" value={row.halalCertificate} maxMb={5} error={errors[`additives.${index}.halalCertificate`]} onChange={(halalCertificate) => updateAdditive(index, { halalCertificate })} onNotice={onNotice}/></>}
        <FileField applicationId={applicationId} documentName={`Dokumen bahan tambahan ${row.name || index + 1}`} label="Dokumen Lainnya" value={row.document} maxMb={5} onChange={(document) => updateAdditive(index, { document })} onNotice={onNotice}/>
      </Entry>)}
    </DynamicSection>

    <DynamicSection title="D. Dokumen Pengendalian Mutu" description="Tambahkan seluruh dokumen, prosedur, formulir, dan catatan yang digunakan untuk mengendalikan mutu proses produksi." addLabel="Tambah Dokumen Pengendalian Mutu" empty="Belum ada dokumen pengendalian mutu." error={errors.qualityDocuments} onAdd={() => onChange({ ...value, qualityDocuments: [...value.qualityDocuments, newQualityDocument()] })}>
      {value.qualityDocuments.map((row, index) => <Entry key={row.id} number={index + 1} title={row.name || "Dokumen mutu baru"} summary={[row.number, `Revisi ${row.revision || "-"}`, formatDate(row.effectiveDate), row.file?.name]} onDelete={() => onChange({ ...value, qualityDocuments: remove(value.qualityDocuments, index) })}>
        <Text label="Nama Dokumen/Formulir *" value={row.name} placeholder="Contoh: Form Pemeriksaan Bahan Baku" error={errors[`qualityDocuments.${index}.name`]} onChange={(name) => updateDocument(index, { name })}/>
        <Text label="Nomor Dokumen *" value={row.number} placeholder="Contoh: FM-QC-001" error={errors[`qualityDocuments.${index}.number`]} onChange={(number) => updateDocument(index, { number })}/>
        <Text label="Nomor Revisi *" value={row.revision} placeholder="Contoh: 02" error={errors[`qualityDocuments.${index}.revision`]} onChange={(revision) => updateDocument(index, { revision })}/>
        <DateField label="Tanggal Berlaku *" value={row.effectiveDate} error={errors[`qualityDocuments.${index}.effectiveDate`]} onChange={(effectiveDate) => updateDocument(index, { effectiveDate })}/>
        <Area label="Keterangan" value={row.description} placeholder="Contoh: Digunakan untuk mencatat hasil pemeriksaan bahan baku setiap penerimaan." onChange={(description) => updateDocument(index, { description })}/>
        <FileField applicationId={applicationId} documentName={`Dokumen mutu ${row.name || index + 1}`} label="Berkas *" value={row.file} maxMb={10} error={errors[`qualityDocuments.${index}.file`]} onChange={(file) => updateDocument(index, { file })} onNotice={onNotice}/>
      </Entry>)}
    </DynamicSection>

    <DynamicSection title="E. Peralatan Produksi" description="Isi seluruh mesin, alat produksi, alat ukur, dan alat pendukung yang digunakan dalam proses produksi." addLabel="Tambah Peralatan Produksi" empty="Belum ada peralatan. Tambahkan minimal satu peralatan produksi." error={errors.equipment} onAdd={() => onChange({ ...value, equipment: [...value.equipment, newEquipment()] })}>
      {value.equipment.map((row, index) => <Entry key={row.id} number={index + 1} title={row.name || "Peralatan baru"} summary={[row.specification, `${row.quantity} unit`, row.requiresCalibration ? formatCalibration(row.calibrationValidUntil) : "Tidak dikalibrasi/ditera", row.ownershipStatus === "RENTED" ? "Sewa" : row.ownershipStatus === "OWNED" ? "Milik sendiri" : ""]} onDelete={() => onChange({ ...value, equipment: remove(value.equipment, index) })}>
        <Text label="Nama Mesin/Alat Produksi *" value={row.name} placeholder="Contoh: Mesin penggiling ikan" error={errors[`equipment.${index}.name`]} onChange={(name) => updateEquipment(index, { name })}/>
        <Area label="Spesifikasi *" value={row.specification} placeholder="Contoh: Kapasitas 50 kg/jam, bahan stainless steel, daya 1.500 watt." error={errors[`equipment.${index}.specification`]} onChange={(specification) => updateEquipment(index, { specification })}/>
        <NumberField label="Jumlah Unit *" value={row.quantity} error={errors[`equipment.${index}.quantity`]} onChange={(quantity) => updateEquipment(index, { quantity })}/>
        <Choice label="Memerlukan Kalibrasi/Tera *" value={row.requiresCalibration} onChange={(requiresCalibration) => updateEquipment(index, { requiresCalibration })}/>
        {row.requiresCalibration === true ? <><Text label="Nomor Sertifikat Kalibrasi/Tera *" value={row.calibrationCertificateNumber} placeholder="Contoh: KAL-2026-00125" error={errors[`equipment.${index}.calibrationCertificateNumber`]} onChange={(calibrationCertificateNumber) => updateEquipment(index, { calibrationCertificateNumber })}/><DateField label="Tanggal Kalibrasi/Tera *" value={row.calibrationDate} error={errors[`equipment.${index}.calibrationDate`]} onChange={(calibrationDate) => updateEquipment(index, { calibrationDate })}/><DateField label="Masa Berlaku *" value={row.calibrationValidUntil} error={errors[`equipment.${index}.calibrationValidUntil`]} onChange={(calibrationValidUntil) => updateEquipment(index, { calibrationValidUntil })}/><Text label="Lembaga Penerbit *" value={row.calibrationIssuer} error={errors[`equipment.${index}.calibrationIssuer`]} onChange={(calibrationIssuer) => updateEquipment(index, { calibrationIssuer })}/>{calibrationWarning(row.calibrationValidUntil)}</> : row.requiresCalibration === false && <Area label="Alasan tidak memerlukan kalibrasi/tera *" value={row.noCalibrationReason} error={errors[`equipment.${index}.noCalibrationReason`]} onChange={(noCalibrationReason) => updateEquipment(index, { noCalibrationReason })}/>} 
        <Select label="Status Kepemilikan *" value={row.ownershipStatus} options={["OWNED|Milik sendiri", "RENTED|Sewa"]} error={errors[`equipment.${index}.ownershipStatus`]} onChange={(ownershipStatus) => updateEquipment(index, { ownershipStatus: ownershipStatus as ProductionEquipment["ownershipStatus"] })}/>
        {row.ownershipStatus === "RENTED" && <><Text label="Nama Pemilik Alat *" value={row.ownerName} error={errors[`equipment.${index}.ownerName`]} onChange={(ownerName) => updateEquipment(index, { ownerName })}/><Text label="Nomor Perjanjian Sewa *" value={row.rentalAgreementNumber} error={errors[`equipment.${index}.rentalAgreementNumber`]} onChange={(rentalAgreementNumber) => updateEquipment(index, { rentalAgreementNumber })}/><DateField label="Tanggal Mulai Sewa *" value={row.rentalStartDate} error={errors[`equipment.${index}.rentalStartDate`]} onChange={(rentalStartDate) => updateEquipment(index, { rentalStartDate })}/><DateField label="Tanggal Berakhir Sewa *" value={row.rentalEndDate} error={errors[`equipment.${index}.rentalEndDate`]} onChange={(rentalEndDate) => updateEquipment(index, { rentalEndDate })}/></>}
        <FileField applicationId={applicationId} documentName={`Dokumen peralatan ${row.name || index + 1}`} label={row.requiresCalibration || row.ownershipStatus === "RENTED" ? "Dokumen Pendukung *" : "Dokumen Pendukung"} value={row.document} maxMb={10} error={errors[`equipment.${index}.document`]} onChange={(document) => updateEquipment(index, { document })} onNotice={onNotice}/>
      </Entry>)}
    </DynamicSection>
  </div>;
}

function DynamicSection(props: { title: string; description: string; addLabel: string; empty: string; error?: string; onAdd: () => void; children: React.ReactNode }) { return <section className="overflow-hidden rounded-2xl border border-slate-200 bg-white shadow-sm"><div className="border-b bg-slate-50/70 p-5"><h3 className="text-lg font-bold text-[#073B4C]">{props.title}</h3><p className="mt-1 text-sm text-slate-600">{props.description}</p></div><div className="space-y-4 p-5">{props.children}{!props.children || (Array.isArray(props.children) && props.children.length === 0) ? <div className="rounded-xl border border-dashed p-6 text-center text-sm text-slate-500">{props.empty}</div> : null}<ErrorText text={props.error}/><button type="button" onClick={props.onAdd} className="inline-flex items-center gap-2 rounded-xl border border-[#087E8B] px-4 py-2.5 text-sm font-bold text-[#087E8B] hover:bg-cyan-50"><Plus size={17}/>{props.addLabel}</button></div></section>; }
function Entry(props: { number: number; title: string; summary: Array<string | undefined>; onDelete: () => void; children: React.ReactNode }) { return <details open className="group rounded-xl border border-slate-200"><summary className="flex cursor-pointer list-none items-center gap-3 p-4"><span className="flex h-8 w-8 shrink-0 items-center justify-center rounded-lg bg-[#073B4C] text-sm font-bold text-white">{props.number}</span><span className="min-w-0 flex-1"><strong className="block truncate text-sm text-[#073B4C]">{props.title}</strong><span className="mt-0.5 block truncate text-xs text-slate-500">{props.summary.filter(Boolean).join(" • ") || "Lengkapi data berikut"}</span></span><Pencil size={16} className="text-slate-400"/><button type="button" onClick={(event) => { event.preventDefault(); props.onDelete(); }} aria-label={`Hapus ${props.title}`} className="rounded-lg p-2 text-[#E63946] hover:bg-red-50"><Trash2 size={17}/></button></summary><div className="grid gap-4 border-t p-4 md:grid-cols-2">{props.children}</div></details>; }
function Text(props: { label: string; value: string; placeholder?: string; error?: string; onChange: (value: string) => void }) { return <Label text={props.label}><input value={props.value} placeholder={props.placeholder} onChange={(event) => props.onChange(event.target.value)} className={inputClass}/><ErrorText text={props.error}/></Label>; }
function Area(props: { label: string; value: string; placeholder?: string; error?: string; onChange: (value: string) => void }) { return <Label text={props.label}><textarea rows={3} value={props.value} placeholder={props.placeholder} onChange={(event) => props.onChange(event.target.value)} className={inputClass}/><ErrorText text={props.error}/></Label>; }
function Select(props: { label: string; value: string; options: string[]; error?: string; onChange: (value: string) => void }) { return <Label text={props.label}><select value={props.value} onChange={(event) => props.onChange(event.target.value)} className={inputClass}><option value="">Pilih opsi</option>{props.options.map((option) => { const [value, label = option] = option.split("|"); return <option key={value} value={value}>{label}</option>; })}</select><ErrorText text={props.error}/></Label>; }
function DateField(props: { label: string; value: string; error?: string; onChange: (value: string) => void }) { return <Label text={props.label}><input type="date" value={props.value} onChange={(event) => props.onChange(event.target.value)} className={inputClass}/><ErrorText text={props.error}/></Label>; }
function NumberField(props: { label: string; value: number; error?: string; onChange: (value: number) => void }) { return <Label text={props.label}><input type="number" min="1" step="1" value={props.value} onChange={(event) => props.onChange(Math.max(0, Math.trunc(Number(event.target.value) || 0)))} className={inputClass}/><ErrorText text={props.error}/></Label>; }
function Choice(props: { label: string; value: boolean | null; onChange: (value: boolean) => void }) { return <fieldset><legend className="text-sm font-semibold text-slate-700">{props.label}</legend><div className="mt-3 flex gap-5">{([[true, "Ya"], [false, "Tidak"]] as const).map(([value, label]) => <label key={label} className="flex items-center gap-2 text-sm"><input type="radio" checked={props.value === value} onChange={() => props.onChange(value)}/>{label}</label>)}</div></fieldset>; }
function FileField(props: { readonly applicationId: string; readonly documentName: string; readonly label: string; readonly value: FileMetadata | null; readonly maxMb: number; readonly error?: string; readonly onChange: (value: FileMetadata | null) => void; readonly onNotice: (message: string) => void }) {
  const [localError, setLocalError] = useLocalFileError(); const [uploading, setUploading] = useState(false);
  async function select(file?: File) { if (!file) return; if (file.size > props.maxMb * 1024 * 1024 || !["application/pdf", "image/jpeg", "image/png"].includes(file.type)) { setLocalError(`Gunakan berkas PDF, JPG, JPEG, atau PNG dengan ukuran maksimal ${props.maxMb} MB.`); return; } setUploading(true); setLocalError(""); try { const formData = new FormData(); formData.set("file", file); formData.set("documentType", "OTHER"); formData.set("documentName", `${props.documentName} - ${file.name}`); const response = await fetch(`/api/certification-applications/${props.applicationId}/documents`, { method: "POST", body: formData }); const result = await response.json() as { success: boolean; message: string; data?: { id: string; originalFileName: string; mimeType: string; fileSize: string; createdAt: string } }; if (!response.ok || !result.success || !result.data) throw new Error(result.message); props.onChange({ id: result.data.id, name: result.data.originalFileName, originalFileName: result.data.originalFileName, mimeType: result.data.mimeType, size: Number(result.data.fileSize), uploadedAt: result.data.createdAt }); props.onNotice("Dokumen berhasil diunggah dan disimpan sebagai berkas privat."); } catch (error) { setLocalError(error instanceof Error ? error.message : "Dokumen gagal diunggah."); } finally { setUploading(false); } }
  return <div><span className="text-sm font-semibold text-slate-700">{props.label}</span><label className={`mt-1.5 flex items-center gap-3 rounded-xl border border-dashed border-[#0FA3B1] bg-cyan-50/30 p-3 text-sm text-[#087E8B] ${uploading ? "cursor-wait opacity-60" : "cursor-pointer"}`}>{uploading ? <LoaderCircle className="animate-spin" size={18}/> : <Upload size={18}/>}<span className="min-w-0 flex-1 truncate">{uploading ? "Mengunggah dokumen..." : props.value?.originalFileName ?? `Pilih berkas (maks. ${props.maxMb} MB)`}</span><input type="file" disabled={uploading} className="sr-only" accept=".pdf,.jpg,.jpeg,.png" onChange={(event) => { void select(event.target.files?.[0]); event.target.value = ""; }}/></label>{props.value && <div className="mt-2 flex items-center gap-2 text-xs text-slate-500"><FileText size={14}/><span>{formatBytes(props.value.size)} · {new Date(props.value.uploadedAt).toLocaleDateString("id-ID")}</span><a href={`/api/certification-applications/${props.applicationId}/documents/${props.value.id}`} className="font-bold text-[#087E8B]">Unduh</a><button type="button" onClick={() => props.onChange(null)} className="font-bold text-[#E63946]">Lepas</button></div>}<ErrorText text={localError || props.error}/></div>;
}
function Label({ text, children }: { text: string; children: React.ReactNode }) { return <label className="block text-sm font-semibold text-slate-700">{text}{children}</label>; }
function ErrorText({ text }: { text?: string }) { return text ? <p role="alert" className="mt-1 text-xs font-medium text-[#E63946]">{text}</p> : null; }
function useLocalFileError(): [string, (value: string) => void] { return useState(""); }
function replace<T>(items: T[], index: number, patch: Partial<T>): T[] { return items.map((item, itemIndex) => itemIndex === index ? { ...item, ...patch } : item); }
function remove<T>(items: T[], index: number): T[] { return items.filter((_, itemIndex) => itemIndex !== index); }
function id(): string { return globalThis.crypto.randomUUID(); }
function newRawMaterial(): RawMaterial { return { id: id(), name: "", origin: "", otherOrigin: "", supplierName: "", supplierAddress: "", requirements: "", document: null }; }
function newAdditive(): Additive { return { id: id(), name: "", brand: "", supplierName: "", origin: "", otherOrigin: "", function: "", hasPermit: "", permitNumber: "", halalStatus: "", halalCertificateNumber: "", halalValidUntil: "", halalCertificate: null, document: null }; }
function newQualityDocument(): QualityDocument { return { id: id(), name: "", number: "", revision: "", effectiveDate: "", description: "", file: null }; }
function newEquipment(): ProductionEquipment { return { id: id(), name: "", specification: "", quantity: 1, requiresCalibration: null, calibrationCertificateNumber: "", calibrationDate: "", calibrationValidUntil: "", calibrationIssuer: "", noCalibrationReason: "", ownershipStatus: "", ownerName: "", rentalAgreementNumber: "", rentalStartDate: "", rentalEndDate: "", document: null }; }
function originLabel(origin: string, other: string): string { return origin === "Lainnya" ? other : origin; }
function halalLabel(status: Additive["halalStatus"]): string { return ({ CERTIFIED: "Bersertifikat halal", NOT_CERTIFIED: "Belum bersertifikat halal", NOT_RELEVANT: "Tidak relevan", "": "" })[status]; }
function formatDate(value: string): string { return value ? new Date(`${value}T00:00:00`).toLocaleDateString("id-ID") : ""; }
function formatBytes(bytes: number): string { return bytes < 1024 * 1024 ? `${Math.ceil(bytes / 1024)} KB` : `${(bytes / 1024 / 1024).toFixed(1)} MB`; }
function formatCalibration(validUntil: string): string { return validUntil ? `Berlaku ${formatDate(validUntil)}` : "Memerlukan kalibrasi/tera"; }
function calibrationWarning(validUntil: string): React.ReactNode { if (!validUntil) return null; const days = Math.ceil((new Date(`${validUntil}T23:59:59`).getTime() - Date.now()) / 86400000); if (days < 0) return <p className="md:col-span-2 rounded-lg bg-red-50 p-3 text-sm text-red-700">Sertifikat kalibrasi/tera telah berakhir.</p>; if (days <= 30) return <p className="md:col-span-2 rounded-lg bg-amber-50 p-3 text-sm text-amber-800">Sertifikat kalibrasi akan berakhir dalam {days} hari.</p>; return null; }
