CREATE TYPE "TestingApplicationStatus" AS ENUM ('DRAFT','DIAJUKAN','PERLU_PERBAIKAN','DISETUJUI','MENUNGGU_SAMPEL','SAMPEL_DITERIMA','DALAM_PENGUJIAN','SELESAI','DITOLAK');
CREATE TYPE "TestingPurpose" AS ENUM ('EKSPOR','DOMESTIK','SERTIFIKASI','INTERNAL','LAINNYA');
CREATE TYPE "ProductForm" AS ENUM ('FRESH','FROZEN','FILLET','OLAHAN','KERING','HIDUP','LAINNYA');
CREATE TYPE "SampleCondition" AS ENUM ('BEKU','DINGIN','SEGAR','KERING','CAIR','HIDUP','LAINNYA');
CREATE TYPE "ApplicationDocumentType" AS ENUM ('SURAT_PERMOHONAN','INVOICE','PACKING_LIST','HEALTH_CERTIFICATE','FOTO_SAMPEL','LAINNYA');

CREATE TABLE "laboratories" ("id" BIGSERIAL PRIMARY KEY,"code" VARCHAR(40) NOT NULL UNIQUE,"name" VARCHAR(200) NOT NULL,"address" TEXT,"is_active" BOOLEAN NOT NULL DEFAULT true,"created_at" TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,"updated_at" TIMESTAMPTZ(3) NOT NULL,"deleted_at" TIMESTAMPTZ(3));
CREATE TABLE "testing_categories" ("id" BIGSERIAL PRIMARY KEY,"code" VARCHAR(40) NOT NULL UNIQUE,"name" VARCHAR(120) NOT NULL,"sort_order" INTEGER NOT NULL DEFAULT 0,"is_active" BOOLEAN NOT NULL DEFAULT true,"created_at" TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,"updated_at" TIMESTAMPTZ(3) NOT NULL,"deleted_at" TIMESTAMPTZ(3));
CREATE TABLE "testing_parameters" ("id" BIGSERIAL PRIMARY KEY,"testing_category_id" BIGINT NOT NULL,"code" VARCHAR(60) NOT NULL UNIQUE,"name" VARCHAR(160) NOT NULL,"method" VARCHAR(200),"estimated_days" INTEGER,"estimated_cost" DECIMAL(18,2),"is_active" BOOLEAN NOT NULL DEFAULT true,"created_at" TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,"updated_at" TIMESTAMPTZ(3) NOT NULL,"deleted_at" TIMESTAMPTZ(3));
CREATE TABLE "testing_applications" ("id" BIGSERIAL PRIMARY KEY,"application_number" VARCHAR(32) UNIQUE,"business_profile_id" BIGINT NOT NULL,"laboratory_id" BIGINT,"purpose" "TestingPurpose","other_purpose" VARCHAR(200),"testing_types" TEXT[] DEFAULT ARRAY[]::TEXT[],"status" "TestingApplicationStatus" NOT NULL DEFAULT 'DRAFT',"notes" TEXT,"declaration_accepted" BOOLEAN NOT NULL DEFAULT false,"submitted_at" TIMESTAMPTZ(3),"created_at" TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,"updated_at" TIMESTAMPTZ(3) NOT NULL,"deleted_at" TIMESTAMPTZ(3));
CREATE TABLE "testing_application_products" ("id" BIGSERIAL PRIMARY KEY,"testing_application_id" BIGINT NOT NULL UNIQUE,"product_name" VARCHAR(200),"product_type" VARCHAR(160),"hs_code" VARCHAR(32),"product_form" "ProductForm","other_product_form" VARCHAR(160),"description" TEXT,"created_at" TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,"updated_at" TIMESTAMPTZ(3) NOT NULL,"deleted_at" TIMESTAMPTZ(3));
CREATE TABLE "testing_samples" ("id" BIGSERIAL PRIMARY KEY,"testing_application_id" BIGINT NOT NULL,"sample_name" VARCHAR(200),"quantity" INTEGER,"weight" DECIMAL(18,3),"weight_unit" VARCHAR(40),"packaging" VARCHAR(120),"condition" "SampleCondition","sampling_date" DATE,"sampling_location" VARCHAR(250),"temperature" DECIMAL(8,2),"description" TEXT,"created_at" TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,"updated_at" TIMESTAMPTZ(3) NOT NULL,"deleted_at" TIMESTAMPTZ(3));
CREATE TABLE "application_testing_parameters" ("id" BIGSERIAL PRIMARY KEY,"testing_application_id" BIGINT NOT NULL,"testing_sample_id" BIGINT NOT NULL,"testing_parameter_id" BIGINT NOT NULL,"created_at" TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,CONSTRAINT "application_testing_parameters_testing_application_id_testing_sample_id_testing_parameter_id_key" UNIQUE("testing_application_id","testing_sample_id","testing_parameter_id"));
CREATE TABLE "application_documents" ("id" BIGSERIAL PRIMARY KEY,"testing_application_id" BIGINT NOT NULL,"document_type" "ApplicationDocumentType" NOT NULL,"document_name" VARCHAR(200),"file_name" VARCHAR(255) NOT NULL,"file_path" VARCHAR(500) NOT NULL,"mime_type" VARCHAR(120) NOT NULL,"file_size" BIGINT NOT NULL,"uploaded_at" TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,"created_at" TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,"updated_at" TIMESTAMPTZ(3) NOT NULL,"deleted_at" TIMESTAMPTZ(3));
CREATE TABLE "testing_application_counters" ("year" INTEGER PRIMARY KEY,"last_number" INTEGER NOT NULL DEFAULT 0,"updated_at" TIMESTAMPTZ(3) NOT NULL);

CREATE INDEX "laboratories_is_active_deleted_at_idx" ON "laboratories"("is_active","deleted_at"); CREATE INDEX "testing_categories_is_active_sort_order_deleted_at_idx" ON "testing_categories"("is_active","sort_order","deleted_at"); CREATE INDEX "testing_parameters_testing_category_id_is_active_deleted_at_idx" ON "testing_parameters"("testing_category_id","is_active","deleted_at"); CREATE INDEX "testing_parameters_name_idx" ON "testing_parameters"("name"); CREATE INDEX "testing_applications_business_profile_id_status_deleted_at_idx" ON "testing_applications"("business_profile_id","status","deleted_at"); CREATE INDEX "testing_applications_laboratory_id_idx" ON "testing_applications"("laboratory_id"); CREATE INDEX "testing_applications_created_at_idx" ON "testing_applications"("created_at"); CREATE INDEX "testing_application_products_product_name_idx" ON "testing_application_products"("product_name"); CREATE INDEX "testing_samples_testing_application_id_deleted_at_idx" ON "testing_samples"("testing_application_id","deleted_at"); CREATE INDEX "application_testing_parameters_testing_sample_id_idx" ON "application_testing_parameters"("testing_sample_id"); CREATE INDEX "application_testing_parameters_testing_parameter_id_idx" ON "application_testing_parameters"("testing_parameter_id"); CREATE INDEX "application_documents_testing_application_id_deleted_at_idx" ON "application_documents"("testing_application_id","deleted_at");

ALTER TABLE "testing_parameters" ADD CONSTRAINT "testing_parameters_testing_category_id_fkey" FOREIGN KEY ("testing_category_id") REFERENCES "testing_categories"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "testing_applications" ADD CONSTRAINT "testing_applications_business_profile_id_fkey" FOREIGN KEY ("business_profile_id") REFERENCES "business_profiles"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "testing_applications" ADD CONSTRAINT "testing_applications_laboratory_id_fkey" FOREIGN KEY ("laboratory_id") REFERENCES "laboratories"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "testing_application_products" ADD CONSTRAINT "testing_application_products_testing_application_id_fkey" FOREIGN KEY ("testing_application_id") REFERENCES "testing_applications"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "testing_samples" ADD CONSTRAINT "testing_samples_testing_application_id_fkey" FOREIGN KEY ("testing_application_id") REFERENCES "testing_applications"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "application_testing_parameters" ADD CONSTRAINT "application_testing_parameters_testing_application_id_fkey" FOREIGN KEY ("testing_application_id") REFERENCES "testing_applications"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "application_testing_parameters" ADD CONSTRAINT "application_testing_parameters_testing_sample_id_fkey" FOREIGN KEY ("testing_sample_id") REFERENCES "testing_samples"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "application_testing_parameters" ADD CONSTRAINT "application_testing_parameters_testing_parameter_id_fkey" FOREIGN KEY ("testing_parameter_id") REFERENCES "testing_parameters"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "application_documents" ADD CONSTRAINT "application_documents_testing_application_id_fkey" FOREIGN KEY ("testing_application_id") REFERENCES "testing_applications"("id") ON DELETE CASCADE ON UPDATE CASCADE;
