import { ArrowLeft, Download, ExternalLink, FileText, ShieldCheck } from "lucide-react";
import Link from "next/link";
import { notFound, redirect } from "next/navigation";
import { FinalLaboratoryReportForm } from "@/components/dashboard/testing-applications/FinalLaboratoryReportForm";
import { LaboratoryReportDecisionForm } from "@/components/dashboard/testing-applications/LaboratoryReportDecisionForm";
import { getLaboratoryReport } from "@/features/testing-applications/laboratory-report.service";
import { requireReportApprover, requireReportPreparer } from "@/features/testing-applications/testing-application.auth";

interface Props { readonly params: Promise<{ readonly id: string }> }
interface Report {
  readonly reportNumber: string; readonly status: string; readonly reportDate: string; readonly conclusion: string; readonly notes: string | null; readonly approvalNotes: string | null; readonly finalFileName: string | null;
  readonly preparedBy: { readonly profile: { readonly fullName: string } | null }; readonly approvedBy: { readonly profile: { readonly fullName: string } | null } | null;
  readonly application: { readonly applicationNumber: string; readonly purpose: string | null; readonly businessProfile: { readonly business: { readonly name: string } }; readonly laboratory: { readonly name: string } | null; readonly product: { readonly productName: string } | null; readonly workOrders: readonly { readonly id: string; readonly workOrderNumber: string; readonly testingMethod: string | null; readonly applicationParameter: { readonly parameter: { readonly name: string; readonly method: string | null }; readonly sample: { readonly sampleName: string | null } }; readonly documents: readonly { readonly id: string; readonly fileName: string }[] }[] };
}

export default async function LaboratoryReportDetailPage({ params }: Props) {
  let role: "PREPARER" | "APPROVER";
  try { try { await requireReportApprover(); role = "APPROVER"; } catch { await requireReportPreparer(); role = "PREPARER"; } } catch { redirect("/dashboard"); }
  const { id } = await params; if (!/^\d+$/.test(id)) notFound();
  let report: Report; try { report = await getLaboratoryReport(id) as Report; } catch (error) { if (error instanceof Error && error.message === "NOT_FOUND") notFound(); throw error; }
  return <div className="space-y-6">
    <header><Link href="/dashboard/quality-testing/reports" className="inline-flex items-center gap-2 text-sm font-bold text-[#087E8B]"><ArrowLeft size={16} /> Kembali</Link><div className="mt-4 flex flex-wrap items-start justify-between gap-4"><div><p className="text-sm font-bold text-[#087E8B]">{report.reportNumber}</p><h1 className="mt-1 text-3xl font-bold text-[#073B4C]">Laporan Hasil Uji</h1><p className="mt-2 text-sm text-slate-500">{report.application.applicationNumber} · {report.application.businessProfile.business.name}</p></div><span className="rounded-full bg-cyan-50 px-3 py-1 text-xs font-bold text-[#087E8B]">{report.status.replaceAll("_", " ")}</span></div></header>
    <div className="grid gap-6 lg:grid-cols-[minmax(0,1fr)_380px]">
      <main className="space-y-5"><section className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><h2 className="flex items-center gap-2 font-bold text-[#073B4C]"><FileText size={18} /> Identitas LHU</h2><dl className="mt-4 grid gap-4 sm:grid-cols-2"><Info label="Tanggal LHU" value={formatDate(report.reportDate)} /><Info label="Laboratorium" value={report.application.laboratory?.name} /><Info label="Produk" value={report.application.product?.productName} /><Info label="Tujuan" value={report.application.purpose?.replaceAll("_", " ")} /><Info label="Disusun oleh" value={report.preparedBy.profile?.fullName} /><Info label="Disetujui oleh" value={report.approvedBy?.profile?.fullName} /></dl><div className="mt-5 rounded-xl bg-slate-50 p-4"><p className="text-xs font-bold text-slate-500">Kesimpulan</p><p className="mt-2 whitespace-pre-wrap text-sm leading-6 text-slate-700">{report.conclusion}</p></div>{report.notes && <div className="mt-3 rounded-xl bg-slate-50 p-4 text-sm text-slate-700">{report.notes}</div>}</section>
        <section className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><h2 className="font-bold text-[#073B4C]">Hasil Pengujian Terverifikasi</h2><div className="mt-4 space-y-4">{report.application.workOrders.map((workOrder) => <article key={workOrder.id} className="rounded-xl border border-slate-200 p-4"><p className="text-xs font-bold text-[#087E8B]">{workOrder.workOrderNumber}</p><h3 className="mt-1 font-semibold text-slate-700">{workOrder.applicationParameter.parameter.name}</h3><p className="mt-1 text-sm text-slate-500">Sampel {workOrder.applicationParameter.sample.sampleName || "-"} · Metode {workOrder.testingMethod || workOrder.applicationParameter.parameter.method || "-"}</p><div className="mt-3 flex flex-wrap gap-2">{workOrder.documents.map((document) => <a key={document.id} href={`/api/work-orders/${workOrder.id}/documents?documentId=${document.id}`} target="_blank" rel="noreferrer" className="inline-flex items-center gap-1.5 rounded-lg border border-slate-200 px-3 py-2 text-xs font-bold text-[#087E8B]"><ExternalLink size={14} /> {document.fileName}</a>)}</div></article>)}</div></section></main>
      <aside className="h-fit rounded-2xl border border-slate-200 bg-white p-5 shadow-sm">{role === "PREPARER" && report.status === "MENUNGGU_DOKUMEN_FINAL" ? <><h2 className="font-bold text-[#073B4C]">Unggah Dokumen Final</h2><p className="mb-5 mt-2 text-sm leading-6 text-slate-500">LHU telah disetujui Kepala UPTD. Unggah PDF final agar dapat diunduh pelaku usaha.</p><FinalLaboratoryReportForm reportId={id} /></> : role === "APPROVER" && report.status === "MENUNGGU_PERSETUJUAN" ? <><h2 className="font-bold text-[#073B4C]">Keputusan Kepala UPTD</h2><p className="mb-5 mt-2 text-sm leading-6 text-slate-500">Persetujuan akan membuka tahap unggah dokumen final oleh penyelia.</p><LaboratoryReportDecisionForm reportId={id} /></> : <div className="text-center"><ShieldCheck className="mx-auto text-[#2E9F6B]" size={36} /><h2 className="mt-3 font-bold text-[#073B4C]">{report.status === "DITERBITKAN" ? "LHU Telah Diterbitkan" : report.status === "MENUNGGU_DOKUMEN_FINAL" ? "Menunggu Dokumen Final" : "Menunggu Keputusan"}</h2>{report.status === "DITERBITKAN" && <a href={`/api/laboratory-reports/${id}/final-file`} className="mt-4 inline-flex items-center gap-2 rounded-xl bg-[#073B4C] px-4 py-2.5 text-sm font-bold text-white"><Download size={17} /> Unduh {report.finalFileName || "LHU Final"}</a>}{report.approvalNotes && <p className="mt-3 text-sm leading-6 text-slate-500">{report.approvalNotes}</p>}</div>}</aside>
    </div>
  </div>;
}

function Info({ label, value }: { readonly label: string; readonly value?: string | null }) { return <div><dt className="text-xs text-slate-400">{label}</dt><dd className="mt-1 text-sm font-semibold text-slate-700">{value || "-"}</dd></div>; }
function formatDate(value: string): string { return new Intl.DateTimeFormat("id-ID", { dateStyle: "long" }).format(new Date(value)); }
