"use client";

import { zodResolver } from "@hookform/resolvers/zod";
import { AlertCircle, CheckCircle2, LoaderCircle, Save, Search, X } from "lucide-react";
import { useEffect, useMemo, useState } from "react";
import { useForm, useWatch } from "react-hook-form";

import { businessProfileSchema, type BusinessProfileFormValues, type BusinessProfileInput } from "@/lib/business/business-profile-schema";
import { BusinessDocumentSection, type BusinessDocumentDto } from "./BusinessDocumentSection";

interface Option { readonly id: string; readonly name: string; readonly isOther?: boolean; }
interface BusinessProfileData {
  readonly business: { readonly code: string; readonly name: string; readonly status: string; readonly membershipRole: string; readonly canEdit: boolean; readonly canManageDocuments: boolean; readonly updatedAt: string; };
  readonly form: Record<string, unknown> & BusinessProfileFormValues;
  readonly completeness: { readonly completed: number; readonly total: number; readonly percentage: number; readonly missingLabels: readonly string[]; };
  readonly provinces: readonly Option[];
  readonly commodities: readonly Option[];
  readonly documents: readonly BusinessDocumentDto[];
}
interface Props { readonly initialData: BusinessProfileData; }
interface ApiResponse { readonly success: boolean; readonly message: string; readonly data?: BusinessProfileData; readonly errors?: Readonly<Record<string, readonly string[]>>; }

async function fetchRegionOptions(level: "regencies" | "districts" | "villages", parentId: string): Promise<readonly Option[]> {
  const response = await fetch(`/api/regions?level=${level}&parentId=${encodeURIComponent(parentId)}`);
  const result = await response.json() as { readonly success: boolean; readonly data?: readonly Option[] };
  if (!response.ok || !result.data) throw new Error("REGION_LOAD_FAILED");
  return result.data;
}

const inputClass = "min-h-11 w-full rounded-xl border border-slate-200 bg-white px-3.5 text-sm text-navy outline-none transition focus:border-ocean focus:ring-4 focus:ring-ocean/10 disabled:cursor-not-allowed disabled:bg-slate-50";
const sections = [["ringkasan", "Ringkasan"], ["umum", "Informasi Umum"], ["alamat", "Alamat Usaha"], ["kontak", "Kontak & PIC"], ["komoditas", "Komoditas"], ["legalitas", "Legalitas"], ["dokumen", "Dokumen Pendukung"]] as const;
const businessTypes = [["FISH_FARMER", "Pembudidaya"], ["FISHER", "Nelayan"], ["PROCESSOR", "Pengolah"], ["DISTRIBUTOR", "Distributor"], ["EXPORTER", "Eksportir"], ["MSME", "UMKM"], ["OTHER", "Lainnya"]] as const;
const statusLabels: Readonly<Record<string, string>> = { DRAFT: "Draf", PENDING_VERIFICATION: "Menunggu verifikasi", ACTIVE: "Aktif", SUSPENDED: "Ditangguhkan", REJECTED: "Ditolak", INACTIVE: "Tidak aktif" };

function Field({ label, name, register, error, type = "text", placeholder, disabled }: { readonly label: string; readonly name: keyof BusinessProfileFormValues; readonly register: ReturnType<typeof useForm<BusinessProfileFormValues>>["register"]; readonly error?: string; readonly type?: string; readonly placeholder?: string; readonly disabled?: boolean; }) {
  const errorId = `${String(name)}-error`;
  return <label className="block text-sm font-semibold text-navy">{label}<input type={type} placeholder={placeholder} disabled={disabled} {...register(name)} aria-invalid={Boolean(error)} aria-describedby={error ? errorId : undefined} className={`${inputClass} mt-2 ${error ? "border-[#E63946]" : ""}`} />{error && <span id={errorId} className="mt-1.5 block text-xs font-medium text-[#C72F3B]">{error}</span>}</label>;
}
function Section({ id, title, description, children }: { readonly id: string; readonly title: string; readonly description: string; readonly children: React.ReactNode; }) {
  return <section id={id} className="scroll-mt-28 rounded-2xl border border-slate-200 bg-white p-5 shadow-[0_10px_35px_rgba(7,59,76,.04)] sm:p-6"><h2 className="text-lg font-bold text-navy">{title}</h2><p className="mt-1 text-sm leading-6 text-muted">{description}</p><div className="mt-5">{children}</div></section>;
}

export function BusinessProfilePage({ initialData }: Props) {
  const [data, setData] = useState(initialData); const [regencies, setRegencies] = useState<readonly Option[]>([]); const [districts, setDistricts] = useState<readonly Option[]>([]); const [villages, setVillages] = useState<readonly Option[]>([]);
  const [loadingLevel, setLoadingLevel] = useState<string | null>(null); const [message, setMessage] = useState<{ readonly kind: "success" | "error"; readonly text: string } | null>(null); const [commoditySearch, setCommoditySearch] = useState("");
  const { register, handleSubmit, control, setValue, setError, reset, formState: { errors, isSubmitting, isDirty } } = useForm<BusinessProfileFormValues, unknown, BusinessProfileInput>({ resolver: zodResolver(businessProfileSchema), defaultValues: initialData.form, mode: "onTouched" });
  const [provinceId = "", regencyId = "", districtId = "", villageId = "", selectedCommodityIds = []] = useWatch({ control, name: ["provinceId", "regencyId", "districtId", "villageId", "commodityIds"] });
  const canEdit = data.business.canEdit;
  const loadRegions = async (level: "regencies" | "districts" | "villages", parentId: string, preserve = false) => {
    if (!parentId) return;
    setLoadingLevel(level);
    try { const options = await fetchRegionOptions(level, parentId); if (level === "regencies") setRegencies(options); else if (level === "districts") setDistricts(options); else setVillages(options); }
    catch { setMessage({ kind: "error", text: "Data wilayah gagal dimuat. Silakan coba kembali." }); if (!preserve) { if (level === "regencies") setRegencies([]); if (level === "districts") setDistricts([]); if (level === "villages") setVillages([]); } }
    finally { setLoadingLevel(null); }
  };
  useEffect(() => {
    const { provinceId: initialProvinceId, regencyId: initialRegencyId, districtId: initialDistrictId } = initialData.form;
    void fetchRegionOptions("regencies", initialProvinceId).then(setRegencies).catch(() => setMessage({ kind: "error", text: "Data wilayah gagal dimuat. Silakan coba kembali." }));
    if (initialRegencyId) void fetchRegionOptions("districts", initialRegencyId).then(setDistricts).catch(() => setMessage({ kind: "error", text: "Data wilayah gagal dimuat. Silakan coba kembali." }));
    if (initialDistrictId) void fetchRegionOptions("villages", initialDistrictId).then(setVillages).catch(() => setMessage({ kind: "error", text: "Data wilayah gagal dimuat. Silakan coba kembali." }));
  }, [initialData.form]);
  const changeProvince = (value: string) => { setValue("provinceId", value, { shouldDirty: true }); setValue("regencyId", "", { shouldDirty: true }); setValue("districtId", "", { shouldDirty: true }); setValue("villageId", "", { shouldDirty: true }); setDistricts([]); setVillages([]); void loadRegions("regencies", value); };
  const changeRegency = (value: string) => { setValue("regencyId", value, { shouldDirty: true }); setValue("districtId", "", { shouldDirty: true }); setValue("villageId", "", { shouldDirty: true }); setVillages([]); void loadRegions("districts", value); };
  const changeDistrict = (value: string) => { setValue("districtId", value, { shouldDirty: true }); setValue("villageId", "", { shouldDirty: true }); void loadRegions("villages", value); };
  const filteredCommodities = useMemo(() => data.commodities.filter(({ name }) => name.toLowerCase().includes(commoditySearch.toLowerCase())), [commoditySearch, data.commodities]);
  const toggleCommodity = (id: string) => setValue("commodityIds", selectedCommodityIds.includes(id) ? selectedCommodityIds.filter((value) => value !== id) : [...selectedCommodityIds, id], { shouldDirty: true, shouldValidate: true });
  const onSubmit = async (values: BusinessProfileInput) => {
    setMessage(null);
    try { const response = await fetch("/api/business/profile", { method: "PUT", headers: { "Content-Type": "application/json" }, body: JSON.stringify(values) }); const result = await response.json() as ApiResponse; if (!response.ok || !result.data) { for (const [field, fieldMessages] of Object.entries(result.errors ?? {})) { const text = fieldMessages[0]; if (text) setError(field as keyof BusinessProfileInput, { type: "server", message: text }); } setMessage({ kind: "error", text: result.message || "Profil usaha gagal disimpan." }); return; } setData(result.data); reset(result.data.form); setMessage({ kind: "success", text: result.message }); window.scrollTo({ top: 0, behavior: "smooth" }); }
    catch { setMessage({ kind: "error", text: "Koneksi ke server bermasalah. Perubahan Anda belum disimpan." }); }
  };
  const refreshDocuments = async () => {
    const response = await fetch("/api/business/profile", { cache: "no-store" });
    const result = await response.json() as ApiResponse;
    if (!response.ok || !result.data) throw new Error("DOCUMENT_REFRESH_FAILED");
    setData((current) => ({ ...current, business: result.data!.business, completeness: result.data!.completeness, documents: result.data!.documents }));
  };
  const errorFor = (name: keyof BusinessProfileFormValues) => errors[name]?.message?.toString();
  return <form onSubmit={(event) => { if (event.target !== event.currentTarget) return; void handleSubmit(onSubmit)(event); }} noValidate className="space-y-6">
    <header id="ringkasan" className="scroll-mt-28 overflow-hidden rounded-3xl bg-navy p-6 text-white shadow-xl shadow-navy/10 sm:p-8">
      <div className="flex flex-col gap-6 lg:flex-row lg:items-end lg:justify-between"><div><p className="text-xs font-bold uppercase tracking-[.14em] text-aqua">Profil Usaha</p><h1 className="mt-2 text-2xl font-bold sm:text-3xl">{data.business.name}</h1><p className="mt-2 text-sm text-white/70">{data.business.code} · {statusLabels[data.business.status] ?? data.business.status}</p><p className="mt-4 max-w-2xl text-sm leading-6 text-white/75">Lengkapi profil usaha Anda agar dapat menggunakan layanan pengujian mutu, sertifikasi, business matching, dan layanan SIGER-KAN lainnya.</p></div><div className="min-w-64 rounded-2xl bg-white/10 p-4"><div className="flex items-center justify-between"><span className="text-sm font-semibold">Kelengkapan profil</span><strong className="text-2xl">{data.completeness.percentage}%</strong></div><div className="mt-3 h-2 overflow-hidden rounded-full bg-white/15" role="progressbar" aria-valuenow={data.completeness.percentage} aria-valuemin={0} aria-valuemax={100}><div className="h-full rounded-full bg-aqua" style={{ width: `${data.completeness.percentage}%` }} /></div><p className="mt-2 text-xs text-white/70">{data.completeness.completed} dari {data.completeness.total} data telah dilengkapi</p></div></div>
      <div className="mt-5 border-t border-white/10 pt-4 text-xs text-white/65">Terakhir diperbarui {new Intl.DateTimeFormat("id-ID", { dateStyle: "long", timeStyle: "short" }).format(new Date(data.business.updatedAt))}</div>
    </header>
    {message && <div role={message.kind === "error" ? "alert" : "status"} aria-live="polite" className={`flex items-start gap-3 rounded-2xl border px-4 py-3 text-sm font-medium ${message.kind === "success" ? "border-[#2E9F6B]/25 bg-[#EAF8F1] text-[#217A51]" : "border-[#E63946]/20 bg-[#FFF4F5] text-[#C72F3B]"}`}>{message.kind === "success" ? <CheckCircle2 className="h-5 w-5 shrink-0" /> : <AlertCircle className="h-5 w-5 shrink-0" />}{message.text}</div>}
    <nav aria-label="Bagian profil usaha" className="sticky top-20 z-20 -mx-1 overflow-x-auto bg-[#F8FAFC]/95 px-1 py-2 backdrop-blur"><div className="flex min-w-max gap-2">{sections.map(([id, label]) => <a key={id} href={`#${id}`} className="rounded-full border border-slate-200 bg-white px-4 py-2 text-xs font-bold text-navy transition hover:border-ocean hover:text-ocean focus-visible:outline-2 focus-visible:outline-ocean">{label}</a>)}</div></nav>
    {data.completeness.missingLabels.length > 0 && <div className="rounded-2xl border border-gold/30 bg-[#FFF9E9] p-4"><p className="text-sm font-bold text-navy">Prioritas untuk dilengkapi</p><p className="mt-1 text-xs leading-5 text-muted">{data.completeness.missingLabels.slice(0, 6).join(", ")}{data.completeness.missingLabels.length > 6 ? ", dan lainnya." : "."}</p></div>}
    <Section id="umum" title="Informasi Umum" description="Identitas dan gambaran utama kegiatan usaha."><div className="grid gap-5 md:grid-cols-2"><Field label="Nama Usaha *" name="name" register={register} error={errorFor("name")} disabled={!canEdit} /><Field label="Nama Merek / Dagang" name="tradeName" register={register} error={errorFor("tradeName")} disabled={!canEdit} /><label className="text-sm font-semibold text-navy">Jenis Usaha *<select {...register("businessType")} disabled={!canEdit} className={`${inputClass} mt-2`}>{businessTypes.map(([id, name]) => <option key={id} value={id}>{name}</option>)}</select></label><Field label="Jenis Usaha Lainnya" name="businessTypeOther" register={register} error={errorFor("businessTypeOther")} disabled={!canEdit} /><Field label="Bentuk Badan Usaha" name="legalEntityType" register={register} placeholder="Contoh: PT, CV, Koperasi" disabled={!canEdit} /><Field label="Skala Usaha" name="businessScale" register={register} placeholder="Mikro, Kecil, Menengah, atau Besar" disabled={!canEdit} /><Field label="Tahun Berdiri" name="yearEstablished" type="number" register={register} error={errorFor("yearEstablished")} disabled={!canEdit} /><Field label="Status Operasional" name="operationalStatus" register={register} placeholder="Aktif / Tidak aktif" disabled={!canEdit} /><Field label="Jumlah Karyawan" name="employeeCount" type="number" register={register} error={errorFor("employeeCount")} disabled={!canEdit} /><div className="grid grid-cols-2 gap-3"><Field label="Kapasitas Produksi" name="productionCapacity" type="number" register={register} error={errorFor("productionCapacity")} disabled={!canEdit} /><Field label="Satuan" name="productionUnit" register={register} placeholder="kg/bulan" disabled={!canEdit} /></div><label className="md:col-span-2 text-sm font-semibold text-navy">Deskripsi Usaha<textarea {...register("description")} disabled={!canEdit} rows={5} className={`${inputClass} mt-2 py-3`} />{errorFor("description") && <span className="mt-1 block text-xs text-[#C72F3B]">{errorFor("description")}</span>}</label></div></Section>
    <Section id="alamat" title="Alamat Usaha" description="Pilihan wilayah saling terhubung dan diverifikasi kembali saat disimpan."><div className="grid gap-5 md:grid-cols-2">{[["Provinsi *", "provinceId", data.provinces, changeProvince], ["Kabupaten/Kota *", "regencyId", regencies, changeRegency], ["Kecamatan", "districtId", districts, changeDistrict], ["Desa/Kelurahan", "villageId", villages, (v: string) => setValue("villageId", v, { shouldDirty: true })]] .map(([label, name, options, change]) => <label key={String(name)} className="text-sm font-semibold text-navy">{String(label)}<select value={String(name) === "provinceId" ? provinceId : String(name) === "regencyId" ? regencyId : String(name) === "districtId" ? districtId : villageId} onChange={(event) => (change as (value: string) => void)(event.target.value)} disabled={!canEdit || loadingLevel === String(name).replace("Id", "ies")} className={`${inputClass} mt-2`}><option value="">Pilih wilayah</option>{(options as readonly Option[]).map((option) => <option key={option.id} value={option.id}>{option.name}</option>)}</select></label>)}<Field label="Kode Pos" name="postalCode" register={register} error={errorFor("postalCode")} disabled={!canEdit} /><div className="grid grid-cols-2 gap-3"><Field label="Latitude" name="latitude" type="number" register={register} error={errorFor("latitude")} disabled={!canEdit} /><Field label="Longitude" name="longitude" type="number" register={register} error={errorFor("longitude")} disabled={!canEdit} /></div><label className="md:col-span-2 text-sm font-semibold text-navy">Alamat Lengkap<textarea {...register("addressLine")} disabled={!canEdit} rows={4} className={`${inputClass} mt-2 py-3`} /></label></div></Section>
    <Section id="kontak" title="Kontak dan Penanggung Jawab" description="Informasi kontak resmi usaha, terpisah dari email akun login."><div className="grid gap-5 md:grid-cols-2">{([ ["Nama PIC", "picName"], ["Jabatan PIC", "picPosition"], ["Email Usaha", "email", "email"], ["Nomor Telepon", "phone", "tel"], ["Nomor WhatsApp", "whatsapp", "tel"], ["Website", "website", "url"], ["Instagram", "instagram", "url"], ["Facebook", "facebook", "url"], ["TikTok", "tiktok", "url"] ] as const).map(([label, name, type]) => <Field key={name} label={label} name={name} type={type} register={register} error={errorFor(name)} disabled={!canEdit} />)}</div></Section>
    <Section id="komoditas" title="Komoditas" description="Pilih satu atau beberapa komoditas yang dikelola usaha."><div className="relative"><Search className="absolute left-3.5 top-3.5 h-4 w-4 text-muted" /><input value={commoditySearch} onChange={(e) => setCommoditySearch(e.target.value)} placeholder="Cari komoditas" className={`${inputClass} pl-10`} /></div><div className="mt-4 flex flex-wrap gap-2">{selectedCommodityIds.length ? selectedCommodityIds.map((id) => { const item = data.commodities.find((commodity) => commodity.id === id); return item ? <button type="button" disabled={!canEdit} onClick={() => toggleCommodity(id)} key={id} className="inline-flex items-center gap-2 rounded-full bg-seafoam px-3 py-2 text-xs font-bold text-ocean">{item.name}<X className="h-3.5 w-3.5" /></button> : null; }) : <p className="text-sm text-muted">Belum ada komoditas dipilih.</p>}</div><div className="mt-4 grid gap-2 sm:grid-cols-2 lg:grid-cols-3">{filteredCommodities.filter(({ id }) => !selectedCommodityIds.includes(id)).map((item) => <button type="button" disabled={!canEdit} onClick={() => toggleCommodity(item.id)} key={item.id} className="rounded-xl border border-slate-200 px-4 py-3 text-left text-sm font-semibold text-navy hover:border-ocean disabled:opacity-50">+ {item.name}</button>)}</div>{errorFor("commodityIds") && <p className="mt-2 text-xs text-[#C72F3B]">{errorFor("commodityIds")}</p>}</Section>
    <Section id="legalitas" title="Legalitas" description="Nomor identitas legal dicatat sebagai data profil dan tidak mengubah status verifikasi."><div className="grid gap-5 md:grid-cols-2">{([ ["NIB", "nib"], ["NPWP", "taxNumber"], ["SIUP", "siupNumber"], ["PIRT", "pirtNumber"], ["Nomor Sertifikat Halal", "halalNumber"], ["Nomor Izin Edar", "distributionPermitNumber"], ["Nomor Legalitas Lainnya", "otherLegalNumber"] ] as const).map(([label, name]) => <Field key={name} label={label} name={name} register={register} error={errorFor(name)} disabled={!canEdit} />)}</div></Section>
    <section id="dokumen" className="scroll-mt-28 rounded-2xl border border-slate-200 bg-white p-5 shadow-[0_10px_35px_rgba(7,59,76,.04)] sm:p-6"><BusinessDocumentSection documents={data.documents} canManage={data.business.canManageDocuments} onChanged={refreshDocuments} onFeedback={(kind, text) => setMessage({ kind, text })} /></section>
    <div className="sticky bottom-4 z-20 flex flex-col gap-3 rounded-2xl border border-slate-200 bg-white/95 p-4 shadow-xl backdrop-blur sm:flex-row sm:items-center sm:justify-between"><p className="text-xs text-muted">{!canEdit ? "Peran Anda hanya dapat melihat profil ini." : isDirty ? "Ada perubahan yang belum disimpan." : "Semua perubahan telah tersimpan."}</p><div className="flex gap-2"><button type="button" disabled={!isDirty || isSubmitting} onClick={() => { reset(data.form); setMessage(null); }} className="min-h-11 rounded-xl border border-slate-200 px-4 text-sm font-bold text-navy disabled:opacity-50">Batalkan Perubahan</button><button type="submit" disabled={!canEdit || isSubmitting || !isDirty} className="inline-flex min-h-11 items-center justify-center gap-2 rounded-xl bg-navy px-5 text-sm font-bold text-white hover:bg-ocean disabled:cursor-not-allowed disabled:opacity-50">{isSubmitting ? <LoaderCircle className="h-4 w-4 animate-spin" /> : <Save className="h-4 w-4" />}Simpan Perubahan</button></div></div>
  </form>;
}
