"use client";
import { BadgeCheck, LoaderCircle, MailCheck, Pencil, Save, X } from "lucide-react";
import { useRouter } from "next/navigation";
import { useState } from "react";
import type { AdminBusinessDetail } from "@/features/admin-dinas/admin-dinas.types";
import type { AdminBusinessUpdateInput } from "@/features/admin-dinas/admin-dinas.validation";

interface ApiResponse { readonly success: boolean; readonly message: string; }
const inputClass = "mt-1.5 min-h-11 w-full rounded-xl border border-slate-200 px-3.5 text-sm text-navy outline-none focus:border-ocean";
const fields = [["Nama usaha", "name"], ["Nama dagang", "tradeName"], ["Bentuk badan usaha", "legalEntityType"], ["Skala usaha", "businessScale"], ["Tahun berdiri", "yearEstablished"], ["Jumlah tenaga kerja", "employeeCount"], ["Kapasitas produksi", "productionCapacity"], ["Satuan produksi", "productionUnit"], ["Nama PIC", "picName"], ["Jabatan PIC", "picPosition"], ["Email usaha", "email"], ["Telepon", "phone"], ["WhatsApp", "whatsapp"], ["NIB", "nib"], ["NPWP", "taxNumber"], ["SIUP", "siupNumber"], ["PIRT", "pirtNumber"], ["Sertifikat halal", "halalNumber"], ["Izin edar", "distributionPermitNumber"]] as const;

export function AdminBusinessActions({ business }: { readonly business: AdminBusinessDetail }) {
  const router = useRouter(); const [editing, setEditing] = useState(false); const [busy, setBusy] = useState(false); const [message, setMessage] = useState<string | null>(null); const profile = business.profile;
  const initial: AdminBusinessUpdateInput = { name: business.name, tradeName: profile?.tradeName ?? "", legalEntityType: profile?.legalEntityType ?? "", businessScale: profile?.businessScale ?? "", yearEstablished: profile?.yearEstablished?.toString() ?? "", employeeCount: profile?.employeeCount?.toString() ?? "", productionCapacity: profile?.productionCapacity ?? "", productionUnit: profile?.productionUnit ?? "", picName: profile?.picName ?? "", picPosition: profile?.picPosition ?? "", email: profile?.email ?? "", phone: profile?.phone ?? "", whatsapp: profile?.whatsapp ?? "", description: profile?.description ?? "", nib: profile?.nib ?? "", taxNumber: profile?.taxNumber ?? "", siupNumber: profile?.siupNumber ?? "", pirtNumber: profile?.pirtNumber ?? "", halalNumber: profile?.halalNumber ?? "", distributionPermitNumber: profile?.distributionPermitNumber ?? "" };
  const call = async (url: string, method: "POST" | "PUT", body?: AdminBusinessUpdateInput) => { const response = await fetch(url, { method, headers: body ? { "Content-Type": "application/json" } : undefined, body: body ? JSON.stringify(body) : undefined }); const result = await response.json() as ApiResponse; if (!response.ok) throw new Error(result.message); setMessage(result.message); router.refresh(); };
  const verify = async () => { if (!window.confirm("Verifikasi dan aktifkan pelaku usaha ini?")) return; setBusy(true); try { await call(`/api/admin-dinas/businesses/${business.id}/verify`, "POST"); } catch (error) { setMessage(error instanceof Error ? error.message : "Verifikasi gagal."); } finally { setBusy(false); } };
  const save = async (formData: FormData) => { setBusy(true); const values = Object.fromEntries(Object.keys(initial).map((key) => [key, String(formData.get(key) ?? "")])) as unknown as AdminBusinessUpdateInput; try { await call(`/api/admin-dinas/businesses/${business.id}`, "PUT", values); setEditing(false); } catch (error) { setMessage(error instanceof Error ? error.message : "Penyimpanan gagal."); } finally { setBusy(false); } };
  return <section className="mt-5 rounded-2xl border border-slate-200 bg-white p-4"><div className="flex flex-wrap items-center gap-3"><button type="button" onClick={() => setEditing((value) => !value)} className="inline-flex min-h-11 items-center gap-2 rounded-xl border border-ocean/25 px-4 text-sm font-bold text-ocean"><Pencil className="h-4 w-4" />Ubah Data</button><button type="button" disabled={busy || business.status === "ACTIVE"} onClick={() => void verify()} className="inline-flex min-h-11 items-center gap-2 rounded-xl bg-[#2E9F6B] px-4 text-sm font-bold text-white disabled:opacity-50">{busy ? <LoaderCircle className="h-4 w-4 animate-spin" /> : <BadgeCheck className="h-4 w-4" />}{business.status === "ACTIVE" ? "Sudah Diverifikasi" : "Verifikasi Usaha"}</button>{message && <p role="status" className="text-sm font-semibold text-ocean">{message}</p>}</div>{editing && <form action={save} className="mt-5 border-t border-slate-100 pt-5"><div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-3">{fields.map(([label, name]) => <label key={name} className="text-sm font-semibold text-navy">{label}<input name={name} defaultValue={initial[name]} className={inputClass} /></label>)}<label className="sm:col-span-2 lg:col-span-3 text-sm font-semibold text-navy">Deskripsi<textarea name="description" defaultValue={initial.description} rows={4} className={`${inputClass} py-3`} /></label></div><div className="mt-5 flex justify-end gap-2"><button type="button" onClick={() => setEditing(false)} className="inline-flex min-h-11 items-center gap-2 rounded-xl border border-slate-200 px-4 text-sm font-bold text-navy"><X className="h-4 w-4" />Batal</button><button type="submit" disabled={busy} className="inline-flex min-h-11 items-center gap-2 rounded-xl bg-navy px-4 text-sm font-bold text-white"><Save className="h-4 w-4" />Simpan</button></div></form>}</section>;
}

export function EmailActivationButton({ businessId, userId, verified }: { readonly businessId: string; readonly userId: string; readonly verified: boolean }) {
  const router = useRouter(); const [busy, setBusy] = useState(false); const [message, setMessage] = useState<string | null>(null);
  const activate = async () => { if (!window.confirm("Aktifkan email pengguna ini sekarang?")) return; setBusy(true); try { const response = await fetch(`/api/admin-dinas/businesses/${businessId}/members/${userId}/activate-email`, { method: "POST" }); const result = await response.json() as ApiResponse; if (!response.ok) throw new Error(result.message); setMessage(result.message); router.refresh(); } catch (error) { setMessage(error instanceof Error ? error.message : "Aktivasi gagal."); } finally { setBusy(false); } };
  return <div className="mt-3"><button type="button" disabled={busy || verified} onClick={() => void activate()} className="inline-flex min-h-9 items-center gap-2 rounded-lg bg-navy px-3 text-xs font-bold text-white disabled:opacity-50">{busy ? <LoaderCircle className="h-3.5 w-3.5 animate-spin" /> : <MailCheck className="h-3.5 w-3.5" />}{verified ? "Email Aktif" : "Aktifkan Email"}</button>{message && <p role="status" className="mt-2 text-xs font-semibold text-ocean">{message}</p>}</div>;
}
