import { ArrowLeft, Building2, FileBadge2, Fish, Mail, MapPin, Phone, UserRound } from "lucide-react";
import Link from "next/link";

import type { AdminBusinessDetail as AdminBusinessDetailData } from "@/features/admin-dinas/admin-dinas.types";
import { AdminBusinessDocuments } from "./AdminBusinessDocuments";
import { AdminBusinessActions, EmailActivationButton } from "./AdminBusinessActions";

interface AdminBusinessDetailProps {
  readonly business: AdminBusinessDetailData;
  readonly canManage: boolean;
}
const statusLabels: Readonly<Record<string, string>> = { ACTIVE: "Aktif", PENDING_VERIFICATION: "Menunggu verifikasi", DRAFT: "Draf", SUSPENDED: "Ditangguhkan", REJECTED: "Ditolak", INACTIVE: "Tidak aktif", VERIFIED: "Terverifikasi", PENDING: "Menunggu verifikasi", EXPIRED: "Kedaluwarsa" };
const fieldLabels: Readonly<Record<string, string>> = { OWNER: "Pemilik", ADMIN: "Admin", QUALITY_MANAGER: "Manajer Mutu", STAFF: "Staf", VIEWER: "Viewer", PRIMARY: "Utama", SECONDARY: "Pendukung" };
function valueOrDash(value: string | number | null | undefined): string { return value === null || value === undefined || value === "" ? "-" : String(value); }
function Info({ label, value }: { readonly label: string; readonly value: string | number | null | undefined }) { return <div><dt className="text-xs font-semibold text-muted">{label}</dt><dd className="mt-1 text-sm font-bold text-navy">{valueOrDash(value)}</dd></div>; }

export function AdminBusinessDetail({ business, canManage }: AdminBusinessDetailProps) {
  const profile = business.profile;
  return <div>
    <Link href="/dashboard/pelaku-usaha" className="inline-flex items-center gap-2 text-sm font-bold text-ocean hover:underline"><ArrowLeft className="h-4 w-4" />Kembali ke daftar pelaku usaha</Link>
    <header className="mt-5 rounded-3xl bg-navy p-6 text-white shadow-[0_18px_50px_rgba(7,59,76,.16)] sm:p-8"><div className="flex flex-col gap-5 sm:flex-row sm:items-center"><span className="flex h-16 w-16 shrink-0 items-center justify-center rounded-2xl bg-white/10 text-aqua"><Building2 className="h-8 w-8" /></span><div className="flex-1"><p className="text-xs font-bold uppercase tracking-[.14em] text-aqua">{business.code}</p><h1 className="mt-2 text-2xl font-bold sm:text-3xl">{business.name}</h1><p className="mt-2 text-sm text-white/65">{profile?.businessType.replaceAll("_", " ") ?? "Profil usaha belum dilengkapi"}</p></div><span className="w-fit rounded-full bg-white/10 px-4 py-2 text-xs font-bold text-aqua">{statusLabels[business.status] ?? business.status}</span></div></header>
    {canManage && <AdminBusinessActions business={business} />}
    <nav aria-label="Bagian detail pelaku usaha" className="mt-5 flex gap-2 overflow-x-auto rounded-2xl border border-slate-200 bg-white p-2"><a href="#profil" className="rounded-xl px-4 py-2.5 text-sm font-bold text-ocean hover:bg-seafoam">Profil</a><a href="#pengguna" className="rounded-xl px-4 py-2.5 text-sm font-bold text-ocean hover:bg-seafoam">Pengguna</a><a href="#legalitas" className="rounded-xl px-4 py-2.5 text-sm font-bold text-ocean hover:bg-seafoam">Legalitas</a><a href="#komoditas" className="rounded-xl px-4 py-2.5 text-sm font-bold text-ocean hover:bg-seafoam">Komoditas</a></nav>

    <section id="profil" className="mt-6 scroll-mt-24 rounded-3xl border border-slate-200 bg-white p-6 sm:p-7"><div className="flex items-center gap-3"><Building2 className="h-5 w-5 text-ocean" /><h2 className="text-lg font-bold text-navy">Profil Pelaku Usaha</h2></div>{profile ? <><dl className="mt-6 grid gap-5 sm:grid-cols-2 lg:grid-cols-4"><Info label="Nama dagang" value={profile.tradeName} /><Info label="Bentuk badan usaha" value={profile.legalEntityType} /><Info label="Skala usaha" value={profile.businessScale} /><Info label="Tahun berdiri" value={profile.yearEstablished} /><Info label="Jumlah tenaga kerja" value={profile.employeeCount} /><Info label="Kapasitas produksi" value={profile.productionCapacity && `${profile.productionCapacity} ${profile.productionUnit ?? ""}`} /><Info label="Penanggung jawab" value={profile.picName} /><Info label="Jabatan" value={profile.picPosition} /></dl><div className="mt-6 grid gap-3 border-t border-slate-100 pt-6 sm:grid-cols-3"><p className="flex gap-2 text-sm text-muted"><Mail className="h-4 w-4 shrink-0 text-ocean" />{valueOrDash(profile.email)}</p><p className="flex gap-2 text-sm text-muted"><Phone className="h-4 w-4 shrink-0 text-ocean" />{valueOrDash(profile.phone ?? profile.whatsapp)}</p><p className="flex gap-2 text-sm text-muted"><MapPin className="h-4 w-4 shrink-0 text-ocean" />{valueOrDash(profile.address)}</p></div>{profile.description && <p className="mt-5 rounded-2xl bg-slate-50 p-4 text-sm leading-6 text-muted">{profile.description}</p>}</> : <p className="mt-6 text-sm text-muted">Profil usaha belum dilengkapi.</p>}</section>

    <section id="pengguna" className="mt-6 scroll-mt-24 rounded-3xl border border-slate-200 bg-white p-6 sm:p-7"><div className="flex items-center gap-3"><UserRound className="h-5 w-5 text-ocean" /><h2 className="text-lg font-bold text-navy">Pengguna Terhubung</h2></div><div className="mt-5 grid gap-3 md:grid-cols-2">{business.members.map((member) => <article key={member.id} className="rounded-2xl border border-slate-200 p-4"><div className="flex items-start justify-between gap-3"><div><p className="font-bold text-navy">{member.name}</p><p className="mt-1 text-xs text-muted">{member.email}</p>{member.phone && <p className="mt-1 text-xs text-muted">{member.phone}</p>}</div><span className="rounded-full bg-seafoam px-3 py-1 text-[10px] font-bold text-ocean">{fieldLabels[member.role] ?? member.role}</span></div>{canManage && <EmailActivationButton businessId={business.id} userId={member.id} verified={Boolean(member.emailVerifiedAt)} />}</article>)}</div>{business.members.length === 0 && <p className="mt-5 text-sm text-muted">Belum ada pengguna yang terhubung.</p>}</section>

    <section id="legalitas" className="mt-6 scroll-mt-24 rounded-3xl border border-slate-200 bg-white p-6 sm:p-7"><div className="flex items-center gap-3"><FileBadge2 className="h-5 w-5 text-ocean" /><h2 className="text-lg font-bold text-navy">Legalitas Usaha</h2></div>{profile && <dl className="mt-6 grid gap-5 sm:grid-cols-2 lg:grid-cols-3"><Info label="NIB" value={profile.nib} /><Info label="NPWP" value={profile.taxNumber} /><Info label="SIUP" value={profile.siupNumber} /><Info label="PIRT" value={profile.pirtNumber} /><Info label="Sertifikat halal" value={profile.halalNumber} /><Info label="Izin edar" value={profile.distributionPermitNumber} /></dl>}<div className="mt-6 border-t border-slate-100 pt-6"><AdminBusinessDocuments documents={business.documents} /></div></section>

    <section id="komoditas" className="mt-6 scroll-mt-24 rounded-3xl border border-slate-200 bg-white p-6 sm:p-7"><div className="flex items-center gap-3"><Fish className="h-5 w-5 text-ocean" /><h2 className="text-lg font-bold text-navy">Komoditas Usaha</h2></div><div className="mt-5 grid gap-3 sm:grid-cols-2 lg:grid-cols-3">{business.commodities.map((item) => <article key={item.id} className="rounded-2xl border border-slate-200 p-4"><div className="flex items-start justify-between gap-3"><div><p className="font-bold text-navy">{item.name}</p><p className="mt-1 text-xs italic text-muted">{item.scientificName ?? item.description ?? "Nama ilmiah belum tersedia"}</p></div><span className="rounded-full bg-seafoam px-3 py-1 text-[10px] font-bold text-ocean">{fieldLabels[item.priority] ?? item.priority}</span></div></article>)}</div>{business.commodities.length === 0 && <p className="mt-5 text-sm text-muted">Belum ada komoditas yang dipilih.</p>}</section>
  </div>;
}
