import { ActionLink, Icon, type IconName } from "./landing-ui";

const badges: ReadonlyArray<{ label: string; icon: IconName }> = [{ label: "Layanan Terintegrasi", icon: "link" }, { label: "Proses Transparan", icon: "search" }, { label: "Sertifikat Digital", icon: "certificate" }, { label: "Pendampingan Mutu", icon: "heart" }];

export function HeroSection() {
  return <section id="beranda" className="relative overflow-hidden bg-[linear-gradient(135deg,#f5fbfa_0%,#fff_48%,#fff9eb_100%)] pb-20 pt-32 sm:pt-36 lg:min-h-[820px] lg:pb-28 lg:pt-44">
    <div className="soft-grid absolute inset-0 opacity-60 [mask-image:linear-gradient(to_bottom,black,transparent_85%)]"/><div className="absolute -right-24 top-24 h-80 w-80 rounded-full bg-aqua/15 blur-3xl"/><div className="absolute -left-28 bottom-8 h-72 w-72 rounded-full bg-gold/10 blur-3xl"/>
    <div className="container-page relative grid items-center gap-14 lg:grid-cols-[1.05fr_.95fr]">
      <div><div className="mb-7 inline-flex items-center gap-2 rounded-full border border-ocean/15 bg-white/80 px-4 py-2 text-xs font-bold text-ocean shadow-sm"><span className="h-2 w-2 rounded-full bg-gold"/>Platform Layanan Publik Perikanan Lampung</div><h1 className="max-w-3xl text-[2.6rem] font-bold leading-[1.08] tracking-[-.05em] text-navy sm:text-5xl lg:text-[3.65rem]">Satu Platform untuk <span className="relative text-ocean">Mutu, Sertifikasi,<svg className="absolute -bottom-2 left-0 w-full text-gold" viewBox="0 0 260 10" fill="none"><path d="M2 7C70 1 187 1 258 6" stroke="currentColor" strokeWidth="4" strokeLinecap="round"/></svg></span> dan Kemajuan Usaha Perikanan</h1><p className="mt-8 max-w-2xl text-lg leading-8 text-muted">SIGER-KAN menghubungkan pelaku usaha, laboratorium, layanan sertifikasi, klinik mutu, mitra bisnis, dan pemerintah dalam satu ekosistem digital yang transparan, cepat, dan terintegrasi.</p><div className="mt-9 flex flex-col gap-3 sm:flex-row"><ActionLink href="/layanan">Mulai Ajukan Layanan <Icon name="arrow" /></ActionLink><ActionLink href="#tentang" variant="secondary">Pelajari SIGER-KAN</ActionLink></div><div className="mt-9 grid grid-cols-2 gap-x-4 gap-y-3 sm:flex sm:flex-wrap">{badges.map((badge) => <div key={badge.label} className="flex items-center gap-2 text-xs font-semibold text-ink/75 sm:text-sm"><span className="flex h-7 w-7 items-center justify-center rounded-full bg-seafoam text-ocean"><Icon name={badge.icon} className="h-3.5 w-3.5"/></span>{badge.label}</div>)}</div></div>
      <DashboardVisual />
    </div>
    <svg className="absolute bottom-0 left-0 h-12 w-full text-white" viewBox="0 0 1440 80" preserveAspectRatio="none" fill="currentColor"><path d="M0 42c240 47 420-30 720 3s495 29 720-12v47H0Z"/></svg>
  </section>;
}

function DashboardVisual() { return <div className="relative mx-auto w-full max-w-[560px] animate-float lg:ml-auto"><div className="absolute -left-8 top-24 hidden h-20 w-20 rounded-full border border-aqua/30 sm:block"/><div className="absolute -right-8 bottom-24 hidden h-12 w-12 rounded-full bg-gold/20 sm:block"/><div className="glass-card relative overflow-hidden rounded-[2rem] p-3 sm:p-5"><div className="rounded-[1.4rem] border border-navy/7 bg-[#f8fbfb] p-4 sm:p-6"><div className="flex items-center justify-between"><div><p className="text-xs font-semibold text-muted">Pusat Kendali Layanan</p><h2 className="mt-1 font-bold text-navy sm:text-lg">Ringkasan Usaha Anda</h2></div><div className="flex h-10 w-10 items-center justify-center rounded-xl bg-navy text-white"><Icon name="chart"/></div></div><div className="mt-5 grid grid-cols-3 gap-2 sm:gap-3">{[["12", "Layanan"], ["08", "Selesai"], ["04", "Diproses"]].map(([value,label],i)=><div key={label} className="rounded-xl border border-navy/7 bg-white p-3"><strong className={`block text-xl ${i===2?"text-ocean":"text-navy"}`}>{value}</strong><span className="text-[10px] text-muted sm:text-xs">{label}</span></div>)}</div><div className="mt-4 grid gap-4 sm:grid-cols-[1.25fr_.75fr]"><div className="rounded-2xl bg-navy p-4 text-white"><div className="flex justify-between text-xs"><span>Aktivitas Layanan</span><span className="text-aqua">6 bulan</span></div><div className="mt-6 flex h-24 items-end gap-2">{[36,55,44,72,62,88,75,96].map((height,index)=><span key={index} className="flex-1 rounded-t bg-aqua/80" style={{height:`${height}%`}}/>)}</div><div className="mt-2 flex justify-between text-[8px] text-white/45"><span>JAN</span><span>MAR</span><span>MEI</span><span>JUL</span></div></div><div className="rounded-2xl border border-navy/7 bg-white p-4"><div className="flex items-center justify-between"><span className="text-xs font-semibold text-navy">Status Mutu</span><span className="h-2 w-2 animate-pulse-soft rounded-full bg-[#2E9F6B]"/></div><div className="mx-auto mt-4 flex h-24 w-24 items-center justify-center rounded-full bg-[conic-gradient(#0FA3B1_0_82%,#DDF4F1_82%)]"><div className="flex h-16 w-16 flex-col items-center justify-center rounded-full bg-white"><strong className="text-xl text-navy">82%</strong><span className="text-[9px] text-muted">Terpenuhi</span></div></div></div></div><div className="mt-4 flex items-center gap-3 rounded-2xl border border-[#2E9F6B]/20 bg-[#eefaf4] p-3"><span className="flex h-9 w-9 items-center justify-center rounded-xl bg-[#2E9F6B] text-white"><Icon name="check"/></span><div className="min-w-0"><p className="truncate text-xs font-bold text-navy">Pengujian sampel berhasil diverifikasi</p><p className="mt-0.5 text-[10px] text-muted">LHU-2026-00742 · Hari ini, 10.24 WIB</p></div></div></div></div></div> }
