import type { TestingApplicationStatus } from "@/app/generated/prisma/client";
import { ApplicationStatusBadge } from "@/components/dashboard/testing-applications/ApplicationStatusBadge";
import { requireSampleReceptionOfficer } from "@/features/testing-applications/testing-application.auth";
import { listReceptionApplications } from "@/features/testing-applications/testing-application.service";
import { Search } from "lucide-react";
import Link from "next/link";
import { redirect } from "next/navigation";

interface Props { readonly searchParams: Promise<{ readonly q?: string; readonly status?: string; readonly updated?: string }> }
interface Item { readonly id: string; readonly applicationNumber: string | null; readonly status: string; readonly submittedAt: string | null; readonly businessProfile: { readonly business: { readonly name: string } }; readonly laboratory: { readonly name: string } | null; readonly product: { readonly productName: string | null } | null; readonly _count: { readonly samples: number; readonly documents: number } }
const statuses = ["DIAJUKAN", "PERLU_PERBAIKAN", "DISETUJUI"] as const;

export default async function SampleReceptionPage({ searchParams }: Props) {
  try { await requireSampleReceptionOfficer(); } catch (error) { if (error instanceof Error && error.message === "UNAUTHENTICATED") redirect("/login"); redirect("/dashboard"); }
  const query = await searchParams; const status = statuses.find((item) => item === query.status) as TestingApplicationStatus | undefined;
  const items = await listReceptionApplications({ search: query.q, status }) as Item[];
  return <div className="space-y-6"><header><p className="text-sm font-semibold text-[#087E8B]">Pengujian Mutu</p><h1 className="mt-1 text-3xl font-bold text-[#073B4C]">Penerimaan Sampel</h1><p className="mt-2 text-sm text-slate-500">Periksa kelengkapan permohonan sebelum sampel diterima laboratorium.</p></header>{query.updated === "1" && <p className="rounded-xl border border-emerald-200 bg-emerald-50 p-4 text-sm text-emerald-700">Keputusan verifikasi berhasil disimpan.</p>}<form className="grid gap-3 rounded-2xl border border-slate-200 bg-white p-4 sm:grid-cols-[1fr_220px_auto]"><label className="relative"><Search className="absolute left-3 top-3 h-4 w-4 text-slate-400"/><input name="q" defaultValue={query.q} placeholder="Cari nomor, usaha, atau produk" className="w-full rounded-xl border border-slate-200 py-2.5 pl-10 pr-3 text-sm"/></label><select name="status" defaultValue={query.status ?? ""} className="rounded-xl border border-slate-200 px-3 py-2.5 text-sm"><option value="">Semua status</option>{statuses.map((item) => <option key={item} value={item}>{item.replaceAll("_", " ")}</option>)}</select><button className="rounded-xl bg-[#073B4C] px-5 py-2.5 text-sm font-bold text-white">Terapkan</button></form><section className="overflow-hidden rounded-2xl border border-slate-200 bg-white shadow-sm"><div className="border-b border-slate-100 px-5 py-4"><h2 className="font-bold text-[#073B4C]">Antrean Permohonan</h2></div>{items.length === 0 ? <p className="p-10 text-center text-sm text-slate-500">Tidak ada permohonan pada antrean ini.</p> : <div className="divide-y divide-slate-100">{items.map((item) => <article key={item.id} className="grid gap-4 p-5 lg:grid-cols-[1.2fr_1fr_auto] lg:items-center"><div><p className="text-sm font-bold text-[#087E8B]">{item.applicationNumber}</p><h3 className="mt-1 font-bold text-[#073B4C]">{item.businessProfile.business.name}</h3><p className="mt-1 text-sm text-slate-500">{item.product?.productName ?? "Produk belum diberi nama"} · {item.laboratory?.name ?? "Laboratorium belum dipilih"}</p></div><div className="text-sm text-slate-500"><ApplicationStatusBadge status={item.status}/><p className="mt-2">{item._count.samples} sampel · {item._count.documents} dokumen</p></div><Link href={`/dashboard/quality-testing/sample-reception/${item.id}`} className="rounded-xl border border-[#087E8B] px-4 py-2.5 text-center text-sm font-bold text-[#087E8B]">Periksa</Link></article>)}</div>}</section></div>;
}
